import { randomUUID } from "node:crypto";
import { cp, mkdir, readdir, readFile, rename, rm, stat } from "node:fs/promises";
import { basename, extname, join, relative, resolve, sep } from "node:path";
import { zipSync } from "fflate";
import { z } from "zod";
import { FfmpegTools, runCommand } from "../audio/ffmpeg.js";
import { Environment } from "../config/env.js";
import { defaultStory, loadStory } from "../config/load-config.js";
import { Chapter, chapterSchema } from "../domain/chapter.js";
import { Story, storySchema } from "../domain/story.js";
import { atomicWrite, atomicWriteJson } from "../storage/atomic-write.js";
import { storyPaths } from "../storage/paths.js";
import { exists, readJsonIfExists } from "../storage/story-files.js";
import { withStoryLock } from "../storage/story-lock.js";
import { readSafeZipBytes } from "../source/zip-safety.js";

export const safeSlugSchema = z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(80);
export const storyMetadataSchema = z.object({ title: z.string().trim().min(1).max(200), author: z.string().trim().max(200).optional(), description: z.string().max(10_000).default(""), tags: z.array(z.string().trim().min(1).max(60)).max(30).default([]), notes: z.string().max(20_000).default(""), sourceLanguage: z.string().trim().min(2).max(30), outputLanguage: z.string().trim().min(2).max(30) });
export type Activity = { id: string; type: string; message: string; at: string };
const activitySchema = z.array(z.object({ id: z.string(), type: z.string(), message: z.string(), at: z.string() })).default([]);
export const cleanupKindSchema = z.enum(["voicePreviews", "abPreviews", "oldProductionManifests", "artwork", "chapterVideo", "exports"]);

export const globalSettingsSchema = z.object({ defaultSourceLanguage: z.string().min(2), defaultOutputLanguage: z.string().min(2), defaultProductionProfile: z.enum(["audio", "audiobook", "story-video", "everything"]), translation: modelSchema(), narration: modelSchema(), qa: modelSchema(), storyBible: modelSchema(), scenePlanner: modelSchema(), tts: z.object({ provider: z.literal("fish"), model: z.string().min(1), referenceId: z.string().optional() }) });
export type GlobalSettings = z.infer<typeof globalSettingsSchema>;

export async function loadGlobalSettings(root: string, env: Environment): Promise<GlobalSettings> { const raw = await readJsonIfExists<Record<string, unknown>>(globalSettingsPath(root)); const defaults = { defaultSourceLanguage: "zh-CN", defaultOutputLanguage: "en-US", defaultProductionProfile: "audiobook" as const, translation: { provider: "gemini" as const, model: env.GEMINI_DEFAULT_MODEL }, narration: { provider: "openai" as const, model: env.OPENAI_DEFAULT_MODEL }, qa: { provider: "openai" as const, model: env.OPENAI_DEFAULT_MODEL }, storyBible: { provider: "gemini" as const, model: env.GEMINI_DEFAULT_MODEL }, scenePlanner: { provider: "openai" as const, model: env.OPENAI_DEFAULT_MODEL }, tts: { provider: "fish" as const, model: env.FISH_AUDIO_MODEL, referenceId: env.FISH_AUDIO_REFERENCE_ID } }; return globalSettingsSchema.parse(raw ? { ...defaults, ...raw } : defaults); }
export async function saveGlobalSettings(root: string, value: unknown) { const settings = globalSettingsSchema.parse(value); await atomicWriteJson(globalSettingsPath(root), settings); return settings; }

export async function createBlankStory(root: string, env: Environment, raw: unknown) {
  const input = storyMetadataSchema.extend({ slug: safeSlugSchema, sourceLanguage: z.string().trim().min(2).max(30).optional(), outputLanguage: z.string().trim().min(2).max(30).optional() }).parse(raw); const paths = storyPaths(root, input.slug, 1); if (await exists(paths.story)) throw new Error(`Story '${input.slug}' already exists`);
  const defaults = await loadGlobalSettings(root, env); let story = defaultStory(input.slug, env); story = storySchema.parse({ ...story, ...input, source: { type: "original" }, sourceLanguage: input.sourceLanguage ?? defaults.defaultSourceLanguage, outputLanguage: input.outputLanguage ?? defaults.defaultOutputLanguage, defaultProductionProfile: defaults.defaultProductionProfile, pipeline: { ...story.pipeline, translation: defaults.translation, narration: defaults.narration, qa: defaults.qa, storyBible: defaults.storyBible, scenePlanner: defaults.scenePlanner, tts: { ...story.pipeline.tts, model: defaults.tts.model, referenceId: defaults.tts.referenceId } } });
  const stage = join(root, "stories", `.create-${randomUUID()}`); await mkdir(stage, { recursive: true }); try { await atomicWriteJson(join(stage, "story.json"), story); await atomicWriteJson(join(stage, "pipeline.json"), story.pipeline); await rename(stage, paths.story); } catch (error) { await rm(stage, { recursive: true, force: true }); throw error; }
  await recordActivity(root, input.slug, "story.created", "Created story project"); return story;
}

export async function updateStoryMetadata(root: string, slug: string, raw: unknown) { safeSlugSchema.parse(slug); const input = storyMetadataSchema.parse(raw); return withStoryLock(root, slug, "story metadata update", async () => { const paths = storyPaths(root, slug, 1); const current = await loadStory(paths.storyConfig); const story = storySchema.parse({ ...current, ...input }); await atomicWriteJson(paths.storyConfig, story); await recordActivity(root, slug, "story.metadata", "Updated story information"); return story; }); }

export async function saveCover(root: string, slug: string, filename: string, bytes: Uint8Array) { safeSlugSchema.parse(slug); const extension = extname(basename(filename)).toLowerCase(); if (![".jpg", ".jpeg", ".png"].includes(extension)) throw new Error("Cover must be a JPG or PNG image"); if (!bytes.length || bytes.length > 15 * 1024 * 1024) throw new Error("Cover must be between 1 byte and 15 MB"); validateImageSignature(extension, bytes); return withStoryLock(root, slug, "cover update", async () => { const paths = storyPaths(root, slug, 1); if (!(await exists(paths.storyConfig))) throw new Error(`Story '${slug}' was not found`); const target = join(paths.story, `cover${extension}`); await atomicWrite(target, bytes); for (const name of ["cover.jpg", "cover.jpeg", "cover.png"]) if (join(paths.story, name) !== target) await rm(join(paths.story, name), { force: true }); await invalidateChapterVideo(root, slug); await recordActivity(root, slug, "story.cover", "Updated story cover; chapter video marked stale"); return { coverUrl: `/api/stories/${slug}/cover` }; }); }

export async function duplicateStory(root: string, sourceSlug: string, requestedSlug: string, mode: "settings" | "full") { safeSlugSchema.parse(sourceSlug); safeSlugSchema.parse(requestedSlug); const source = storyPaths(root, sourceSlug, 1).story; if (!(await exists(join(source, "story.json")))) throw new Error(`Story '${sourceSlug}' was not found`); const slug = await uniqueSlug(root, requestedSlug); const stage = join(root, "stories", `.duplicate-${randomUUID()}`); const target = storyPaths(root, slug, 1).story;
  try { await mkdir(stage, { recursive: true }); if (mode === "full") { await rm(stage, { recursive: true, force: true }); await cp(source, stage, { recursive: true, filter: (path) => ![".lock"].includes(basename(path)) && !basename(path).endsWith(".tmp") }); } else { for (const name of ["story.json", "pipeline.json", "cover.jpg", "cover.jpeg", "cover.png"]) if (await exists(join(source, name))) await cp(join(source, name), join(stage, name)); }
    const story = await loadStory(join(stage, "story.json")); const copy = storySchema.parse({ ...story, id: slug, slug, title: `${story.title} Copy` }); await atomicWriteJson(join(stage, "story.json"), copy); await atomicWriteJson(join(stage, "pipeline.json"), copy.pipeline); await rename(stage, target); await recordActivity(root, slug, "story.duplicated", `Duplicated from ${sourceSlug} (${mode === "full" ? "full project" : "settings only"})`); return { story: copy, slug };
  } catch (error) { await rm(stage, { recursive: true, force: true }); throw error; }
}

export async function deleteStory(root: string, slug: string, confirmation: string) { safeSlugSchema.parse(slug); const paths = storyPaths(root, slug, 1); const story = await loadStory(paths.storyConfig); if (confirmation !== story.title) throw new Error("Confirmation must exactly match the story title"); const trash = join(root, "stories", ".trash"); await mkdir(trash, { recursive: true }); const destination = join(trash, `${slug}-${Date.now()}`); await withStoryLock(root, slug, "story deletion", async () => { await rename(paths.story, destination); await rm(join(destination, ".lock"), { recursive: true, force: true }); }); return { deleted: slug, recoverable: true }; }

export async function buildStoryBackup(root: string, slug: string, includeMedia: boolean) { safeSlugSchema.parse(slug); return withStoryLock(root, slug, "project backup", async () => { const storyRoot = storyPaths(root, slug, 1).story; const files = await walk(storyRoot); const archive: Record<string, Uint8Array> = {}; let expandedBytes = 0; for (const path of files) { const rel = relative(storyRoot, path).split(sep).join("/"); if (shouldExcludeBackup(rel, includeMedia)) continue; const info = await stat(path); if (info.size > 25 * 1024 * 1024) throw new Error(`Backup file exceeds the 25 MB per-file limit: ${rel}`); expandedBytes += info.size; if (expandedBytes > 300 * 1024 * 1024) throw new Error("Backup exceeds the 300 MB expanded-size limit"); archive[rel] = await readFile(path); } archive["backup.json"] = Buffer.from(JSON.stringify({ format: "ai-story-studio", version: 1, slug, includeMedia, createdAt: new Date().toISOString() })); const bytes = zipSync(archive, { level: 6 }); if (bytes.length > 100 * 1024 * 1024) throw new Error("Backup exceeds the 100 MB archive-size limit"); const id = randomUUID(); const directory = join(root, ".ai-story-studio", "backups"); await mkdir(directory, { recursive: true }); await atomicWrite(join(directory, `${id}.zip`), bytes); await recordActivity(root, slug, "backup.created", `Created ${includeMedia ? "full" : "project-only"} backup`); return { id, filename: `${slug}-${includeMedia ? "full" : "project"}.zip`, bytes: bytes.length, downloadUrl: `/api/backups/${id}.zip` }; }); }

export async function restoreStoryBackup(root: string, bytes: Uint8Array) { const archive = readSafeZipBytes(bytes); validateArchiveNames(Object.keys(archive)); const descriptorBytes = archive["backup.json"]; const storyBytes = archive["story.json"]; if (!descriptorBytes || !storyBytes) throw new Error("Backup must contain backup.json and story.json"); const descriptor = z.object({ format: z.literal("ai-story-studio"), version: z.literal(1), slug: safeSlugSchema }).passthrough().parse(JSON.parse(Buffer.from(descriptorBytes).toString("utf8"))); const original = storySchema.parse(JSON.parse(Buffer.from(storyBytes).toString("utf8"))); const slug = await uniqueSlug(root, descriptor.slug); const stage = join(root, "stories", `.restore-${randomUUID()}`); try { await mkdir(stage, { recursive: true }); for (const [name, data] of Object.entries(archive)) { if (name === "backup.json" || name.endsWith("/")) continue; await atomicWrite(join(stage, name), data); } const restored = storySchema.parse({ ...original, id: slug, slug, ...(slug === original.slug ? {} : { title: `${original.title} Restored` }) }); await atomicWriteJson(join(stage, "story.json"), restored); await atomicWriteJson(join(stage, "pipeline.json"), restored.pipeline); await rename(stage, storyPaths(root, slug, 1).story); await recordActivity(root, slug, "backup.restored", `Restored backup from ${descriptor.slug}`); return { slug, story: restored }; } catch (error) { await rm(stage, { recursive: true, force: true }); throw error; } }

export async function getStorageUsage(root: string, slug: string) { safeSlugSchema.parse(slug); const story = storyPaths(root, slug, 1).story; const totals: Record<string, number> = { source: 0, text: 0, ttsRaw: 0, masteredAudio: 0, artwork: 0, video: 0, previews: 0, exports: 0, other: 0, total: 0 }; for (const path of await walk(story)) { const bytes = (await stat(path)).size; const rel = relative(story, path).split(sep).join("/"); const category = storageCategory(rel); totals[category] += bytes; totals.total += bytes; } return totals; }

export async function cleanupStory(root: string, slug: string, kind: z.infer<typeof cleanupKindSchema>) { safeSlugSchema.parse(slug); cleanupKindSchema.parse(kind); return withStoryLock(root, slug, `cleanup ${kind}`, async () => { const paths = storyPaths(root, slug, 1); let removed = 0; const removeTarget = async (path: string) => { if (await exists(path)) { removed += await pathSize(path); await rm(path, { recursive: true, force: true }); } };
    if (kind === "voicePreviews") await removeTarget(join(paths.story, "voice-previews")); else if (kind === "abPreviews") await removeTarget(join(paths.story, "previews")); else if (kind === "exports") await removeTarget(join(paths.story, "exports")); else if (kind === "oldProductionManifests") { const directory = join(paths.story, "production-runs"); if (await exists(directory)) for (const name of await readdir(directory)) if (name !== "latest.json") await removeTarget(join(directory, name)); }
    else { for (const entry of await readdir(join(paths.story, "chapters"), { withFileTypes: true }).catch(() => [])) if (entry.isDirectory()) { const number = Number(entry.name); if (!Number.isSafeInteger(number)) continue; const chapterPaths = storyPaths(root, slug, number); if (kind === "chapterVideo") { await removeTarget(chapterPaths.video); await markPending(chapterPaths.chapterMeta, ["video"]); } else { await removeTarget(chapterPaths.scenesDirectory); await markPending(chapterPaths.chapterMeta, ["artwork", "video"]); } } }
    await recordActivity(root, slug, "storage.cleanup", `Cleaned ${kind} (${removed} bytes)`); return { kind, removedBytes: removed }; }); }

export async function readActivity(root: string, slug: string, limit = 30) { safeSlugSchema.parse(slug); const items = activitySchema.parse((await readJsonIfExists(activityPath(root, slug))) ?? []); return items.slice(-Math.min(100, Math.max(1, limit))).reverse(); }
export async function recordActivity(root: string, slug: string, type: string, message: string) { const path = activityPath(root, slug); const items = activitySchema.parse((await readJsonIfExists(path)) ?? []); items.push({ id: randomUUID(), type, message, at: new Date().toISOString() }); await atomicWriteJson(path, items.slice(-500)); }
export async function systemStatus(env: Environment) { const tools = new FfmpegTools(); let ffmpeg = false; let ffprobe = false; try { await runCommand(tools.ffmpegPath, ["-version"], 5_000); ffmpeg = true; } catch {} try { await runCommand(tools.ffprobePath, ["-version"], 5_000); ffprobe = true; } catch {} return { providers: { openai: Boolean(env.OPENAI_API_KEY), gemini: Boolean(env.GEMINI_API_KEY), fish: Boolean(env.FISH_AUDIO_API_KEY) }, dependencies: { ffmpeg, ffprobe } }; }

export function slugify(value: string) { return value.normalize("NFKD").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 80) || "untitled-story"; }
export function backupPath(root: string, id: string) { if (!/^[a-f0-9-]{36}$/.test(id)) throw new Error("Invalid backup ID"); return join(root, ".ai-story-studio", "backups", `${id}.zip`); }

function modelSchema() { return z.object({ provider: z.enum(["openai", "gemini"]), model: z.string().min(1) }); }
function globalSettingsPath(root: string) { return join(root, ".ai-story-studio", "settings.json"); }
function activityPath(root: string, slug: string) { return join(storyPaths(root, slug, 1).story, "activity.json"); }
async function uniqueSlug(root: string, requested: string) { const base = safeSlugSchema.parse(slugify(requested)); if (!(await exists(storyPaths(root, base, 1).story))) return base; for (let i = 2; i < 10_000; i++) { const value = `${base}-${i}`; if (!(await exists(storyPaths(root, value, 1).story))) return value; } throw new Error("Unable to allocate a unique story slug"); }
async function walk(directory: string): Promise<string[]> { const out: string[] = []; for (const entry of await readdir(directory, { withFileTypes: true }).catch((error) => { if ((error as NodeJS.ErrnoException).code === "ENOENT") return []; throw error; })) { if (entry.name === ".lock" || entry.name.includes(".tmp")) continue; const path = join(directory, entry.name); if (entry.isDirectory()) out.push(...await walk(path)); else if (entry.isFile()) out.push(path); if (out.length > 10_000) throw new Error("Project contains more than 10,000 files"); } return out; }
function shouldExcludeBackup(path: string, includeMedia: boolean) { if (path === "activity.json" || path.startsWith("backups/") || path.startsWith(".lock")) return true; if (includeMedia || /^cover\.(jpg|jpeg|png)$/.test(path)) return false; return /(^|\/)(audio-segments|scenes|voice-previews|previews|exports)(\/|$)/.test(path) || /\.(mp3|m4b|mp4|png|jpe?g)$/i.test(path); }
function validateArchiveNames(names: string[]) { if (names.length > 10_000) throw new Error("Backup contains too many files"); for (const name of names) { const normalized = name.replaceAll("\\", "/"); const parts = normalized.split("/"); if (!name || name.includes("\0") || normalized.startsWith("/") || /^[A-Za-z]:/.test(normalized) || parts.includes("..") || parts.includes(".lock") || parts.some((part) => part.includes(".tmp")) || resolve("/safe", normalized) === "/safe") throw new Error(`Unsafe backup path: ${name}`); } }
function validateImageSignature(extension: string, bytes: Uint8Array) { const png = bytes[0] === 0x89 && bytes[1] === 0x50 && bytes[2] === 0x4e && bytes[3] === 0x47; const jpeg = bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff; if (extension === ".png" ? !png : !jpeg) throw new Error("Cover contents do not match its file extension"); }
async function invalidateChapterVideo(root: string, slug: string) { const chapters = join(storyPaths(root, slug, 1).story, "chapters"); for (const entry of await readdir(chapters, { withFileTypes: true }).catch(() => [])) if (entry.isDirectory() && /^\d+$/.test(entry.name)) await markPending(storyPaths(root, slug, Number(entry.name)).chapterMeta, ["video"]); }
async function markPending(path: string, stages: string[]) { const raw = await readJsonIfExists<Chapter>(path); if (!raw) return; const chapter = chapterSchema.parse(raw); for (const stage of stages) if (stage in chapter.stages) chapter.stages[stage as keyof typeof chapter.stages] = { status: "pending" }; chapter.updatedAt = new Date().toISOString(); await atomicWriteJson(path, chapter); }
function storageCategory(path: string) { if (path.startsWith("source/")) return "source"; if (path.startsWith("previews/") || path.startsWith("voice-previews/")) return "previews"; if (path.startsWith("exports/")) return "exports"; if (path.includes("/audio-segments/") || path.endsWith("/audio-raw.mp3")) return "ttsRaw"; if (path.endsWith("/audio.mp3")) return "masteredAudio"; if (/\/scenes\/.*\.png$/.test(path)) return "artwork"; if (path.endsWith(".mp4")) return "video"; if (/\.(txt|json|srt|vtt)$/.test(path)) return "text"; return "other"; }
async function pathSize(path: string): Promise<number> { const info = await stat(path); if (info.isFile()) return info.size; let total = 0; for (const entry of await readdir(path)) total += await pathSize(join(path, entry)); return total; }
