import { readFile } from "node:fs/promises";
import { Chapter, chapterSchema } from "../domain/chapter.js";
import { Story } from "../domain/story.js";
import { ArtworkError } from "../pipeline/errors.js";
import { atomicWrite, atomicWriteJson } from "../storage/atomic-write.js";
import { sceneImagePath, storyPaths } from "../storage/paths.js";
import { exists, readJsonIfExists } from "../storage/story-files.js";
import { fingerprint } from "../utils/hash.js";
import { sceneContentFingerprint } from "../scenes/manifest.js";
import { loadCharacterVisualReferences } from "../scenes/visual-references.js";
import { artworkReviewSchema, Scene, SceneManifest, sceneManifestSchema } from "../scenes/types.js";
import { ImageProvider } from "./provider.js";

export async function generateStoredArtwork(options: { root: string; story: Story; chapter: number; provider: ImageProvider; sceneId?: string; force?: boolean; dryRun?: boolean; onProgress?: (event: { type: string; chapter: number; scene?: string; index?: number; total?: number }) => void }) {
  const paths = storyPaths(options.root, options.story.slug, options.chapter); const raw = await readJsonIfExists<SceneManifest>(paths.scenesManifest); if (!raw) throw new ArtworkError(`Chapter ${options.chapter} has no scene plan`); const manifest = sceneManifestSchema.parse(raw);
  const rawChapter = await readJsonIfExists<Chapter>(paths.chapterMeta); if (!rawChapter) throw new ArtworkError(`Chapter ${options.chapter} has no pipeline metadata`); const chapter = chapterSchema.parse(rawChapter);
  let selected = options.sceneId ? manifest.scenes.filter((scene) => scene.id === options.sceneId) : manifest.scenes; if (options.sceneId && !selected.length) throw new ArtworkError(`Scene '${options.sceneId}' was not found`);
  const candidates: Array<{ scene: Scene; prompt: string; refs: Awaited<ReturnType<typeof loadCharacterVisualReferences>>; inputFingerprint: string }> = [];
  for (const scene of selected) { const refs = await loadCharacterVisualReferences(options.root, options.story.slug, scene.characters); const prompt = artworkPrompt(scene, refs, options.story.artwork.stylePrompt); const inputFingerprint = artworkFingerprint(scene, refs.map((ref) => ref.fingerprint), options.story, options.provider.version); const validFile = await exists(sceneImagePath(options.root, options.story.slug, options.chapter, scene.id)); const needs = options.force || scene.artwork.status !== "complete" || !validFile || scene.artwork.fingerprint !== inputFingerprint || scene.artwork.review === "needs-regeneration"; if (needs) candidates.push({ scene, prompt, refs, inputFingerprint }); }
  if (options.dryRun) return { dryRun: true, chapter: options.chapter, planned: manifest.scenes.length, selected: selected.length, imagesToGenerate: candidates.length, sceneIds: candidates.map((item) => item.scene.id) };
  await options.provider.validateConfiguration(); const started = Date.now(); chapter.stages.artwork = { status: "running", provider: options.story.artwork.provider, model: options.story.artwork.model, fingerprint: fingerprint({ manifest: manifest.planningFingerprint, manualRevision: manifest.manualRevision, settings: options.story.artwork }), startedAt: new Date().toISOString() }; await persistChapter(paths.chapterMeta, chapter);
  let generated = 0; let reused = selected.length - candidates.length;
  for (let index = 0; index < candidates.length; index++) { const item = candidates[index]!; item.scene.artwork = { ...item.scene.artwork, status: "running", provider: options.provider.name, model: options.story.artwork.model, fingerprint: item.inputFingerprint, error: undefined }; manifest.updatedAt = new Date().toISOString(); await atomicWriteJson(paths.scenesManifest, manifest); options.onProgress?.({ type: "artwork.scene.started", chapter: options.chapter, scene: item.scene.id, index: index + 1, total: candidates.length });
    try { const result = await options.provider.generate({ model: options.story.artwork.model, prompt: item.prompt, quality: options.story.artwork.quality, size: options.story.artwork.size, outputFormat: options.story.artwork.outputFormat }); validatePng(result.data); const imagePath = sceneImagePath(options.root, options.story.slug, options.chapter, item.scene.id); await atomicWrite(imagePath, result.data); item.scene.artwork = { status: "complete", review: "unreviewed", provider: options.provider.name, model: options.story.artwork.model, fingerprint: item.inputFingerprint, imageFingerprint: fingerprint(result.data.toString("base64")), generatedAt: new Date().toISOString() }; generated++; options.onProgress?.({ type: "artwork.scene.completed", chapter: options.chapter, scene: item.scene.id, index: index + 1, total: candidates.length }); }
    catch (error) { item.scene.artwork = { ...item.scene.artwork, status: "failed", review: "needs-regeneration", error: error instanceof Error ? error.message : String(error) }; await atomicWriteJson(paths.scenesManifest, manifest); chapter.stages.artwork = { ...chapter.stages.artwork, status: "failed", durationMs: Date.now() - started, error: { message: `${item.scene.id}: ${item.scene.artwork.error}` } }; await persistChapter(paths.chapterMeta, chapter); throw new ArtworkError(`Artwork generation failed for ${item.scene.id}: ${item.scene.artwork.error}`, { cause: error }); }
    await atomicWriteJson(paths.scenesManifest, manifest);
  }
  const outputFingerprint = fingerprint(manifest.scenes.map((scene) => ({ id: scene.id, fingerprint: scene.artwork.fingerprint, imageFingerprint: scene.artwork.imageFingerprint, review: scene.artwork.review }))); const allGenerated = manifest.scenes.every((scene) => scene.artwork.status === "complete"); chapter.stages.artwork = { ...chapter.stages.artwork, status: allGenerated ? "complete" : "pending", outputFingerprint, completedAt: new Date().toISOString(), durationMs: Date.now() - started, usage: { requests: generated } }; chapter.scenes = { total: manifest.scenes.length, generated: manifest.scenes.filter((scene) => scene.artwork.status === "complete").length, approved: manifest.scenes.filter((scene) => scene.artwork.review === "approved").length }; if (generated) { chapter.stages.video = { status: "pending" }; chapter.video = undefined; } await persistChapter(paths.chapterMeta, chapter); return { dryRun: false, chapter: options.chapter, planned: manifest.scenes.length, selected: selected.length, imagesToGenerate: candidates.length, generated, reused };
}

export async function reviewStoredArtwork(options: { root: string; story: Story; chapter: number; sceneId: string; review: unknown }) { const review = artworkReviewSchema.parse(options.review); const paths = storyPaths(options.root, options.story.slug, options.chapter); const raw = await readJsonIfExists<SceneManifest>(paths.scenesManifest); if (!raw) throw new ArtworkError(`Chapter ${options.chapter} has no scene plan`); const manifest = sceneManifestSchema.parse(raw); const scene = manifest.scenes.find((item) => item.id === options.sceneId); if (!scene) throw new ArtworkError(`Scene '${options.sceneId}' was not found`); if (review === "approved" && (scene.artwork.status !== "complete" || !(await exists(sceneImagePath(options.root, options.story.slug, options.chapter, scene.id))))) throw new ArtworkError("Only successfully generated artwork can be approved"); scene.artwork.review = review; manifest.updatedAt = new Date().toISOString(); await atomicWriteJson(paths.scenesManifest, manifest); const chapterRaw = await readJsonIfExists<Chapter>(paths.chapterMeta); if (chapterRaw) { const chapter = chapterSchema.parse(chapterRaw); chapter.scenes = { total: manifest.scenes.length, generated: manifest.scenes.filter((item) => item.artwork.status === "complete").length, approved: manifest.scenes.filter((item) => item.artwork.review === "approved").length }; chapter.stages.video = { status: "pending" }; chapter.video = undefined; await persistChapter(paths.chapterMeta, chapter); } return manifest; }

export function artworkFingerprint(scene: Scene, visualReferenceFingerprints: string[], story: Story, providerVersion: string) { return fingerprint({ scene: sceneContentFingerprint(scene), visualReferenceFingerprints, style: story.artwork.stylePrompt, aspectRatio: story.artwork.aspectRatio, quality: story.artwork.quality, size: story.artwork.size, outputFormat: story.artwork.outputFormat, provider: story.artwork.provider, model: story.artwork.model, providerVersion }); }
function artworkPrompt(scene: Scene, refs: Array<{ name: string; description: string }>, style: string) { return [`STORY-WIDE ART DIRECTION: ${style}`, `SCENE: ${scene.visualPrompt}`, `SUMMARY: ${scene.summary}`, scene.location ? `LOCATION: ${scene.location}` : "", scene.characters.length ? `CHARACTERS: ${scene.characters.join(", ")}` : "", ...refs.map((ref) => `CANONICAL VISUAL REFERENCE — ${ref.name}: ${ref.description}`), "Create one polished still illustration. 16:9-safe composition. No text, captions, speech bubbles, logos, or watermarks."].filter(Boolean).join("\n"); }
function validatePng(data: Buffer) { if (data.length < 8 || !data.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]))) throw new ArtworkError("Image provider returned invalid PNG data"); }
async function persistChapter(path: string, chapter: Chapter) { chapter.updatedAt = new Date().toISOString(); await atomicWriteJson(path, chapterSchema.parse(chapter)); }
