import { mkdtemp, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { alignStoredChapter } from "../src/alignment/chapter-alignment.js";
import { reconcileAndValidateAlignment, tokenizeNarration } from "../src/alignment/quality.js";
import { AlignmentConfig, AlignmentEngine, AlignmentObservation, alignmentArtifactSchema } from "../src/alignment/types.js";
import { parseWhisperJson } from "../src/alignment/whisper-cpp.js";
import { chapterSchema } from "../src/domain/chapter.js";
import { buildProductionPlan } from "../src/production/planner.js";
import { atomicWrite, atomicWriteJson } from "../src/storage/atomic-write.js";
import { storyPaths } from "../src/storage/paths.js";
import { generateAlignedSubtitleTiming } from "../src/subtitles/aligned-timing.js";
import { discardManualSubtitles, generateStoredSubtitles, saveManualSubtitles, validateCueOrder } from "../src/subtitles/chapter-subtitles.js";
import { testStory } from "./helpers.js";

const config: AlignmentConfig = { engine: "whisper-cpp", executable: "whisper-cli", model: "/model.bin", device: "cpu", minimumMatchPercentage: 80, minimumConfidence: .4, maximumGapSeconds: 5, timeoutMs: 10_000 };
class FakeAlignment implements AlignmentEngine { readonly name = "fake-align"; readonly version = "fake-v1"; calls = 0; constructor(private readonly confidence = .95) {} async validateConfiguration() {} async align(request: { narration: string }) { this.calls++; const tokens = tokenizeNarration(request.narration); return tokens.map((text, index) => ({ text, start: .1 + index * .7, end: .65 + index * .7, confidence: this.confidence })); } }

async function fixture() { const root = await mkdtemp(join(tmpdir(), "alignment-")); const story = testStory(); const paths = storyPaths(root, story.slug, 1); const complete = { status: "complete" as const, fingerprint: "input", outputFingerprint: "output" }; const now = new Date().toISOString(); const narration = "Maya stepped onto the empty platform. A silver train waited."; await atomicWriteJson(paths.chapterMeta, chapterSchema.parse({ chapter: 1, sourceLanguage: story.sourceLanguage, outputLanguage: story.outputLanguage, counts: { originalCharacters: 10, englishWords: 10, narrationWords: 10 }, createdAt: now, updatedAt: now, stages: { ingestion: complete, translation: complete, narration: complete, qa: complete, storyBible: complete, tts: complete, audioMastering: complete }, audio: { durationSeconds: 8, codec: "mp3", container: "mp3" } })); await atomicWrite(paths.narration, narration); await atomicWrite(paths.audio, Buffer.from("mastered chapter audio")); return { root, story, paths, narration }; }

describe("forced alignment", () => {
  it("validates durable artifacts and reuses unchanged narration/audio", async () => { const { root, story, paths } = await fixture(); const engine = new FakeAlignment(); const first = await alignStoredChapter({ root, storySlug: story.slug, chapter: 1, language: story.outputLanguage, config, engine }); const second = await alignStoredChapter({ root, storySlug: story.slug, chapter: 1, language: story.outputLanguage, config, engine }); expect(first.artifact.mode).toBe("aligned"); expect(second.reused).toBe(true); expect(engine.calls).toBe(1); expect(alignmentArtifactSchema.parse(JSON.parse(await readFile(paths.alignment, "utf8"))).metrics.matchedWordPercentage).toBe(100); });
  it("lets restart planning recognize and reuse a valid alignment artifact", async () => { const { root, story } = await fixture(); await alignStoredChapter({ root, storySlug: story.slug, chapter: 1, language: story.outputLanguage, config, engine: new FakeAlignment() }); const plan = await buildProductionPlan({ root, story, chapters: [1], outputs: ["video"], artwork: false, alignment: true }); expect(plan.counts.alignment).toEqual({ required: 0, reusable: 1 }); expect(plan.chapterRequirements["1"]).not.toContain("alignment"); });
  it("invalidates cache when narration or mastered audio changes", async () => { const { root, story, paths } = await fixture(); const engine = new FakeAlignment(); await alignStoredChapter({ root, storySlug: story.slug, chapter: 1, language: story.outputLanguage, config, engine }); await atomicWrite(paths.narration, "Maya carefully stepped onto the empty platform. A silver train waited."); await alignStoredChapter({ root, storySlug: story.slug, chapter: 1, language: story.outputLanguage, config, engine }); await atomicWrite(paths.audio, Buffer.from("different mastered audio")); await alignStoredChapter({ root, storySlug: story.slug, chapter: 1, language: story.outputLanguage, config, engine }); expect(engine.calls).toBe(3); });
  it("falls back for low confidence or a missing engine", async () => { const low = await fixture(); const lowResult = await alignStoredChapter({ root: low.root, storySlug: low.story.slug, chapter: 1, language: "en", config, engine: new FakeAlignment(.1) }); expect(lowResult.artifact).toMatchObject({ mode: "estimated" }); expect(lowResult.artifact.warning).toMatch(/confidence/i); const missing = await fixture(); const missingResult = await alignStoredChapter({ root: missing.root, storySlug: missing.story.slug, chapter: 1, language: "en", config, engine: undefined }); expect(missingResult.artifact).toMatchObject({ mode: "estimated", engine: "whisper-cpp" }); });
  it("rejects non-monotonic/audio-bound observations", () => { const quality = reconcileAndValidateAlignment("one two", [{ text: "one", start: 3, end: 4, confidence: .9 }, { text: "two", start: 2, end: 12, confidence: .9 }], 8, config); expect(quality.usable).toBe(false); expect(quality.warnings.join(" ")).toMatch(/timestamps/i); });
  it("parses whisper.cpp full JSON token timestamps", () => { const words = parseWhisperJson({ transcription: [{ text: " Hello world", offsets: { from: 0, to: 2000 }, tokens: [{ text: "Hello", offsets: { from: 100, to: 700 }, p: .9 }, { text: "world", offsets: { from: 800, to: 1500 }, p: .8 }] }] }); expect(words).toEqual([{ text: "Hello", start: .1, end: .7, confidence: .9 }, { text: "world", start: .8, end: 1.5, confidence: .8 }]); });
});

describe("aligned subtitles and protected edits", () => {
  it("segments long aligned sentences into ordered readable cues", () => { const text = "This deliberately long sentence contains enough words to become several readable subtitle cues without showing every individual word independently."; const tokens = tokenizeNarration(text); const words = tokens.map((word, index) => ({ text: word, start: index * .45, end: index * .45 + .4, confidence: .9, matched: true })); const document = generateAlignedSubtitleTiming(words, words.at(-1)!.end, testStory().subtitles); expect(document.cues.length).toBeGreaterThan(1); expect(document.cues.every((cue) => cue.text.replace("\n", " ").length <= 84)).toBe(true); for (let index = 1; index < document.cues.length; index++) expect(document.cues[index]!.startSeconds).toBeGreaterThanOrEqual(document.cues[index - 1]!.endSeconds); });
  it("validates bounds and protects manual edits until explicit reset", async () => { const { root, story, paths } = await fixture(); await alignStoredChapter({ root, storySlug: story.slug, chapter: 1, language: "en", config, engine: new FakeAlignment() }); const generated = await generateStoredSubtitles({ root, story, chapter: 1 }); const cues = generated.document.cues.map((cue, index) => ({ ...cue, text: index ? cue.text : "A deliberate correction." })); await saveManualSubtitles(root, story.slug, 1, cues); const protectedResult = await generateStoredSubtitles({ root, story, chapter: 1, force: true }); expect(protectedResult.protected).toBe(true); expect(protectedResult.document.cues[0]!.text).toBe("A deliberate correction."); await discardManualSubtitles(root, story.slug, 1); const reset = await generateStoredSubtitles({ root, story, chapter: 1, force: true }); expect(reset.document.manual).toBe(false); expect(await readFile(paths.subtitlesSrt, "utf8")).not.toContain("A deliberate correction."); expect(() => validateCueOrder([{ index: 1, startSeconds: 0, endSeconds: 9, text: "Too long" }], 8)).toThrow(/beyond/); });
});
