import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { AudiobookProcessor } from "../src/audio/audiobook.js";
import { chapterSchema } from "../src/domain/chapter.js";
import { qaResultSchema } from "../src/domain/qa.js";
import { QualityGateError } from "../src/pipeline/errors.js";
import { PipelineOptions } from "../src/pipeline/chapter-pipeline.js";
import { buildProductionPlan, isProductionStageForced, requiredProductionStages, resolveProductionOptions } from "../src/production/planner.js";
import { planProduction, ProductionDependencies, runProduction } from "../src/production/orchestrator.js";
import { productionManifestSchema } from "../src/production/types.js";
import { atomicWrite, atomicWriteJson } from "../src/storage/atomic-write.js";
import { storyPaths } from "../src/storage/paths.js";
import { readJsonIfExists } from "../src/storage/story-files.js";
import { fingerprint } from "../src/utils/hash.js";
import { VideoProcessor } from "../src/video/renderer.js";
import { VideoExportProcessor } from "../src/video/video-export.js";
import { testStory } from "./helpers.js";

class ProductionPipeline {
  calls: Array<{ chapter: number; force?: string }> = []; fail = new Set<number>(); pauseAfter?: { requested: boolean };
  async run(options: PipelineOptions) { this.calls.push({ chapter: options.chapter, force: options.force }); if (this.fail.has(options.chapter)) throw new Error(`Chapter ${options.chapter} exploded`); const chapter = await writeCompleteChapter(options.root, options.chapter); for (const stage of ["ingestion", "translation", "narration", "qa", "storyBible", "continuity", "tts", "audioMastering"] as const) options.onStageEvent?.({ stage, status: "completed", state: chapter.stages[stage] }); if (this.pauseAfter && options.chapter === 1) this.pauseAfter.requested = true; return chapter; }
}
const video: VideoProcessor = { version: "production-video", render: async (_input, output, settings) => { await atomicWrite(output, Buffer.from("video")); return { durationSeconds: 10, videoCodec: "h264", audioCodec: "aac", width: settings.width, height: settings.height, container: "mp4" }; } };
const videoExport: VideoExportProcessor = { version: "production-video-export", assemble: async (chapters, output) => { await atomicWrite(output, Buffer.from("video-export")); return { durationSeconds: chapters.reduce((sum, item) => sum + item.durationSeconds, 0), videoCodec: "h264", audioCodec: "aac", width: 1920, height: 1080, container: "mp4" }; } };
const audiobook: AudiobookProcessor = { version: "production-book", assemble: async (chapters, output, format) => { await atomicWrite(output, Buffer.from("book")); return { durationSeconds: chapters.reduce((sum, item) => sum + item.durationSeconds, 0) + Math.max(0, chapters.length - 1) * 1.5, codec: format === "m4b" ? "aac" : "mp3", container: format === "m4b" ? "mp4" : "mp3" }; } };

async function fixture(count = 2) { const root = await mkdtemp(join(tmpdir(), "production-")); const story = testStory(); const chapters = []; for (let chapter = 1; chapter <= count; chapter++) { const path = join(root, `source-${chapter}.txt`); await atomicWrite(path, `Chapter ${chapter}`); chapters.push({ chapter, path, filename: `source-${chapter}.txt` }); } return { root, story, chapters }; }
function dependencies(pipeline: ProductionPipeline, chapters: Awaited<ReturnType<typeof fixture>>["chapters"]): ProductionDependencies { return { pipeline, loadChapters: async () => chapters, video, videoExport, audiobook }; }

describe("production planning", () => {
  it("selects only audiobook dependencies and adds video/artwork dependencies when requested", () => { expect(requiredProductionStages(["audiobook"], false)).toEqual(["ingestion", "translation", "narration", "qa", "storyBible", "continuity", "tts", "audioMastering", "audiobook"]); expect(requiredProductionStages(["video"], true)).toEqual(expect.arrayContaining(["subtitles", "scenePlanning", "artwork", "video", "videoExport"])); });
  it("resolves reusable profiles and explicit overrides", () => { const story = testStory(); expect(resolveProductionOptions(story, { profile: "story-video" })).toMatchObject({ outputs: ["video"], artwork: true, repairQa: true }); expect(resolveProductionOptions(story, { profile: "story-video", artwork: false })).toMatchObject({ artwork: false }); });
  it("forces dependency descendants without treating sibling exports as dependents", () => { expect(isProductionStageForced("audio", "audiobook")).toBe(true); expect(isProductionStageForced("video", "videoExport")).toBe(true); expect(isProductionStageForced("video", "audiobook")).toBe(false); expect(isProductionStageForced("audiobook", "videoExport")).toBe(false); expect(isProductionStageForced("continuity", "continuity")).toBe(true); expect(isProductionStageForced("continuity", "tts")).toBe(false); });
  it("reports actual reusable stage files without provider calls", async () => { const { root, story } = await fixture(1); await writeCompleteChapter(root, 1); const first = await buildProductionPlan({ root, story, chapters: [1], outputs: ["audio"], artwork: false }); expect(first.counts.audioMastering).toEqual({ required: 0, reusable: 1 }); await atomicWrite(storyPaths(root, story.slug, 1).audio, Buffer.alloc(0)); const changed = await buildProductionPlan({ root, story, chapters: [1], outputs: ["audio"], artwork: false }); expect(changed.counts.audioMastering.required).toBe(1); });
  it("keeps dry-run free of pipeline and refresh calls", async () => { const { root, story, chapters } = await fixture(1); let refreshes = 0; const pipeline = new ProductionPipeline(); const result = await runProduction({ root, story, from: 1, to: 1, outputs: ["audio"], dryRun: true, refresh: true }, { ...dependencies(pipeline, chapters), refresh: async () => { refreshes++; } }); expect(result.manifest.status).toBe("planned"); expect(pipeline.calls).toHaveLength(0); expect(refreshes).toBe(0); });
});

describe("production execution", () => {
  it("builds an audiobook, persists its manifest, and records stage work", async () => { const { root, story, chapters } = await fixture(2); const pipeline = new ProductionPipeline(); const result = await runProduction({ root, story, from: 1, to: 2, outputs: ["audiobook"] }, dependencies(pipeline, chapters)); expect(result.manifest.status).toBe("completed"); expect(result.manifest.summary.exports.audiobook).toMatch(/\.m4b$/); expect(result.manifest.summary.newStages).toBe(16); const stored = await readJsonIfExists(join(root, "stories", story.slug, "production-runs", `${result.manifest.id}.json`)); expect(productionManifestSchema.parse(stored).summary.completed).toBe(2); });
  it("builds subtitles, chapter video, and a combined video for video output", async () => { const { root, story, chapters } = await fixture(1); const result = await runProduction({ root, story, from: 1, to: 1, outputs: ["video"], artwork: false }, dependencies(new ProductionPipeline(), chapters)); expect(result.manifest.status).toBe("completed"); expect(result.manifest.summary.exports.video).toMatch(/\.mp4$/); expect(result.manifest.chapters["1"]?.operations).toMatchObject({ subtitles: { status: "complete" }, video: { status: "complete" } }); });
  it("resumes after a safe pause without rerunning completed chapters", async () => { const { root, story, chapters } = await fixture(2); const pause = { requested: false, get isRequested() { return this.requested; } }; const firstPipeline = new ProductionPipeline(); firstPipeline.pauseAfter = pause; const first = await runProduction({ root, story, from: 1, to: 2, outputs: ["audio"], pause }, dependencies(firstPipeline, chapters)); expect(first.manifest.status).toBe("paused"); const secondPipeline = new ProductionPipeline(); const second = await runProduction({ root, story, from: 1, to: 2, outputs: ["audio"] }, dependencies(secondPipeline, chapters)); expect(second.manifest.id).toBe(first.manifest.id); expect(secondPipeline.calls.map((item) => item.chapter)).toEqual([2]); expect(second.manifest.status).toBe("completed"); });
  it("continues past an isolated chapter failure", async () => { const { root, story, chapters } = await fixture(2); const pipeline = new ProductionPipeline(); pipeline.fail.add(1); const result = await runProduction({ root, story, from: 1, to: 2, outputs: ["audio"] }, dependencies(pipeline, chapters)); expect(result.manifest.status).toBe("completed_with_errors"); expect(result.manifest.summary).toMatchObject({ completed: 1, failed: 1 }); });
  it("retries transient chapter failures while reusing completed stage work", async () => { const { root, story, chapters } = await fixture(1); const pipeline = new ProductionPipeline(); const base = pipeline.run.bind(pipeline); let attempts = 0; pipeline.run = async (options) => { if (++attempts === 1) throw Object.assign(new Error("service unavailable"), { status: 503, headers: { "retry-after": "0" } }); return base(options); }; const result = await runProduction({ root, story, from: 1, to: 1, outputs: ["audio"] }, dependencies(pipeline, chapters)); expect(result.manifest.status).toBe("completed"); expect(attempts).toBe(2); });
  it("uses bounded QA repair before completing a chapter", async () => { const { root, story, chapters } = await fixture(1); const pipeline = new ProductionPipeline(); const base = pipeline.run.bind(pipeline); let attempts = 0; pipeline.run = async (options) => { if (++attempts === 1) throw new QualityGateError("QA failed", failedQa()); return base(options); }; const result = await runProduction({ root, story, from: 1, to: 1, outputs: ["audio"], repairQa: true }, dependencies(pipeline, chapters)); expect(result.manifest.status).toBe("completed"); expect(pipeline.calls[0]?.force).toBe("translation"); expect(attempts).toBe(2); });
  it("stops QA repair after the configured bound", async () => { const { root, story, chapters } = await fixture(1); let attempts = 0; const pipeline = new ProductionPipeline(); pipeline.run = async () => { attempts++; throw new QualityGateError("QA still failing", failedQa()); }; const result = await runProduction({ root, story, from: 1, to: 1, outputs: ["audio"], repairQa: true }, dependencies(pipeline, chapters)); expect(attempts).toBe(3); expect(result.manifest).toMatchObject({ status: "completed_with_errors", summary: { needsReview: 1, qaFailures: 1 } }); });
  it("routes requested remote refresh before loading chapters", async () => { const { root, story, chapters } = await fixture(1); let refreshes = 0; const pipeline = new ProductionPipeline(); await runProduction({ root, story, from: 1, to: 1, outputs: ["audio"], refresh: true }, { ...dependencies(pipeline, chapters), refresh: async (from, to) => { expect([from, to]).toEqual([1, 1]); refreshes++; } }); expect(refreshes).toBe(1); });
});

async function writeCompleteChapter(root: string, chapter: number) { const story = testStory(); const paths = storyPaths(root, story.slug, chapter); const now = new Date().toISOString(); const complete = { status: "complete" as const, fingerprint: "input", outputFingerprint: "output" }; const audio = Buffer.from(`audio-${chapter}`); const continuity = Buffer.from(JSON.stringify({ version: 1, chapter, findingIds: [], openFindings: 0 })); const value = chapterSchema.parse({ chapter, sourceLanguage: story.sourceLanguage, outputLanguage: story.outputLanguage, counts: { originalCharacters: 10, englishWords: 2, narrationWords: 2 }, createdAt: now, updatedAt: now, stages: { ingestion: complete, translation: complete, narration: complete, qa: complete, storyBible: complete, continuity: { ...complete, outputFingerprint: fingerprint(continuity.toString("base64")) }, tts: complete, audioMastering: { ...complete, outputFingerprint: fingerprint(audio.toString("base64")) } }, quality: { status: "pass", score: 1, issueCategories: [] }, audio: { durationSeconds: 10, codec: "mp3", container: "mp3" } }); await Promise.all([atomicWriteJson(paths.chapterMeta, value), atomicWrite(paths.original, "original"), atomicWrite(paths.english, "english"), atomicWrite(paths.narration, "narration"), atomicWriteJson(paths.qa, passedQa()), atomicWriteJson(paths.bibleUpdate, { chapterSummary: "Summary", characters: [], relationships: [], terminology: [], locations: [], factions: [], abilities: [], unresolvedThreads: [] }), atomicWrite(paths.continuityAnalysis, continuity), atomicWrite(paths.audioRaw, audio), atomicWrite(paths.audio, audio)]); return value; }
function passedQa() { return qaResultSchema.parse({ status: "pass", score: 1, issues: [], checks: { completeness: "pass", names: "pass", numbers: "pass", terminology: "pass", dialogue: "pass", storyConsistency: "pass", narrationFidelity: "pass" } }); }
function failedQa() { return qaResultSchema.parse({ status: "fail", score: .2, issues: [{ category: "completeness", severity: "fail", message: "Missing passage", evidence: "Ending absent" }], checks: { completeness: "fail", names: "pass", numbers: "pass", terminology: "pass", dialogue: "pass", storyConsistency: "pass", narrationFidelity: "pass" } }); }
