import { readFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { createDatabasePool } from "../src/queue/database.js";
import { PostgresQueueRepository } from "../src/queue/repository.js";

const url=process.env.TEST_DATABASE_URL;const suite=url?describe:describe.skip;
suite("Postgres durable queue integration",()=>{const pool=createDatabasePool(url??"postgresql://unused",{max:4});let repository:PostgresQueueRepository;
  beforeAll(async()=>{await pool.query(await readFile("migrations/001_durable_production_queue.sql","utf8"));await pool.query("TRUNCATE production_events,production_work_items,production_jobs,provider_cooldowns CASCADE");repository=new PostgresQueueRepository(pool);});afterAll(()=>pool.end());
  it("creates 1,600 paginated items and atomically claims only the first chronological chapter",async()=>{const job=await repository.createJob({story:`large-${randomUUID().slice(0,8)}`,input:{from:1,to:1600,profile:"audio",refresh:false},plan:{chapters:1600},chapters:Array.from({length:1600},(_,index)=>({chapter:index+1,providers:["openai"]})),maxAttempts:5});expect((await repository.listWorkItems(job.id,{page:32,pageSize:50}))).toMatchObject({total:1600,pages:32,items:[{chapter:1551}]});const [a,b]=await Promise.all([repository.claimNext("worker-a",60_000),repository.claimNext("worker-b",60_000)]);expect([a,b].filter(Boolean)).toHaveLength(1);expect((a??b)?.chapter).toBe(1);expect(await repository.claimNext("worker-c",60_000)).toBeUndefined();});
  it("persists retry counters and recovers expired leases",async()=>{const story=`retry-${randomUUID().slice(0,8)}`;const job=await repository.createJob({story,input:{from:1,to:1,outputs:["audio"],refresh:false},plan:{},chapters:[{chapter:1,providers:["openai"]}],maxAttempts:3});const item=await repository.claimNext("crashed",30_000,new Date(0));expect(item?.attemptCount).toBe(1);const restarted=new PostgresQueueRepository(pool);expect(await restarted.recoverExpired(new Date(60_000))).toBe(1);const reclaimed=await restarted.claimNext("restarted",30_000,new Date(60_001));expect(reclaimed?.attemptCount).toBe(2);await restarted.failItem(reclaimed!,{category:"rate_limit",retryable:true,retryAfterMs:1000,message:"OpenAI rate limit",recommendedAction:"wait",provider:"openai"},new Date(60_001));const stored=(await restarted.listWorkItems(job.id,{page:1,pageSize:10})).items[0]!;expect(stored).toMatchObject({status:"retry_wait",attemptCount:2,errorCategory:"rate_limit"});expect(stored.nextRetryAt).toBeTruthy();});
  it("persists pause, resume, cancel, and Needs Review",async()=>{const story=`control-${randomUUID().slice(0,8)}`;const job=await repository.createJob({story,input:{from:1,to:2,outputs:["audio"],refresh:false},plan:{},chapters:[{chapter:1},{chapter:2}],maxAttempts:1});expect((await repository.requestPause(job.id)).pauseRequested).toBe(true);expect((await repository.resume(job.id)).status).toBe("queued");const item=await repository.claimNext("worker",60_000);await repository.failItem(item!,{category:"content_qa",retryable:false,message:"QA failed",recommendedAction:"review"});expect((await repository.listNeedsReview({page:1,pageSize:10})).items.some(value=>value.jobId===job.id)).toBe(true);await repository.retryItem(item!.id,"qa");expect((await repository.listWorkItems(job.id,{page:1,pageSize:10})).items[0]).toMatchObject({status:"pending",currentStage:"qa"});expect((await repository.requestCancel(job.id)).cancelRequested).toBe(true);await repository.claimNext("sweeper",60_000);expect((await repository.getJob(job.id))?.status).toBe("cancelled");});
});
