import { describe, expect, it } from "vitest";
import { PostgresQueueRepository } from "../src/queue/repository.js";
import { QueueJob, QueueWorkItem } from "../src/queue/types.js";
import { ProductionWorker } from "../src/queue/worker.js";
import { ClassifiedFailure } from "../src/queue/failure.js";

describe("large durable worker simulation",()=>{
  it("keeps 1,600 chapters sequential, prevents duplicate claims, retries transient work, and isolates permanent failures",async()=>{const store=new MemoryQueue(1600);const calls:number[]=[];const attempts=new Map<number,number>();const executor={execute:async(item:QueueWorkItem)=>{calls.push(item.chapter);const count=(attempts.get(item.chapter)??0)+1;attempts.set(item.chapter,count);if(item.chapter===437&&count===1)throw Object.assign(new Error("provider unavailable"),{status:503});if(item.chapter===1600)throw new Error("Corrupt source chapter");return{reused:item.chapter<100,qaStatus:([700,900].includes(item.chapter)?"warn":"pass") as "warn"|"pass"};},finalize:async()=>({})};const a=new ProductionWorker(store as unknown as PostgresQueueRepository,executor,{workerId:"a",pollMs:1000,leaseMs:60_000,providerSpacingMs:0});const b=new ProductionWorker(store as unknown as PostgresQueueRepository,executor,{workerId:"b",pollMs:1000,leaseMs:60_000,providerSpacingMs:0});await Promise.all([a.tick(),b.tick()]);expect(calls).toEqual([1]);for(let index=0;index<1601;index++)await a.tick();expect(calls).toHaveLength(1601);expect(attempts.get(437)).toBe(2);expect(calls.every((chapter,index)=>index===0||chapter>=calls[index-1]!)).toBe(true);expect(store.items[699]?.status).toBe("warning");expect(store.items[899]?.status).toBe("warning");expect(store.items[1599]?.status).toBe("failed");expect(store.items.filter(item=>item.status==="completed")).toHaveLength(1597);});
});

class MemoryQueue{
  readonly job:QueueJob;readonly items:QueueWorkItem[];private claimed=false;
  constructor(count:number){const now=new Date().toISOString();this.job={id:"00000000-0000-0000-0000-000000000001",story:"large-story",from:1,to:count,status:"queued",pauseRequested:false,cancelRequested:false,totalItems:count,completedItems:0,warningItems:0,reviewItems:0,failedItems:0,options:{from:1,to:count,outputs:["audio"],refresh:false},plan:{},createdAt:now,updatedAt:now};this.items=Array.from({length:count},(_,index)=>({id:String(index+1),jobId:this.job.id,story:this.job.story,chapter:index+1,ordinal:index+1,status:"pending",attemptCount:0,maxAttempts:2,reused:false,requiredProviders:[]}));}
  async recoverExpired(){return 0}async pruneEvents(){return 0}async getJob(){return structuredClone(this.job)}async addEvent(){}async heartbeat(){}async heartbeatFinalization(){}async setCooldown(){}
  async claimNext(workerId:string){if(this.claimed)return undefined;const item=this.items.find((candidate,index)=>["pending","retry_wait"].includes(candidate.status)&&this.items.slice(0,index).every(previous=>["completed","warning","skipped"].includes(previous.status)));if(!item)return undefined;this.claimed=true;item.status="running";item.attemptCount++;item.leaseOwner=workerId;this.job.status="running";return structuredClone(item);}
  async completeItem(value:QueueWorkItem,result:{reused:boolean;qaStatus?:string}){const item=this.items[Number(value.id)-1]!;item.status=result.qaStatus==="warn"?"warning":"completed";item.reused=result.reused;this.claimed=false;this.recount();}
  async failItem(value:QueueWorkItem,failure:ClassifiedFailure){const item=this.items[Number(value.id)-1]!;item.lastError=failure.message;item.errorCategory=failure.category;if(failure.retryable&&item.attemptCount<item.maxAttempts)item.status="retry_wait";else item.status=failure.category==="content_qa"||failure.retryable?"needs_review":"failed";this.claimed=false;this.recount();}
  async claimFinalization(){return undefined}
  private recount(){this.job.completedItems=this.items.filter(item=>item.status==="completed").length;this.job.warningItems=this.items.filter(item=>item.status==="warning").length;this.job.reviewItems=this.items.filter(item=>item.status==="needs_review").length;this.job.failedItems=this.items.filter(item=>item.status==="failed").length;}
}
