import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { DatabasePool } from "../src/queue/database.js";
import { PostgresQueueRepository, QueueConflictError, QueueLeaseLostError } from "../src/queue/repository.js";

describe("durable queue SQL",()=>{const database=new PGlite();let repository:PostgresQueueRepository;
  beforeAll(async()=>{await database.exec(await readFile("migrations/001_durable_production_queue.sql","utf8"));const adapter={query:(text:string,values?:unknown[])=>database.query(text,values),connect:async()=>({query:(text:string,values?:unknown[])=>database.query(text,values),release:()=>undefined})};repository=new PostgresQueueRepository(adapter as unknown as DatabasePool);});afterAll(()=>database.close());
  it("applies the migration and executes job creation, pagination, and a chronological claim",async()=>{const job=await repository.createJob({story:"sql-story",input:{from:1,to:3,outputs:["audio"],refresh:false},plan:{requiredChapters:[1,2,3]},chapters:[{chapter:1,providers:["openai"]},{chapter:2,providers:["fish"]},{chapter:3}],maxAttempts:5});expect(job).toMatchObject({story:"sql-story",status:"queued",totalItems:3});expect(await repository.listWorkItems(job.id,{page:2,pageSize:2})).toMatchObject({total:3,pages:2,items:[{chapter:3}]});const claimed=await repository.claimNext("worker-one",60_000);expect(claimed).toMatchObject({chapter:1,status:"running",attemptCount:1,leaseOwner:"worker-one"});expect(await repository.claimNext("worker-two",60_000)).toBeUndefined();});
  it("enforces one active durable job per story",async()=>{await expect(repository.createJob({story:"sql-story",input:{from:4,to:4,outputs:["audio"],refresh:false},plan:{},chapters:[{chapter:4}],maxAttempts:3})).rejects.toBeInstanceOf(QueueConflictError);});
  it("persists recovery and pause/resume/cancel controls",async()=>{expect(await repository.recoverExpired(new Date(Date.now()+120_000))).toBe(1);const recovered=(await repository.listWorkItems((await repository.listJobs({page:1,pageSize:10,story:"sql-story"})).items[0]!.id,{page:1,pageSize:10})).items[0]!;expect(recovered).toMatchObject({status:"pending",attemptCount:1});const job=await repository.createJob({story:"control-story",input:{from:1,to:2,outputs:["audio"],refresh:false},plan:{},chapters:[{chapter:1},{chapter:2}],maxAttempts:3});expect((await repository.requestPause(job.id)).pauseRequested).toBe(true);await repository.claimNext("control-sweep",60_000);expect((await repository.getJob(job.id))?.status).toBe("paused");expect((await repository.resume(job.id)).status).toBe("queued");expect((await repository.requestCancel(job.id)).cancelRequested).toBe(true);await repository.claimNext("cancel-sweep",60_000);expect((await repository.getJob(job.id))?.status).toBe("cancelled");});
  it("fences stale workers after an expired item lease is reclaimed",async()=>{const job=await repository.createJob({story:"fenced-story",input:{from:1,to:1,outputs:["audio"],refresh:false},plan:{},chapters:[{chapter:1}],maxAttempts:3});const stale=await repository.claimNext("worker-a",1_000,new Date(0));expect(stale?.leaseToken).toBeTruthy();expect((await repository.listWorkItems(job.id,{page:1,pageSize:10})).items[0]).not.toHaveProperty("leaseToken");await repository.recoverExpired(new Date(2_000));const current=await repository.claimNext("worker-b",1_000,new Date(2_001));expect(current?.leaseToken).not.toBe(stale?.leaseToken);await expect(repository.completeItem(stale!,{reused:false})).rejects.toBeInstanceOf(QueueLeaseLostError);await repository.completeItem(current!,{reused:false});expect((await repository.listWorkItems(job.id,{page:1,pageSize:10})).items[0]?.status).toBe("completed");});
  it("fences stale finalizers after their lease is reclaimed",async()=>{await repository.createJob({story:"fenced-export",input:{from:1,to:1,outputs:["audio"],refresh:false},plan:{},chapters:[{chapter:1}],maxAttempts:3});const item=await repository.claimNext("chapter-worker",1_000,new Date(0));await repository.completeItem(item!,{reused:false});const stale=await repository.claimFinalization("finalizer-a",1_000,new Date(0));await repository.recoverExpired(new Date(2_000));const current=await repository.claimFinalization("finalizer-b",1_000,new Date(2_001));await expect(repository.completeFinalization(stale!)).rejects.toBeInstanceOf(QueueLeaseLostError);await repository.completeFinalization(current!);expect((await repository.getJob(current!.id))?.status).toBe("completed");});
});
