import { mkdtemp, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { generateStoredArtwork, artworkFingerprint, reviewStoredArtwork } from "../src/artwork/generator.js";
import { ImageProviderRouter } from "../src/artwork/router.js";
import { ImageProvider } from "../src/artwork/provider.js";
import { chapterSchema } from "../src/domain/chapter.js";
import { LLMProvider } from "../src/llm/provider.js";
import { planStoredScenes, scenePlanningFingerprint, updateStoredSceneManifest } from "../src/scenes/manifest.js";
import { normalizeSceneTiming, validateSceneCoverage } from "../src/scenes/timing.js";
import { SceneManifest, sceneManifestSchema } from "../src/scenes/types.js";
import { atomicWrite, atomicWriteJson } from "../src/storage/atomic-write.js";
import { sceneImagePath, storyPaths } from "../src/storage/paths.js";
import { buildVideoArgs, VideoProcessor } from "../src/video/renderer.js";
import { renderStoredChapterVideo } from "../src/video/chapter-video.js";
import { testStory } from "./helpers.js";

class SceneLLM implements LLMProvider { readonly name = "openai" as const; calls: any[] = []; async validateConfiguration() {} async generateText() { return { text: "" }; } async generateStructured<T>(request: any): Promise<any> { this.calls.push(request); return { value: request.schema.parse({ scenes: [{ summary: "Mara enters the observatory.", startSeconds: 0, endSeconds: 12, characters: ["Mara"], location: "Old Observatory", visualPrompt: "Mara beneath the brass telescope", importance: "major" }, { summary: "The star map ignites.", startSeconds: 12, endSeconds: 30, characters: ["Mara"], location: "Old Observatory", visualPrompt: "Blue constellations flare across the chamber", importance: "standard" }] }) as T }; } }
class FakeImages implements ImageProvider { readonly name = "openai"; readonly version = "fake-images-v1"; calls: any[] = []; async validateConfiguration() {} async generate(request: any) { this.calls.push(request); return { data: Buffer.from([137, 80, 78, 71, 13, 10, 26, 10, 1]), mimeType: "image/png" as const }; } }
class CaptureVideo implements VideoProcessor { readonly version = "capture-video"; input: any; async render(input: any, output: string, settings: any) { this.input = input; await atomicWrite(output, Buffer.from("video")); return { durationSeconds: 33, videoCodec: "h264", audioCodec: "aac", width: settings.width, height: settings.height, container: "mp4" }; } }

async function fixture() { const root = await mkdtemp(join(tmpdir(), "story-scenes-")); const story = testStory(); const paths = storyPaths(root, story.slug, 1); const now = new Date().toISOString(); const complete = { status: "complete" as const, fingerprint: "input", outputFingerprint: "output" }; const chapter = chapterSchema.parse({ chapter: 1, originalTitle: "The Observatory", sourceLanguage: story.sourceLanguage, outputLanguage: story.outputLanguage, counts: { originalCharacters: 50, englishWords: 20, narrationWords: 18 }, createdAt: now, updatedAt: now, stages: { ingestion: complete, translation: complete, narration: complete, qa: complete, storyBible: complete, tts: complete, audioMastering: complete, subtitles: { status: "pending" }, scenePlanning: { status: "pending" }, artwork: { status: "pending" }, video: { status: "pending" } }, audio: { durationSeconds: 30, codec: "mp3", container: "mp3" } }); await atomicWriteJson(paths.chapterMeta, chapter); await atomicWrite(paths.narration, "Mara entered the old observatory. Above her, a map of blue stars awakened."); await atomicWrite(paths.audio, Buffer.from("mastered")); return { root, story, paths }; }

describe("scene planning", () => {
  it("normalizes structured scenes into full, non-overlapping chapter coverage", () => { const story = testStory(); const scenes = normalizeSceneTiming([{ summary: "A", startSeconds: 2, endSeconds: 10, characters: [], visualPrompt: "A", importance: "standard", location: undefined }, { summary: "B", startSeconds: 14, endSeconds: 20, characters: [], visualPrompt: "B", importance: "major", location: undefined }], 30, story.scenes); validateSceneCoverage(scenes, 30); expect(scenes[0]!.startSeconds).toBe(0); expect(scenes.at(-1)!.endSeconds).toBe(30); expect(scenes[1]!.startSeconds).toBe(scenes[0]!.endSeconds); });
  it("uses canonical Story Bible context and reuses its planning fingerprint", async () => { const { root, story } = await fixture(); const provider = new SceneLLM(); const first = await planStoredScenes({ root, story, chapter: 1, provider }); const second = await planStoredScenes({ root, story, chapter: 1, provider }); expect(first.reused).toBe(false); expect(second.reused).toBe(true); expect(provider.calls).toHaveLength(1); expect(provider.calls[0].input).toContain("CANONICAL STORY BIBLE"); expect(scenePlanningFingerprint("n", "b", story.scenes, "openai", "one")).not.toBe(scenePlanningFingerprint("n", "b", story.scenes, "openai", "two")); });
  it("keeps manual edits as the image-generation source of truth", async () => { const { root, story } = await fixture(); const result = await planStoredScenes({ root, story, chapter: 1, provider: new SceneLLM() }); const scenes = structuredClone(result.manifest.scenes); scenes[0]!.visualPrompt = "A manually art-directed brass observatory"; const updated = await updateStoredSceneManifest({ root, story, chapter: 1, scenes }); expect(updated.manuallyEdited).toBe(true); expect(updated.manualRevision).toBe(1); expect(updated.scenes[0]!.visualPrompt).toContain("manually art-directed"); expect(updated.scenes[0]!.artwork.status).toBe("pending"); });
});

describe("artwork generation", () => {
  it("supports dry-run estimates, partial regeneration, fingerprints, and review states", async () => { const { root, story, paths } = await fixture(); await planStoredScenes({ root, story, chapter: 1, provider: new SceneLLM() }); const images = new FakeImages(); const estimate = await generateStoredArtwork({ root, story, chapter: 1, provider: images, dryRun: true }); expect(estimate.imagesToGenerate).toBe(2); expect(images.calls).toHaveLength(0); const one = await generateStoredArtwork({ root, story, chapter: 1, provider: images, sceneId: "scene-001" }); expect(one.generated).toBe(1); expect(images.calls).toHaveLength(1); const reused = await generateStoredArtwork({ root, story, chapter: 1, provider: images, sceneId: "scene-001" }); expect(reused.generated).toBe(0); await reviewStoredArtwork({ root, story, chapter: 1, sceneId: "scene-001", review: "approved" }); const manifest = sceneManifestSchema.parse(JSON.parse(await readFile(paths.scenesManifest, "utf8"))); expect(manifest.scenes[0]!.artwork.review).toBe("approved"); expect(artworkFingerprint(manifest.scenes[0]!, [], story, images.version)).toBe(manifest.scenes[0]!.artwork.fingerprint); });
  it("regenerates only edited scenes, remakes art after style changes, and leaves TTS untouched", async () => { const { root, story, paths } = await fixture(); const planner = new SceneLLM(); const planned = await planStoredScenes({ root, story, chapter: 1, provider: planner }); const images = new FakeImages(); await generateStoredArtwork({ root, story, chapter: 1, provider: images }); const beforeChapter = chapterSchema.parse(JSON.parse(await readFile(paths.chapterMeta, "utf8"))); const edited = structuredClone(planned.manifest.scenes); edited[1]!.visualPrompt = "A hand-directed cobalt constellation map"; await updateStoredSceneManifest({ root, story, chapter: 1, scenes: edited }); const partial = await generateStoredArtwork({ root, story, chapter: 1, provider: images }); expect(partial.generated).toBe(1); expect(images.calls).toHaveLength(3); const restyled = { ...story, artwork: { ...story.artwork, stylePrompt: `${story.artwork.stylePrompt}, watercolor texture` } }; const styleRun = await generateStoredArtwork({ root, story: restyled, chapter: 1, provider: images }); expect(styleRun.generated).toBe(2); expect(images.calls).toHaveLength(5); expect(planner.calls).toHaveLength(1); const afterChapter = chapterSchema.parse(JSON.parse(await readFile(paths.chapterMeta, "utf8"))); expect(afterChapter.stages.tts).toEqual(beforeChapter.stages.tts); });
  it("routes providers without coupling scene planning to a vendor", () => { const images = new FakeImages(); expect(new ImageProviderRouter(new Map([["openai", images]])).forName("openai")).toBe(images); expect(() => new ImageProviderRouter(new Map()).forName("missing")).toThrow("not registered"); });
});

describe("scene artwork video selection", () => {
  it("uses a complete approved scene reel and emits ordered FFmpeg image inputs", async () => { const { root, story, paths } = await fixture(); await planStoredScenes({ root, story, chapter: 1, provider: new SceneLLM() }); const images = new FakeImages(); await generateStoredArtwork({ root, story, chapter: 1, provider: images }); const raw = JSON.parse(await readFile(paths.scenesManifest, "utf8")) as SceneManifest; for (const scene of raw.scenes) scene.artwork.review = "approved"; await atomicWriteJson(paths.scenesManifest, raw); const video = new CaptureVideo(); await renderStoredChapterVideo({ root, story: { ...story, video: { ...story.video, subtitleMode: "none" } }, chapter: 1, processor: video }); expect(video.input.sceneArtwork).toHaveLength(2); const command = buildVideoArgs({ ...video.input, audioDurationSeconds: 30 }, "out.mp4", { ...story.video, subtitleMode: "none" }).join(" "); expect(command).toContain(sceneImagePath(root, story.slug, 1, "scene-001")); expect(command).toContain("concat=n=2:v=1:a=0"); });
  it("falls back when any scene image is not approved", async () => { const { root, story } = await fixture(); await planStoredScenes({ root, story, chapter: 1, provider: new SceneLLM() }); await generateStoredArtwork({ root, story, chapter: 1, provider: new FakeImages() }); await reviewStoredArtwork({ root, story, chapter: 1, sceneId: "scene-001", review: "approved" }); const video = new CaptureVideo(); await renderStoredChapterVideo({ root, story: { ...story, video: { ...story.video, subtitleMode: "none", backgroundMode: "gradient" } }, chapter: 1, processor: video }); expect(video.input.sceneArtwork).toBeUndefined(); expect(video.input.cover).toBeUndefined(); });
});
