import { mkdtemp, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { generateStoredSubtitles, subtitleFingerprint } from "../src/subtitles/chapter-subtitles.js";
import { toSrt } from "../src/subtitles/srt.js";
import { generateSubtitleTiming, segmentNarration } from "../src/subtitles/timing.js";
import { toVtt } from "../src/subtitles/vtt.js";
import { FfmpegVideoTools } from "../src/video/ffmpeg-video.js";
import { renderStoredChapterVideo, videoFingerprint } from "../src/video/chapter-video.js";
import { buildVideoArgs, validateChapterVideo, VideoProcessor } from "../src/video/renderer.js";
import { assembleVideoExport, buildVideoExportArgs, VideoExportProcessor } from "../src/video/video-export.js";
import { AudioProbe } from "../src/audio/ffmpeg.js";
import { chapterSchema } from "../src/domain/chapter.js";
import { atomicWrite, atomicWriteJson } from "../src/storage/atomic-write.js";
import { storyPaths } from "../src/storage/paths.js";
import { testStory } from "./helpers.js";

class FakeVideo implements VideoProcessor { readonly version = "fake-video-v1"; calls = 0; async render(_input: any, output: string, settings: any) { this.calls++; await atomicWrite(output, Buffer.from(`video-${this.calls}`)); return { durationSeconds: 13, videoCodec: "h264", audioCodec: "aac", width: settings.width, height: settings.height, container: "mp4" }; } }
class FakeVideoExport implements VideoExportProcessor { readonly version = "fake-export-v1"; calls = 0; order: number[] = []; async assemble(chapters: any[], output: string) { this.calls++; this.order = chapters.map((item) => item.chapter); await atomicWrite(output, Buffer.from(`export-${this.calls}`)); return { durationSeconds: 26, videoCodec: "h264", audioCodec: "aac", width: 1920, height: 1080, container: "mp4" }; } }

async function fixture(numbers = [1]) { const root = await mkdtemp(join(tmpdir(), "story-video-")); const story = testStory(); const complete = { status: "complete" as const, fingerprint: "in", outputFingerprint: "out" }; for (const chapter of numbers) { const paths = storyPaths(root, story.slug, chapter); const now = new Date().toISOString(); const metadata = chapterSchema.parse({ chapter, originalTitle: `Title ${chapter}`, sourceLanguage: story.sourceLanguage, outputLanguage: story.outputLanguage, counts: { originalCharacters: 10, englishWords: 8, narrationWords: 8 }, createdAt: now, updatedAt: now, stages: { ingestion: complete, translation: complete, narration: { ...complete, outputFingerprint: `narration-${chapter}` }, qa: complete, storyBible: complete, tts: complete, audioMastering: { ...complete, outputFingerprint: `audio-${chapter}` }, subtitles: { status: "pending" }, video: { status: "pending" } }, audio: { durationSeconds: 10, codec: "mp3", container: "mp3" } }); await atomicWriteJson(paths.chapterMeta, metadata); await atomicWrite(paths.narration, "The lantern opened. A long road waited beyond the door, quiet and silver."); await atomicWrite(paths.audio, Buffer.from("mastered-audio")); } return { root, story }; }

describe("deterministic subtitles", () => {
  it("segments sentences and long phrases into readable caption chunks", () => { const chunks = segmentNarration("First sentence. This is a much longer sentence, with a clause that should split into a readable second caption!", 42); expect(chunks.length).toBeGreaterThan(2); expect(chunks.every((chunk) => chunk.length <= 42)).toBe(true); });
  it("allocates ordered timing and makes the final cue end at the mastered duration", () => { const document = generateSubtitleTiming("One short line. A second, somewhat longer spoken sentence. The end.", 12.345, testStory().subtitles); expect(document.cues[0]!.startSeconds).toBe(0); expect(document.cues.at(-1)!.endSeconds).toBe(12.345); for (let index = 1; index < document.cues.length; index++) expect(document.cues[index]!.startSeconds).toBe(document.cues[index - 1]!.endSeconds); });
  it("formats standards-compliant SRT and WebVTT timestamps", () => { const document = generateSubtitleTiming("Opening line. Closing line.", 5.25, testStory().subtitles); expect(toSrt(document)).toMatch(/1\n00:00:00,000 -->/); expect(toSrt(document)).toContain("00:00:05,250"); expect(toVtt(document)).toMatch(/^WEBVTT\n\n00:00:00\.000 -->/); });
  it("reuses subtitle files and invalidates only from relevant settings", async () => { const { root, story } = await fixture(); const first = await generateStoredSubtitles({ root, story, chapter: 1 }); const second = await generateStoredSubtitles({ root, story, chapter: 1 }); expect(first.reused).toBe(false); expect(second.reused).toBe(true); const changed = { ...story, subtitles: { ...story.subtitles, maxCharactersPerLine: 36 } }; expect((await generateStoredSubtitles({ root, story: changed, chapter: 1 })).reused).toBe(false); expect(subtitleFingerprint("n", "a", story.subtitles)).not.toBe(subtitleFingerprint("n", "a", changed.subtitles)); });
});

describe("chapter video", () => {
  it("generates FFmpeg arguments for fallback, intro, audio, and optional subtitles", () => { const story = testStory(); const args = buildVideoArgs({ audio: "audio.mp3", subtitles: "subtitles.srt", storyTitle: "Book", chapterLabel: "Chapter 1", chapterTitle: "Opening", audioDurationSeconds: 10 }, "video.mp4", { ...story.video, width: 1280, height: 720, subtitleMode: "both" }); const command = args.join(" "); expect(command).toContain("color=c="); expect(command).toContain("drawtext="); expect(command).toContain("subtitles=filename="); expect(command).toContain("mov_text"); expect(command).toContain("libx264"); });
  it("validates ffprobe video streams, codec, resolution, and duration", async () => { const tools = new FfmpegVideoTools("ffmpeg", "ffprobe", async () => ({ stdout: JSON.stringify({ format: { duration: "13", format_name: "mp4" }, streams: [{ codec_type: "video", codec_name: "h264", width: 1920, height: 1080 }, { codec_type: "audio", codec_name: "aac" }] }), stderr: "" })); await expect(tools.probe("video.mp4")).resolves.toMatchObject({ videoCodec: "h264", audioCodec: "aac", width: 1920 }); expect(() => validateChapterVideo({ durationSeconds: 13, videoCodec: "h264", audioCodec: "aac", width: 720, height: 480, container: "mp4" }, testStory().video, 13)).toThrow("Expected 1920x1080"); });
  it("reuses video fingerprints and video settings invalidate no upstream stage", async () => { const { root, story } = await fixture(); await generateStoredSubtitles({ root, story, chapter: 1 }); const processor = new FakeVideo(); const first = await renderStoredChapterVideo({ root, story, chapter: 1, processor }); const second = await renderStoredChapterVideo({ root, story, chapter: 1, processor }); expect(first.reused).toBe(false); expect(second.reused).toBe(true); const changed = { ...story, video: { ...story.video, quality: 24 } }; await renderStoredChapterVideo({ root, story: changed, chapter: 1, processor }); expect(processor.calls).toBe(2); const metadata = chapterSchema.parse(JSON.parse(await readFile(storyPaths(root, story.slug, 1).chapterMeta, "utf8"))); expect(metadata.stages.tts.status).toBe("complete"); expect(metadata.stages.audioMastering.status).toBe("complete"); expect(videoFingerprint("a", "s", "b", story.video, "t")).not.toBe(videoFingerprint("a", "s", "b", changed.video, "t")); });
});

describe("combined video export", () => {
  it("preserves numeric chapter ordering and caches unchanged exports", async () => { const { root, story } = await fixture([2, 1]); const renderer = new FakeVideo(); for (const chapter of [2, 1]) { await generateStoredSubtitles({ root, story, chapter }); await renderStoredChapterVideo({ root, story, chapter, processor: renderer }); } const processor = new FakeVideoExport(); const first = await assembleVideoExport({ root, story, from: 1, to: 2, processor }); const second = await assembleVideoExport({ root, story, from: 1, to: 2, processor }); expect(first.reused).toBe(false); expect(second.reused).toBe(true); expect(processor.order).toEqual([1, 2]); expect(processor.calls).toBe(1); const command = buildVideoExportArgs([{ chapter: 1, title: "One", path: "1.mp4", durationSeconds: 13, fingerprint: "a" }], "book.mp4", "chapters.ffmeta").join(" "); expect(command).toContain("map_chapters"); });
});
