import { mkdir } from "node:fs/promises";
import { join } from "node:path";
import { DatabasePool } from "../queue/database.js";
import { atomicWriteJson } from "../storage/atomic-write.js";
import { logger } from "../utils/logger.js";
import { CostFilters, ProviderUsageRecord, UsageSink, providerUsageRecordSchema } from "./types.js";

export class PostgresUsageRepository implements UsageSink {
  constructor(private readonly pool: DatabasePool, private readonly root: string) {}
  async record(raw: ProviderUsageRecord) { const value = providerUsageRecordSchema.parse(raw); const result = await this.pool.query(
    `INSERT INTO provider_usage(id,idempotency_key,story,chapter,production_run_id,queue_job_id,stage,provider,model,operation,attempted_at,completed_at,attempt,input_tokens,cached_input_tokens,output_tokens,input_characters,input_utf8_bytes,output_bytes,audio_duration_seconds,image_count,image_quality,image_size,request_id,success,error_category,retry,cost_usd,cost_status,pricing_snapshot,record)
     VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31) ON CONFLICT(idempotency_key) DO NOTHING RETURNING id`,
    [value.id,value.idempotencyKey,value.story,value.chapter,value.productionRunId,value.queueJobId,value.stage,value.provider,value.model,value.operation,value.attemptedAt,value.completedAt,value.attempt,value.inputTokens,value.cachedInputTokens,value.outputTokens,value.inputCharacters,value.inputUtf8Bytes,value.outputBytes,value.audioDurationSeconds,value.imageCount,value.imageQuality,value.imageSize,value.requestId,value.success,value.errorCategory,value.retry,value.costUsd,value.costStatus,value.pricing??null,value]);
    if (!result.rowCount) return;
    try { const directory = join(this.root,"stories",value.story,"analytics","usage"); await mkdir(directory,{recursive:true}); await atomicWriteJson(join(directory,`${value.id}.json`),value); }
    catch (error) { logger.warn({event:"cost.portable_mirror_failed",story:value.story,id:value.id,error:error instanceof Error?error.message:String(error)}); }
  }
  async summary(filters: CostFilters = {}) { const { where, values } = queryParts(filters); const aggregate = await this.pool.query(`SELECT COALESCE(sum(cost_usd),0)::float8 AS "totalCostUsd",count(*)::int AS requests,count(*) FILTER (WHERE success)::int AS successful,count(*) FILTER (WHERE NOT success)::int AS failed,count(*) FILTER (WHERE retry)::int AS retries,COALESCE(sum(input_tokens),0)::float8 AS "inputTokens",COALESCE(sum(cached_input_tokens),0)::float8 AS "cachedInputTokens",COALESCE(sum(output_tokens),0)::float8 AS "outputTokens",COALESCE(sum(input_utf8_bytes),0)::float8 AS "inputUtf8Bytes",COALESCE(sum(image_count),0)::int AS images,count(*) FILTER (WHERE cost_status='unavailable')::int AS "unpricedRequests" FROM provider_usage ${where}`,values);
    const dimensions = await this.pool.query(`SELECT stage,provider,model,count(*)::int AS requests,COALESCE(sum(cost_usd),0)::float8 AS "costUsd",COALESCE(sum(input_tokens),0)::float8 AS "inputTokens",COALESCE(sum(output_tokens),0)::float8 AS "outputTokens",COALESCE(sum(input_utf8_bytes),0)::float8 AS "inputUtf8Bytes",COALESCE(sum(image_count),0)::int AS images,count(*) FILTER (WHERE NOT success)::int AS failures FROM provider_usage ${where} GROUP BY stage,provider,model ORDER BY "costUsd" DESC,requests DESC`,values);
    const chapters = filters.story ? await this.pool.query(`SELECT chapter,count(*)::int AS requests,COALESCE(sum(cost_usd),0)::float8 AS "costUsd",count(*) FILTER (WHERE cost_status='unavailable')::int AS unpriced FROM provider_usage ${where} GROUP BY chapter ORDER BY chapter NULLS LAST`,values) : { rows: [] };
    return { summary: aggregate.rows[0], dimensions: dimensions.rows, chapters: chapters.rows };
  }
  async list(filters: CostFilters = {}) { const page=Math.max(1,filters.page??1),pageSize=Math.min(200,Math.max(1,filters.pageSize??50));const {where,values}=queryParts(filters);const count=await this.pool.query<{total:number}>(`SELECT count(*)::int AS total FROM provider_usage ${where}`,values);const rows=await this.pool.query<{record:ProviderUsageRecord}>(`SELECT record FROM provider_usage ${where} ORDER BY attempted_at DESC,id DESC LIMIT $${values.length+1} OFFSET $${values.length+2}`,[...values,pageSize,(page-1)*pageSize]);const total=count.rows[0]?.total??0;return{items:rows.rows.map(row=>providerUsageRecordSchema.parse(row.record)),page,pageSize,total,pages:Math.max(1,Math.ceil(total/pageSize))}; }
  async recordedCost(filters: Pick<CostFilters,"story"|"productionRunId"|"queueJobId">) { return (await this.summary(filters)).summary.totalCostUsd as number; }
}
function queryParts(filters:CostFilters){const clauses:string[]=[],values:unknown[]=[];const add=(sql:string,value:unknown)=>{values.push(value);clauses.push(sql.replace("?",`$${values.length}`));};if(filters.story)add("story = ?",filters.story);if(filters.chapterFrom!==undefined)add("chapter >= ?",filters.chapterFrom);if(filters.chapterTo!==undefined)add("chapter <= ?",filters.chapterTo);if(filters.productionRunId)add("production_run_id = ?",filters.productionRunId);if(filters.queueJobId)add("queue_job_id = ?",filters.queueJobId);if(filters.stage)add("stage = ?",filters.stage);if(filters.provider)add("provider = ?",filters.provider);if(filters.model)add("model = ?",filters.model);if(filters.fromDate)add("attempted_at >= ?",filters.fromDate);if(filters.toDate)add("attempted_at < ?",filters.toDate);return{where:clauses.length?`WHERE ${clauses.join(" AND ")}`:"",values};}
