import { useEffect, useRef, useState } from "react";
import { inspectVisualCheck, startVisualCheck, type VisualCheck, type VisualCheckTarget } from "./visual-workflow.js";
import { VisualWorkflowJob, useVisualWorkflowJob } from "./VisualWorkflowJob.js";
export function ArtworkVisualCheck({ slug, target }: { slug: string; target: VisualCheckTarget }) {
  const [check, setCheck] = useState<VisualCheck | null>(null); const [stale, setStale] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [config, setConfig] = useState(""); const [open, setOpen] = useState(false);
  const key = `${slug}:${JSON.stringify(target)}`; const current = useRef(key); current.current = key;
  const inspect = async () => { setBusy(true); setError(""); try { const result = await inspectVisualCheck(slug, target); if (current.current !== key) return; setCheck(result.check); setStale(result.stale); setConfig(`${result.provider} / ${result.model}`); } catch (error) { if (current.current === key) setError(String(error)); } finally { if (current.current === key) setBusy(false); } };
  const work = useVisualWorkflowJob(slug, `check:${key}`, job => { if (job.result?.check) void inspect(); });
  useEffect(() => { setCheck(null); setStale(false); setError(""); if (open) void inspect(); }, [key, slug, open]);
  return <details className="visual-workflow-panel" onToggle={event => setOpen(event.currentTarget.open)}><summary>Advisory AI visual check</summary><p>Optional paid check using the book’s QA model{config && ` (${config})`}. Checks identity, creature anatomy, specified counts, signature features and composition. Results require your judgment and never approve artwork.</p><button type="button" disabled={busy || work.active} onClick={async () => { setBusy(true); setError(""); try { work.track(await startVisualCheck(slug, target)); } catch (error) { setError(String(error)); } finally { setBusy(false); } }}>{busy || work.active ? "Checking…" : check && !stale ? "Reuse current check" : "Run AI visual check"}</button>{check && <button type="button" disabled={busy || work.active} onClick={async () => { try { work.track(await startVisualCheck(slug, target, true)); } catch (error) { setError(String(error)); } }}>Run a fresh paid check</button>}{error && <p role="alert">{error}</p>}{stale && <p role="status">This check predates changes to the artwork, scene, references or QA settings. Run it again to review the current design.</p>}
    {check && <div><strong>{check.summary}</strong><ul>{(["identity", "creatureForm", "count", "signatureFeatures", "composition"] as const).map(category => <li key={category}><b>{category.replace(/([A-Z])/g, " $1")}: {check[category].status.replaceAll("_", " ")}</b><p>{check[category].observation}</p></li>)}</ul><small>{check.provider} / {check.model} · {new Date(check.checkedAt).toLocaleString()}</small></div>}<VisualWorkflowJob job={work.job} error={work.error} />
  </details>;
}
