import { useEffect, useState } from "react";
import { api } from "./api.js";
import "./background-music.css";

export type MusicSelection = { mode: "none" } | { mode: "story_default" } | { mode: "track"; trackId: string };
type Track = { id: string; title: string; durationSeconds: number; license?: string; attribution?: string; source?: string; sourceUrl?: string; commercialUse?: boolean; tags: string[] };
type Settings = { defaultTrackId?: string; level: "very_soft" | "subtle" | "balanced" | "present" | "custom"; customGainDb?: number; ducking: { enabled: boolean; strength: "gentle" | "normal" | "strong" }; fadeInSeconds: number; fadeOutSeconds: number; loopMode: "continuous" | "restart_chapter" };

export type MusicOverrides = Partial<Omit<Settings, "ducking">> & { ducking?: Partial<Settings["ducking"]> };
export function BackgroundMusicControls({ slug, selection, onSelectionChange, overrides, onOverridesChange }: { slug: string; selection: MusicSelection; onSelectionChange: (value: MusicSelection) => void; overrides?: MusicOverrides; onOverridesChange?: (value: MusicOverrides) => void }) {
  const [tracks, setTracks] = useState<Track[]>([]);
  const [settings, setSettings] = useState<Settings>();
  const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [metadata, setMetadata] = useState({ title: "", source: "", sourceUrl: "", license: "", attribution: "", commercialUse: false, tags: "" });
  const refresh = () => { void api<{ tracks: Track[] }>("/music/tracks").then((value) => setTracks(Array.isArray(value?.tracks) ? value.tracks : [])).catch((cause) => setError(String(cause))); };
  useEffect(() => { refresh(); void api<Settings>(`/stories/${slug}/background-music`).then((value) => { if (value && typeof value.level === "string" && value.ducking) setSettings(value); }).catch((cause) => setError(String(cause))); }, [slug]);
  const save = async (next: Settings) => { try { setError(""); const saved = await api<Settings>(`/stories/${slug}/background-music`, { method: "PUT", body: JSON.stringify(next) }); setSettings(saved); setNotice("Story music preferences saved."); } catch (cause) { setError(String(cause)); } };
  const upload = async (file: File) => { try { setError(""); setNotice(""); const track = await api<Track>("/music/tracks", { method: "POST", headers: { "X-File-Name": encodeURIComponent(file.name), "X-Music-Metadata": encodeURIComponent(JSON.stringify({ title: metadata.title.trim() || file.name.replace(/\.[^.]+$/, ""), source: metadata.source || undefined, sourceUrl: metadata.sourceUrl || undefined, license: metadata.license || undefined, attribution: metadata.attribution || undefined, commercialUse: metadata.commercialUse ? true : undefined, tags: metadata.tags.split(",").map((value) => value.trim()).filter(Boolean) })) }, body: file }); refresh(); setNotice(`Imported ${track.title}.`); } catch (cause) { setError(String(cause)); } };
  const edit = async (track: Track) => { const title = window.prompt("Track title", track.title); if (title === null || !title.trim()) return; const license = window.prompt("License (optional)", track.license ?? ""); if (license === null) return; const attribution = window.prompt("Attribution (optional)", track.attribution ?? ""); if (attribution === null) return; const source = window.prompt("Source (optional)", track.source ?? ""); if (source === null) return; const sourceUrl = window.prompt("Source URL (optional)", track.sourceUrl ?? ""); if (sourceUrl === null) return; const commercialUse = window.confirm("Commercial use allowed? Choose Cancel for no/unknown."); const tags = window.prompt("Tags, comma separated", track.tags.join(", ")); if (tags === null) return; try { const updated = await api<Track>(`/music/tracks/${track.id}`, { method: "PATCH", body: JSON.stringify({ title: title.trim(), license, attribution, source, sourceUrl: sourceUrl || undefined, commercialUse, tags: tags.split(",").map((value) => value.trim()).filter(Boolean) }) }); setTracks((current) => current.map((item) => item.id === track.id ? updated : item)); } catch (cause) { setError(String(cause)); } };
  const remove = async (track: Track) => { if (!window.confirm(`Remove ${track.title} from the music library? Existing exported files remain available.`)) return; try { await api(`/music/tracks/${track.id}`, { method: "DELETE" }); refresh(); if (settings?.defaultTrackId === track.id) await save({ ...settings, defaultTrackId: undefined }); if (selection.mode === "track" && selection.trackId === track.id) onSelectionChange({ mode: "none" }); } catch (cause) { setError(String(cause)); } };
  return <section className="music-controls"><h3>Background music</h3><p>Choose music only when building an export. Clean chapter masters stay unchanged.</p>
    <label>Music for this export <select value={selection.mode === "track" ? `track:${selection.trackId}` : selection.mode} onChange={(event) => { const value = event.target.value; onSelectionChange(value.startsWith("track:") ? { mode: "track", trackId: value.slice(6) } : value === "story_default" ? { mode: "story_default" } : { mode: "none" }); }}><option value="none">No music</option><option value="story_default" disabled={!settings?.defaultTrackId || !tracks.some((track) => track.id === settings.defaultTrackId)}>Story default{settings?.defaultTrackId ? "" : " (not set)"}</option>{tracks.map((track) => <option key={track.id} value={`track:${track.id}`}>{track.title}</option>)}</select></label>
    {settings && <div className="music-preferences"><label>Default track <select value={settings.defaultTrackId ?? ""} onChange={(event) => void save({ ...settings, defaultTrackId: event.target.value || undefined })}><option value="">None</option>{tracks.map((track) => <option key={track.id} value={track.id}>{track.title}</option>)}</select></label><label>Music level <select value={settings.level} onChange={(event) => void save({ ...settings, level: event.target.value as Settings["level"], customGainDb: event.target.value === "custom" ? settings.customGainDb ?? -22 : settings.customGainDb })}><option value="very_soft">Very soft</option><option value="subtle">Subtle</option><option value="balanced">Balanced</option><option value="present">Present</option><option value="custom">Custom</option></select></label>{settings.level === "custom" && <label>Gain dB <input type="number" min="-40" max="-6" value={settings.customGainDb ?? -22} onChange={(event) => setSettings({ ...settings, customGainDb: Number(event.target.value) })} onBlur={() => void save(settings)} /></label>}<label><input type="checkbox" checked={settings.ducking.enabled} onChange={(event) => void save({ ...settings, ducking: { ...settings.ducking, enabled: event.target.checked } })} /> Duck music beneath speech</label><label>Ducking strength <select value={settings.ducking.strength} onChange={(event) => void save({ ...settings, ducking: { ...settings.ducking, strength: event.target.value as Settings["ducking"]["strength"] } })}><option value="gentle">Gentle</option><option value="normal">Normal</option><option value="strong">Strong</option></select></label><label>Loop <select value={settings.loopMode} onChange={(event) => void save({ ...settings, loopMode: event.target.value as Settings["loopMode"] })}><option value="continuous">Continuous</option><option value="restart_chapter" disabled>Restart each chapter (coming later)</option></select></label><label>Fade in seconds <input type="number" min="0" max="30" step="0.5" value={settings.fadeInSeconds} onChange={(event) => setSettings({ ...settings, fadeInSeconds: Number(event.target.value) })} onBlur={() => void save(settings)} /></label><label>Fade out seconds <input type="number" min="0" max="30" step="0.5" value={settings.fadeOutSeconds} onChange={(event) => setSettings({ ...settings, fadeOutSeconds: Number(event.target.value) })} onBlur={() => void save(settings)} /></label></div>}
    {onOverridesChange && <details><summary>Advanced settings for this export</summary><p>These changes apply to this export only.</p><label>Level <select value={overrides?.level ?? settings?.level ?? "subtle"} onChange={(event) => onOverridesChange({ ...overrides, level: event.target.value as Settings["level"], customGainDb: event.target.value === "custom" ? overrides?.customGainDb ?? settings?.customGainDb ?? -22 : overrides?.customGainDb })}><option value="very_soft">Very soft</option><option value="subtle">Subtle</option><option value="balanced">Balanced</option><option value="present">Present</option><option value="custom">Custom</option></select></label>{(overrides?.level ?? settings?.level) === "custom" && <label>Gain dB <input type="number" min="-40" max="-6" value={overrides?.customGainDb ?? settings?.customGainDb ?? -22} onChange={(event) => onOverridesChange({ ...overrides, customGainDb: Number(event.target.value) })} /></label>}<label><input type="checkbox" checked={overrides?.ducking?.enabled ?? settings?.ducking?.enabled ?? true} onChange={(event) => onOverridesChange({ ...overrides, ducking: { ...overrides?.ducking, enabled: event.target.checked } })} /> Duck beneath narration</label><label>Ducking <select value={overrides?.ducking?.strength ?? settings?.ducking?.strength ?? "normal"} onChange={(event) => onOverridesChange({ ...overrides, ducking: { ...overrides?.ducking, strength: event.target.value as Settings["ducking"]["strength"] } })}><option value="gentle">Gentle</option><option value="normal">Normal</option><option value="strong">Strong</option></select></label><label>Fade in <input type="number" min="0" max="30" step="0.5" value={overrides?.fadeInSeconds ?? settings?.fadeInSeconds ?? 1.5} onChange={(event) => onOverridesChange({ ...overrides, fadeInSeconds: Number(event.target.value) })} /></label><label>Fade out <input type="number" min="0" max="30" step="0.5" value={overrides?.fadeOutSeconds ?? settings?.fadeOutSeconds ?? 2} onChange={(event) => onOverridesChange({ ...overrides, fadeOutSeconds: Number(event.target.value) })} /></label><label>Playback <select value={overrides?.loopMode ?? settings?.loopMode ?? "continuous"} onChange={(event) => onOverridesChange({ ...overrides, loopMode: event.target.value as Settings["loopMode"] })}><option value="continuous">Continuous</option><option value="restart_chapter" disabled>Restart each chapter (coming later)</option></select></label><button type="button" onClick={() => onOverridesChange({})}>Reset export overrides</button></details>}
    <div className="music-library"><h4>Music library</h4><div className="music-import-fields"><label>Title <input value={metadata.title} onChange={(event) => setMetadata({ ...metadata, title: event.target.value })} /></label><label>Source <input value={metadata.source} onChange={(event) => setMetadata({ ...metadata, source: event.target.value })} /></label><label>Source URL <input value={metadata.sourceUrl} onChange={(event) => setMetadata({ ...metadata, sourceUrl: event.target.value })} /></label><label>License <input value={metadata.license} onChange={(event) => setMetadata({ ...metadata, license: event.target.value })} /></label><label>Attribution <input value={metadata.attribution} onChange={(event) => setMetadata({ ...metadata, attribution: event.target.value })} /></label><label>Tags (comma separated) <input value={metadata.tags} onChange={(event) => setMetadata({ ...metadata, tags: event.target.value })} /></label><label><input type="checkbox" checked={metadata.commercialUse} onChange={(event) => setMetadata({ ...metadata, commercialUse: event.target.checked })} /> Commercial use allowed</label></div><label>Import local audio <input type="file" accept=".mp3,.wav,.m4a,.flac,.ogg,audio/*" onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file); event.currentTarget.value = ""; }} /></label>{tracks.map((track) => <article key={track.id}><b>{track.title}</b><small>{Math.round(track.durationSeconds)}s{track.license ? ` · ${track.license}` : ""}{track.attribution ? ` · ${track.attribution}` : ""}{track.source ? ` · ${track.source}` : ""}{track.commercialUse === true ? " · Commercial use allowed" : ""}{track.tags.length ? ` · ${track.tags.join(", ")}` : ""}</small><audio controls preload="none" src={`/api/music/tracks/${track.id}/audio`} /><button type="button" onClick={() => void edit(track)}>Edit</button><button type="button" onClick={() => void remove(track)}>Remove</button></article>)}</div>
    {settings?.defaultTrackId && !tracks.some((track) => track.id === settings.defaultTrackId) && <p role="alert">The story default track is missing. Choose another track before exporting with story default.</p>}
    {notice && <p role="status">{notice}</p>}{error && <p role="alert">{error}</p>}
  </section>;
}
