import { useEffect, useState } from "react";
import { api } from "./api.js";

export type Bed = { id: string; name: string; tracks: Array<{ trackId: string }>; playbackMode: "sequential" | "shuffle"; crossfadeSeconds: number };
export function MusicBedEditor({ tracks, beds, refresh }: { tracks: Array<{ id: string; title: string }>; beds: Bed[]; refresh: () => void }) {
  const [name, setName] = useState(""); const [ids, setIds] = useState<string[]>([]); const [mode, setMode] = useState<"sequential" | "shuffle">("sequential"); const [crossfade, setCrossfade] = useState(3); const [editing, setEditing] = useState<string>(); const [error, setError] = useState("");
  useEffect(() => { if (ids.length === 0 && tracks[0] && !editing) setIds([tracks[0].id]); }, [tracks]);
  const save = async () => { try { setError(""); await api(editing ? `/music/beds/${editing}` : "/music/beds", { method: editing ? "PUT" : "POST", body: JSON.stringify({ name, tracks: ids.map((trackId) => ({ trackId })), playbackMode: mode, crossfadeSeconds: crossfade }) }); setEditing(undefined); setName(""); refresh(); } catch (cause) { setError(String(cause)); } };
  return <details><summary>Music beds</summary><p>Arrange local tracks into a reusable bed. Shuffle order is deterministic for each export.</p><label>Bed name <input value={name} onChange={(event) => setName(event.target.value)} /></label><label>Playback <select value={mode} onChange={(event) => setMode(event.target.value as typeof mode)}><option value="sequential">Sequential</option><option value="shuffle">Shuffle</option></select></label><label>Crossfade seconds <input type="number" min="0" max="10" step="0.5" value={crossfade} onChange={(event) => setCrossfade(Number(event.target.value))} /></label>{ids.map((id, index) => <div key={index}><label>Track {index + 1} <select value={id} onChange={(event) => setIds(ids.map((value, i) => i === index ? event.target.value : value))}>{tracks.map((track) => <option key={track.id} value={track.id}>{track.title}</option>)}</select></label><button type="button" onClick={() => setIds(ids.filter((_, i) => i !== index))}>Remove</button></div>)}<button type="button" disabled={!tracks.length || ids.length >= 30} onClick={() => setIds([...ids, tracks[0]!.id])}>Add track</button><button type="button" disabled={!name.trim() || !ids.length} onClick={() => void save()}>{editing ? "Update bed" : "Save bed"}</button>{beds.map((bed) => <article key={bed.id}><b>{bed.name}</b><small>{bed.tracks.length} tracks · {bed.playbackMode} · {bed.crossfadeSeconds}s crossfade</small><button type="button" onClick={() => { setEditing(bed.id); setName(bed.name); setIds(bed.tracks.map((item) => item.trackId)); setMode(bed.playbackMode); setCrossfade(bed.crossfadeSeconds); }}>Edit</button><button type="button" onClick={() => { if (!window.confirm(`Delete ${bed.name}? Existing exports remain available.`)) return; void api(`/music/beds/${bed.id}`, { method: "DELETE" }).then(refresh).catch((cause) => setError(String(cause))); }}>Delete</button></article>)}{error && <p role="alert">{error}</p>}</details>;
}
