import { useEffect, useState } from "react";
import { api, post, QueueEvent, QueueJob, QueuePage, QueueWorkItem } from "./api.js";
import { pretty } from "./format.js";

type JobDetail = { job: QueueJob; workItems: QueuePage<QueueWorkItem>; events: QueueEvent[] };

export function QueueStudioPage({ navigate }: { navigate: (path: string) => void }) {
  const [jobs, setJobs] = useState<QueuePage<QueueJob>>(); const [summary, setSummary] = useState<any>(); const [page, setPage] = useState(1); const [itemPage, setItemPage] = useState(1);
  const [selected, setSelected] = useState<string | undefined>(() => new URLSearchParams(location.search).get("job") ?? undefined); const [detail, setDetail] = useState<JobDetail>(); const [error, setError] = useState("");
  const load = async () => { try { setError(""); const [nextJobs, nextSummary] = await Promise.all([api<QueuePage<QueueJob>>(`/queue/jobs?page=${page}&pageSize=25`), api<any>("/queue/summary")]); setJobs(nextJobs); setSummary(nextSummary); if (selected) setDetail(await api<JobDetail>(`/queue/jobs/${selected}?page=${itemPage}&pageSize=50`)); } catch (value) { setError(message(value)); } };
  useEffect(() => { void load(); const timer = setInterval(() => void load(), 2_000); return () => clearInterval(timer); }, [page, itemPage, selected]);
  useEffect(() => { if (!selected) return; const source = new EventSource(`/api/queue/jobs/${selected}/events`); source.addEventListener("job", () => void load()); source.onerror = () => source.close(); return () => source.close(); }, [selected, itemPage]);
  const select = (id: string) => { setSelected(id); setItemPage(1); history.replaceState({}, "", `/queue?job=${id}`); };
  const control = async (action: string) => { if (!selected) return; try { await post(`/queue/jobs/${selected}/${action}`, {}); await load(); } catch (value) { setError(message(value)); } };
  const counts = { queued: summary?.jobs?.queued ?? 0, running: summary?.jobs?.running ?? 0, completed: (summary?.jobs?.completed ?? 0) + (summary?.jobs?.completed_with_warnings ?? 0), warning: summary?.workItems?.warning ?? 0, "retry waiting": summary?.workItems?.retry_wait ?? 0, "needs review": summary?.workItems?.needs_review ?? 0, failed: summary?.workItems?.failed ?? 0 };
  return <section className="page queue-page"><div className="section-heading"><div><span className="eyebrow">Long-run control room</span><h2>Production queue</h2><p>Durable chapter work, ordered for Story Bible continuity and recoverable after restarts.</p></div><button className="button" onClick={() => navigate("/review")}>Needs review</button></div>{error && <div className="error-box">{error}</div>}
    <div className="queue-tally">{Object.entries(counts).map(([label, value]) => <article key={label} className={label.replaceAll(" ", "-")}><span>{label}</span><b>{String(value)}</b></article>)}</div>
    <div className="queue-layout"><div className="queue-ledger"><header><span>Run</span><span>Progress</span><span>Now</span><span>Updated</span></header>{jobs?.items.map((job) => { const done = job.completedItems + job.warningItems + job.reviewItems + job.failedItems; const percent = Math.round(done / Math.max(1, job.totalItems) * 100); return <button className={selected === job.id ? "selected" : ""} key={job.id} onClick={() => select(job.id)}><span><b>{job.story}</b><small>Chapters {job.from}–{job.to} · {pretty(job.profile ?? "custom")}</small></span><span><i><em style={{ width: `${percent}%` }} /></i><small>{done}/{job.totalItems} · {percent}%</small></span><span><strong className={`queue-state ${job.status}`}>{pretty(job.status)}</strong><small>{job.currentChapter ? `Ch. ${job.currentChapter} · ${pretty(job.currentStage ?? "working")}` : "—"}</small></span><span><small>{new Date(job.updatedAt).toLocaleString()}</small></span></button>; })}{jobs && !jobs.items.length && <p className="queue-empty">No durable production jobs yet. Review a production plan, then start it.</p>}</div>
      <aside className="queue-inspector">{detail ? <><div className="queue-inspector-head"><span className={`queue-state ${detail.job.status}`}>{pretty(detail.job.status)}</span><h3>{detail.job.story}</h3><p>Chapters {detail.job.from}–{detail.job.to}</p></div><div className="queue-actions">{["queued", "running"].includes(detail.job.status) && <button onClick={() => void control("pause")}>Pause after chapter</button>}{detail.job.status === "paused" && <button onClick={() => void control("resume")}>Resume</button>}{!["completed", "completed_with_warnings", "failed", "cancelled"].includes(detail.job.status) && <button className="danger" onClick={() => void control("cancel")}>Cancel</button>}</div><dl><div><dt>Complete</dt><dd>{detail.job.completedItems}</dd></div><div><dt>Warnings</dt><dd>{detail.job.warningItems}</dd></div><div><dt>Review</dt><dd>{detail.job.reviewItems}</dd></div><div><dt>Failed</dt><dd>{detail.job.failedItems}</dd></div></dl><div className="work-scroll">{detail.workItems.items.map((item) => <div className="work-line" key={item.id}><i className={item.status} /><span><b>Chapter {item.chapter}</b><small>{pretty(item.currentStage ?? item.status)}{item.reused ? " · cached" : ""}</small></span><em>{item.attemptCount}/{item.maxAttempts}</em></div>)}</div>{detail.workItems.pages > 1 && <div className="queue-mini-pages"><button disabled={itemPage === 1} onClick={() => setItemPage(itemPage - 1)}>←</button><span>{itemPage}/{detail.workItems.pages}</span><button disabled={itemPage === detail.workItems.pages} onClick={() => setItemPage(itemPage + 1)}>→</button></div>}<div className="queue-history"><span className="eyebrow">Recent operations</span>{detail.events.slice(-12).reverse().map((event) => <p key={event.id}><i />{event.message}<small>{new Date(event.createdAt).toLocaleTimeString()}</small></p>)}</div></> : <div className="queue-invitation"><span>⌁</span><h3>Select a run</h3><p>Inspect its current chapter, attempts, and persisted controls.</p></div>}</aside></div>
    {jobs && jobs.pages > 1 && <div className="pagination"><button disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page} / {jobs.pages}</span><button disabled={page === jobs.pages} onClick={() => setPage(page + 1)}>Next</button></div>}</section>;
}

export function NeedsReviewPage({ navigate }: { navigate: (path: string) => void }) {
  const [data, setData] = useState<QueuePage<QueueWorkItem>>(); const [page, setPage] = useState(1); const [error, setError] = useState(""); const load = () => api<QueuePage<QueueWorkItem>>(`/queue/review?page=${page}&pageSize=40`).then(setData).catch((value) => setError(message(value))); useEffect(() => { void load(); }, [page]);
  const act = async (item: QueueWorkItem, action: "retry" | "resolve" | "skip", body: unknown = {}) => { try { setError(""); await post(`/queue/items/${item.id}/${action}`, body); await load(); } catch (value) { setError(message(value)); } };
  return <section className="page review-queue-page"><div className="section-heading"><div><span className="eyebrow">Intervention desk</span><h2>Needs review</h2><p>Nothing is silently skipped. Resolve, retry, or explicitly set an independent visual stage aside.</p></div><button className="button" onClick={() => navigate("/queue")}>Production queue</button></div>{error && <div className="error-box">{error}</div>}{data?.items.length ? <div className="review-queue-list">{data.items.map((item) => <article key={item.id}><div className="review-marker"><span>{String(item.chapter).padStart(4, "0")}</span><i /></div><div><span className="eyebrow">{item.story} · {pretty(item.currentStage ?? "pipeline")}</span><h3>Chapter {item.chapter} · {pretty(item.errorCategory ?? item.status)}</h3><p>{item.lastError ?? "Manual review was requested for this chapter."}</p><small>{item.attemptCount} of {item.maxAttempts} attempts{item.lastAttemptAt ? ` · last tried ${new Date(item.lastAttemptAt).toLocaleString()}` : ""}</small><b>{recommend(item.errorCategory)}</b></div><div className="review-actions"><button onClick={() => navigate(`/stories/${item.story}/chapters/${item.chapter}`)}>Open chapter</button><button onClick={() => void act(item, "retry")}>Retry chapter</button>{retryStage(item.currentStage) && <button onClick={() => void act(item, "retry", { stage: retryStage(item.currentStage) })}>Retry {pretty(item.currentStage!)}</button>}<button onClick={() => void act(item, "resolve")}>Verify resolved</button>{["subtitles", "scenePlanning", "artwork", "video"].includes(item.currentStage ?? "") && <button className="danger" onClick={() => void act(item, "skip")}>Skip explicitly</button>}</div></article>)}</div> : <div className="queue-invitation wide"><span>✓</span><h3>No chapters need intervention</h3><p>Provider retries and quality checks are clear.</p></div>}{data && data.pages > 1 && <div className="pagination"><button disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page} / {data.pages}</span><button disabled={page === data.pages} onClick={() => setPage(page + 1)}>Next</button></div>}</section>;
}

function retryStage(stage?: string) { return ({ storyBible: "story-bible", audioMastering: "audio", scenePlanning: "scenes", videoExport: "video-export" } as Record<string, string>)[stage ?? ""] ?? (["ingestion", "translation", "narration", "qa", "continuity", "tts", "alignment", "subtitles", "artwork", "video", "audiobook"].includes(stage ?? "") ? stage : undefined); }
function recommend(category?: string) { return category === "configuration" ? "Fix configuration, then retry and resume the job." : category === "content_qa" ? "Review narration and QA evidence before retrying." : category === "rate_limit" ? "The provider cooldown will expire automatically." : "Inspect the source and chapter artifacts before retrying."; }
function message(value: unknown) { return value instanceof Error ? value.message : String(value); }
