import { VisualCostPreview, VisualWorkflowJob, useVisualWorkflowJob } from "./VisualWorkflowJob.js";
import { planReferenceSheets, startReferenceSheets, type ReferenceBatchPlan, type ReferenceSelection } from "./visual-workflow.js";
import { approveVisualReference } from "./api.js";
import { useEffect, useState } from "react";
import { getVisualCatalog, referenceUrl, type VisualCatalogEntity } from "./visual-workflow.js";
export function VisualReviewQueue({ slug, onReview, revision }: { slug: string; revision?: number; onReview: (entity: VisualCatalogEntity) => void }) {
  const [selected, setSelected] = useState<Record<string, string>>({}); const [approving, setApproving] = useState(false); const [progress, setProgress] = useState("");
  const [generationSelection, setGenerationSelection] = useState<Record<string, ReferenceSelection>>({}); const [plan, setPlan] = useState<ReferenceBatchPlan>(); const [planning, setPlanning] = useState(false); const [force, setForce] = useState(false);
  const [entities, setEntities] = useState<VisualCatalogEntity[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [query, setQuery] = useState("");
  const refresh = async () => { setLoading(true); setError(""); try { setEntities(await getVisualCatalog(slug)); } catch (error) { setError(String(error)); } finally { setLoading(false); } };
  const work = useVisualWorkflowJob(slug, "references", () => { setPlan(undefined); void refresh(); });
  const inspectGeneration = async (selection = Object.values(generationSelection), fresh = force) => { setPlanning(true); setError(""); try { setPlan(await planReferenceSheets(slug, selection, fresh)); } catch (error) { setError(String(error)); } finally { setPlanning(false); } };
  const generate = async () => { if (!plan) return; setPlanning(true); setError(""); try { work.track(await startReferenceSheets(slug, Object.values(generationSelection), plan)); setPlan(undefined); } catch (error) { setError(String(error)); } finally { setPlanning(false); } };
  useEffect(() => { void refresh(); }, [slug, revision]);
  const pending = entities.filter(entity => entity.tasks.length && `${entity.name} ${entity.tasks.map(task => task.label).join(" ")}`.toLowerCase().includes(query.toLowerCase()));
  const approveSelected = async () => {
    setApproving(true); const failures: string[] = []; const items = entities.flatMap(entity => entity.tasks.map(task => ({ entity, task }))).filter(({ task }) => selected[task.key]);
    for (let index = 0; index < items.length; index++) { const { entity, task } = items[index]!; setProgress(`Approving ${index + 1} of ${items.length}: ${entity.name}`); try { await approveVisualReference(slug, entity.id, selected[task.key]!, true, task.kind === "form" ? task.scopeId : undefined, task.kind === "era" ? task.scopeId : undefined); setSelected(current => { const next = { ...current }; delete next[task.key]; return next; }); } catch (error) { failures.push(`${entity.name}: ${String(error)}`); } }
    await refresh(); setError(failures.join("\n")); setApproving(false); setProgress(`Approval finished: ${items.length - failures.length} succeeded, ${failures.length} need attention.`);
  };
  return <details className="visual-review-queue"><summary>Visual review queue · {entities.reduce((sum, entity) => sum + entity.tasks.length, 0)} items</summary><p>Review detected eras, creature forms, missing references, and conflicts together. Designs only become active through approval.</p><input aria-label="Search visual review" placeholder="Search entities or designs" value={query} onChange={event => setQuery(event.target.value)} /><button type="button" disabled={loading} onClick={() => void refresh()}>{loading ? "Refreshing…" : "Refresh review queue"}</button>{error && <p role="alert">{error}</p>}
    <div className="visual-reference-batch"><label><input type="checkbox" disabled={work.active} checked={force} onChange={event => { setForce(event.target.checked); setPlan(undefined); }} />Generate fresh sheets even when references exist</label><button type="button" disabled={work.active || planning || approving || !Object.keys(generationSelection).length} onClick={() => void inspectGeneration()}>{planning ? "Preparing…" : "Preview selected reference generation"}</button>
    {plan && <div><VisualCostPreview plan={plan} /><ul>{plan.entries.map(entry => <li key={entry.key}>{entry.label} · {entry.blockedReason ?? (entry.reuseReferenceId ? "Existing sheet will be reused" : entry.identityReason ?? "New candidate sheet")}</li>)}</ul><button type="button" disabled={work.active || planning || !plan.imageCount} onClick={() => void generate()}>Generate {plan.imageCount} candidate sheets</button><button type="button" onClick={() => setPlan(undefined)}>Close plan</button></div>}
    <VisualWorkflowJob job={work.job} error={work.error} onRetry={job => { const completed = new Set((job.result?.outcomes ?? job.progress?.outcomes ?? []).filter((item: { status: string }) => ["generated", "reused"].includes(item.status)).map((item: { key: string }) => item.key)); const selection = ((job.payload?.selection ?? []) as ReferenceSelection[]).filter(item => !completed.has(`${item.entityId}:${item.kind}:${item.scopeId ?? "base"}`)); setGenerationSelection(Object.fromEntries(selection.map(item => [`${item.entityId}:${item.kind}:${item.scopeId ?? "base"}`, item]))); setForce(!!job.payload?.force); if (selection.length) void inspectGeneration(selection, !!job.payload?.force); else setProgress("All selected sheets have been completed."); }} /></div>
    <p role="status">{progress}</p><button type="button" disabled={approving || work.active || !Object.keys(selected).length} onClick={() => void approveSelected()}>Approve selected reviewed sheets and designs ({Object.keys(selected).length})</button>
    {pending.map(entity => <div key={entity.id}><strong>{entity.name}</strong><ul>{entity.tasks.map(task => { const scope = task.kind === "era" ? entity.profile?.appearanceEras?.find(era => era.id === task.scopeId) : task.kind === "form" ? entity.profile?.creatureForms?.find(form => form.id === task.scopeId) : undefined; const assigned = new Set([...(entity.profile?.appearanceEras ?? []).flatMap(era => era.referenceIds), ...(entity.profile?.creatureForms ?? []).flatMap(form => form.referenceIds)]); const refs = entity.profile?.references.filter(ref => scope ? scope.referenceIds.includes(ref.id) : task.kind !== "conflict" && !assigned.has(ref.id)) ?? []; return <li key={task.key}>{task.kind !== "conflict" && <label><input type="checkbox" disabled={work.active || approving || task.stale} checked={!!generationSelection[`${entity.id}:${task.kind === "reference" ? "profile" : task.kind}:${task.scopeId ?? "base"}`]} onChange={event => { const selection: ReferenceSelection = { entityId: entity.id, kind: task.kind === "reference" ? "profile" : task.kind as ReferenceSelection["kind"], scopeId: task.scopeId }; const key = `${entity.id}:${selection.kind}:${selection.scopeId ?? "base"}`; setGenerationSelection(current => { const next = { ...current }; if (event.target.checked) next[key] = selection; else delete next[key]; return next; }); setPlan(undefined); }} />Generate a candidate for this design</label>}<p>{task.label}{task.stale && " · source changed; re-review required"}{task.needsSheet && " · reference needed"}</p>{scope && <p>{scope.appearance || scope.visualPrompt}</p>}{refs.map(ref => <label key={ref.id}><img width="140" alt={task.label} src={referenceUrl(slug, entity.id, ref.id)} /><input type="radio" name={task.key} disabled={approving || work.active || task.stale || entity.profile?.conflicts?.some(conflict => conflict.status === "needs_review")} checked={selected[task.key] === ref.id} onChange={() => setSelected(current => ({ ...current, [task.key]: ref.id }))} />{scope ? "I reviewed this sheet and design; approve it" : "I reviewed this base sheet; approve it"}</label>)}</li>; })}</ul><button type="button" disabled={approving || work.active} onClick={() => onReview(entity)}>Review designs</button></div>)}{!loading && !error && !pending.length && <p>No visual review items match.</p>}
  </details>;
}
