import { useState } from "react";
import { getVisualImpact, planVisualRegeneration, startVisualRegeneration, sceneSelectionKey, type VisualImpact, type RegenerationPlan, type SceneSelection } from "./visual-workflow.js";
import { VisualWorkflowJob, VisualCostPreview, useVisualWorkflowJob } from "./VisualWorkflowJob.js";
export function VisualImpactPanel({ slug, entityId }: { slug: string; entityId: string }) {
  const [rows, setRows] = useState<VisualImpact[]>(); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [selected, setSelected] = useState<SceneSelection[]>([]); const [includeProtected, setIncludeProtected] = useState(false); const [plan, setPlan] = useState<RegenerationPlan>();
  const inspect = async () => { setBusy(true); setError(""); try { setRows(await getVisualImpact(slug, entityId)); } catch (error) { setError(String(error)); } finally { setBusy(false); } };
  const work = useVisualWorkflowJob(slug, `regeneration:${entityId}`, () => { setPlan(undefined); void inspect(); });
  const preview = async (selection = selected, protectedAllowed = includeProtected) => { setBusy(true); setError(""); try { setPlan(await planVisualRegeneration(slug, entityId, selection, protectedAllowed)); } catch (error) { setError(String(error)); } finally { setBusy(false); } };
  return <details className="visual-workflow-panel"><summary>Scenes affected by visual changes</summary><p>Select scenes to generate new candidates. Approved versions stay active until you approve a replacement.</p><button type="button" disabled={busy || work.active} onClick={() => void inspect()}>{busy ? "Inspecting…" : "Inspect affected scenes"}</button>{error && <p role="alert">{error}</p>}
    {rows && <><label><input type="checkbox" disabled={work.active} checked={includeProtected} onChange={event => { setIncludeProtected(event.target.checked); setPlan(undefined); if (!event.target.checked) setSelected(items => items.filter(item => !rows.find(row => sceneSelectionKey(row) === sceneSelectionKey(item))?.protected)); }} />Allow selected protected scenes to receive new candidates</label><ul>{rows.map(row => { const key = sceneSelectionKey(row); return <li key={key}><label><input type="checkbox" disabled={work.active || row.disabled || row.protected && !includeProtected} checked={selected.some(item => sceneSelectionKey(item) === key)} onChange={event => { const item = { chapter: row.chapter, summaryId: row.summaryId, sceneId: row.sceneId }; setSelected(items => event.target.checked ? [...items, item] : items.filter(item => sceneSelectionKey(item) !== key)); setPlan(undefined); }} /><a href={row.chapter ? `/stories/${slug}/scenes?chapter=${row.chapter}` : `/stories/${slug}/summaries?summary=${row.summaryId}`}>{row.source} · {row.sceneId}</a></label> · {row.protected ? "Protected artwork" : row.hasArtwork ? "Eligible for selective regeneration" : "No completed artwork"}{row.disabled && " · disabled"}<p>{row.summary}</p></li>; })}</ul><button type="button" disabled={busy || work.active || !selected.length} onClick={() => void preview()}>Preview selected regeneration</button></>}
    {plan && <div><VisualCostPreview plan={plan} /><ul>{plan.entries.map(entry => <li key={entry.key}>{entry.label} · {entry.blockedReason ?? "New candidate; previous versions retained"}</li>)}</ul><button type="button" disabled={busy || work.active || !plan.imageCount} onClick={async () => { setBusy(true); setError(""); try { work.track(await startVisualRegeneration(slug, entityId, selected, includeProtected, plan)); setPlan(undefined); } catch (error) { setError(String(error)); } finally { setBusy(false); } }}>Generate {plan.imageCount} replacement candidates</button><button type="button" onClick={() => setPlan(undefined)}>Close plan</button></div>}
    <VisualWorkflowJob job={work.job} error={work.error} onRetry={job => { const completed = new Set((job.result?.outcomes ?? job.progress?.outcomes ?? []).filter((item: { status: string }) => item.status === "generated").map((item: { key: string }) => item.key)); const remaining = ((job.payload?.selection ?? []) as SceneSelection[]).filter(item => !completed.has(sceneSelectionKey(item))); setSelected(remaining); setIncludeProtected(!!job.payload?.includeProtected); if (remaining.length) void preview(remaining, !!job.payload?.includeProtected); else setError("All selected scenes have completed candidates."); }} />{rows?.length === 0 && <p>No stored scenes use this entity.</p>}
  </details>;
}
