import React from "react";
import type { VisualAppearanceEra, VisualEntityProfile } from "./api.js";

type Props = { profile: VisualEntityProfile; onChange: (profile: VisualEntityProfile) => void; busy?: boolean; onGenerate?: (eraId: string) => void; onApprove?: (eraId: string, refId: string) => void; referenceUrl?: (refId: string) => string };

export function VisualAppearanceEras({ profile, onChange, busy, onGenerate, onApprove, referenceUrl }: Props) {
  const eras = profile.appearanceEras ?? [];
  const update = (id: string, patch: Partial<VisualAppearanceEra>) => onChange({ ...profile, appearanceEras: eras.map((era) => era.id === id ? { ...era, ...patch } : era) });
  const add = () => onChange({ ...profile, appearanceEras: [...eras, { id: crypto.randomUUID(), name: "New appearance era", startChapter: 1, status: "draft", appearance: "", visualPrompt: "", referenceIds: [] }] });
  if (!["character", "creature"].includes(profile.visualType)) return <p className="hint-text">Appearance eras are available for characters and creatures.</p>;
  return <div className="appearance-eras">
    <div className="appearance-eras-intro"><div><h4>Appearance across chapters</h4><p className="hint-text">Approved eras apply only within their chapter range when this Visual Profile is approved. The main profile remains the look outside those ranges. Scene direction still controls temporary changes.</p></div><button type="button" className="btn btn-primary" onClick={add}>Add era</button></div>
    {eras.length === 0 && <p className="hint-text">No appearance eras yet. Artwork uses the main Visual Profile.</p>}
    {eras.map((era) => <section className="appearance-era-card" key={era.id}>
      <div className="appearance-era-heading"><strong>{era.name || "Untitled era"}</strong><span className={`badge status-${era.status}`}>{era.status}</span><button type="button" className="btn btn-danger" onClick={() => onChange({ ...profile, appearanceEras: eras.filter((item) => item.id !== era.id) })}>Remove</button></div>
      <small>Era ID for flashback overrides: <code>{era.id}</code></small>
      <div className="form-grid-2col"><div><label htmlFor={`era-name-${era.id}`}>Era name</label><input id={`era-name-${era.id}`} value={era.name} onChange={(event) => update(era.id, { name: event.target.value })} /></div><div><label htmlFor={`era-status-${era.id}`}>Status</label><select id={`era-status-${era.id}`} value={era.status} onChange={(event) => update(era.id, { status: event.target.value as VisualAppearanceEra["status"] })}><option value="draft">Draft</option><option value="approved">Approved for artwork</option></select></div><div><label htmlFor={`era-start-${era.id}`}>First chapter</label><input id={`era-start-${era.id}`} type="number" min="1" step="1" value={era.startChapter} onChange={(event) => update(era.id, { startChapter: Number(event.target.value) })} /></div><div><label htmlFor={`era-end-${era.id}`}>Last chapter (blank = onward)</label><input id={`era-end-${era.id}`} type="number" min={era.startChapter} step="1" value={era.endChapter ?? ""} onChange={(event) => update(era.id, { endChapter: event.target.value ? Number(event.target.value) : undefined })} /></div></div>
      <label htmlFor={`era-appearance-${era.id}`}>Appearance for this era</label><textarea id={`era-appearance-${era.id}`} rows={3} value={era.appearance} onChange={(event) => update(era.id, { appearance: event.target.value })} placeholder="Persistent appearance after this change" />
      <label htmlFor={`era-prompt-${era.id}`}>Artwork prompt for this era</label><textarea id={`era-prompt-${era.id}`} rows={3} value={era.visualPrompt} onChange={(event) => update(era.id, { visualPrompt: event.target.value })} placeholder="Optional era-specific visual direction" />
      <label htmlFor={`era-negative-${era.id}`}>Negative prompt for this era</label><input id={`era-negative-${era.id}`} value={era.negativePrompt ?? ""} onChange={(event) => update(era.id, { negativePrompt: event.target.value })} placeholder="Optional exclusions for this era" />
      <div className="form-grid-2col">{profile.visualType === "character" ? <><div><label>Apparent age</label><input value={era.character?.apparentAge ?? ""} onChange={(event) => update(era.id, { character: { ...era.character, apparentAge: event.target.value } })} /></div><div><label>Hair color</label><input value={era.character?.hairColor ?? ""} onChange={(event) => update(era.id, { character: { ...era.character, hairColor: event.target.value } })} /></div><div><label>Hairstyle</label><input value={era.character?.hairstyle ?? ""} onChange={(event) => update(era.id, { character: { ...era.character, hairstyle: event.target.value } })} /></div><div><label>Eye color</label><input value={era.character?.eyeColor ?? ""} onChange={(event) => update(era.id, { character: { ...era.character, eyeColor: event.target.value } })} /></div><div><label>Build</label><input value={era.character?.build ?? ""} onChange={(event) => update(era.id, { character: { ...era.character, build: event.target.value } })} /></div><div><label>Outfit</label><input value={era.character?.defaultOutfit ?? ""} onChange={(event) => update(era.id, { character: { ...era.character, defaultOutfit: event.target.value } })} /></div><div><label>Scars and lasting marks</label><input value={era.character?.scars ?? ""} onChange={(event) => update(era.id, { character: { ...era.character, scars: event.target.value } })} /></div><div><label>Distinguishing features</label><input value={era.character?.distinguishingFeatures ?? ""} onChange={(event) => update(era.id, { character: { ...era.character, distinguishingFeatures: event.target.value } })} /></div></> : <><div><label>Scale</label><input value={era.creature?.scale ?? ""} onChange={(event) => update(era.id, { creature: { ...era.creature, scale: event.target.value } })} /></div><div><label>Coloration</label><input value={era.creature?.coloration ?? ""} onChange={(event) => update(era.id, { creature: { ...era.creature, coloration: event.target.value } })} /></div><div><label>Anatomy</label><input value={era.creature?.anatomy ?? ""} onChange={(event) => update(era.id, { creature: { ...era.creature, anatomy: event.target.value } })} /></div><div><label>Eyes</label><input value={era.creature?.eyes ?? ""} onChange={(event) => update(era.id, { creature: { ...era.creature, eyes: event.target.value } })} /></div><div><label>Armor or fur</label><input value={era.creature?.armorFur ?? ""} onChange={(event) => update(era.id, { creature: { ...era.creature, armorFur: event.target.value } })} /></div><div><label>Distinguishing features</label><input value={era.creature?.distinguishingFeatures ?? ""} onChange={(event) => update(era.id, { creature: { ...era.creature, distinguishingFeatures: event.target.value } })} /></div></>}</div>
      {onGenerate && <div className="era-generation-actions"><button type="button" className="btn btn-primary" disabled={busy} onClick={() => onGenerate(era.id)}>{busy ? "Working…" : "Save and generate era reference sheet"}</button><p className="hint-text">Uses this era's saved appearance and the book's artwork model. Generation adds a candidate here for review; it does not approve it automatically.</p></div>}
      {profile.references.filter(reference => era.referenceIds.includes(reference.id)).map(reference => <div className="reference-item" key={reference.id}>
        {referenceUrl && <a href={referenceUrl(reference.id)} target="_blank" rel="noopener noreferrer"><img src={referenceUrl(reference.id)} alt={`${era.name} reference sheet`} style={{ maxWidth: "100%", maxHeight: 260, objectFit: "contain" }} /></a>}
        <p>{reference.approved ? "Approved reference" : "Candidate — review before approving"}</p>
        {onApprove && (!reference.approved || era.status !== "approved") && <button type="button" className="btn btn-primary" disabled={busy} onClick={() => onApprove(era.id, reference.id)}>Approve sheet and era</button>}
      </div>)}
      <fieldset><legend>Reference images for this era</legend><p className="hint-text">Only selected approved images are supplied to artwork in this era.</p>{profile.references.filter((reference) => reference.approved).map((reference) => <label className="appearance-era-reference" key={reference.id}><input type="checkbox" checked={era.referenceIds.includes(reference.id)} onChange={(event) => update(era.id, { referenceIds: event.target.checked ? [...era.referenceIds, reference.id] : era.referenceIds.filter((id) => id !== reference.id) })} />{reference.role.replaceAll("_", " ")} · {reference.id.slice(0, 8)}</label>)}{!profile.references.some((reference) => reference.approved) && <p className="hint-text">Approve reference images in the Reference Images tab first.</p>}</fieldset>
    </section>)}
  </div>;
}
