import type { Story } from "../domain/story.js";
import type { MusicTrack } from "./types.js";

export function buildStoryMusicContext(story: Story) { return { title: story.title.slice(0, 200), description: story.description.slice(0, 700), themes: story.tags.slice(0, 8).map((tag) => tag.slice(0, 60)), desiredNarrationStyle: "Instrumental, low density, loop-friendly, with room for narration" }; }
export function suggestMusicConcepts(story: Story) { const context = buildStoryMusicContext(story); const base = context.themes.slice(0, 2).join(", ") || "cinematic fiction"; return [
  { title: `${context.title} — Atmosphere`, description: "Quiet atmospheric underscore", mood: "mysterious", genre: "ambient cinematic", instrumentation: "soft drones, low strings", energy: "low", purpose: "background_narration", prompt: `Instrumental ambient cinematic underscore for ${context.title}. Themes: ${base}. Context: ${context.description.slice(0, 180)}. Mysterious and low energy. Soft drones and low strings. No vocals, no prominent lead melody, minimal percussion, leave space for audiobook narration, loop-friendly ending.` },
  { title: `${context.title} — Resolve`, description: "Restrained heroic underscore", mood: "resolute", genre: "cinematic orchestral", instrumentation: "cello, distant horns", energy: "low", purpose: "background_narration", prompt: `Instrumental cinematic orchestral ambience for ${context.title}. Themes: ${base}. Context: ${context.description.slice(0, 180)}. Restrained and resolute. Cello and distant horns, gentle pulse. No vocals, avoid dense arrangements or sharp transients, leave space for narration, loop-friendly ending.` },
  { title: `${context.title} — Tension`, description: "Subtle suspense underscore", mood: "tense", genre: "dark ambient", instrumentation: "low pads, sparse strings", energy: "very_low", purpose: "background_narration", prompt: `Instrumental dark ambient underscore for ${context.title}. Themes: ${base}. Context: ${context.description.slice(0, 180)}. Very low energy and subtle suspense. Low pads and sparse strings. No vocals, no dominant melody, minimal transients, room for narration, loop-friendly ending.` },
  ]; }
export function rankMusicTracks(story: Story, tracks: MusicTrack[]) { const tags = new Set(story.tags.map((tag) => tag.toLowerCase())); return tracks.map((track) => ({ track, score: track.tags.reduce((sum, tag) => sum + (tags.has(tag.toLowerCase()) ? 2 : 0) + (/ambient|instrumental|narration-friendly|low-energy/i.test(tag) ? 1 : 0), 0) })).sort((a, b) => b.score - a.score || a.track.title.localeCompare(b.track.title)); }
