import { randomUUID } from "node:crypto";
import { DatabasePool } from "./database.js";
import { ClassifiedFailure, retryDelayMs } from "./failure.js";
import { DurableJobStatus, QueueEvent, QueueJob, QueuePage, QueueSubmission, QueueWorkItem, WorkItemStatus } from "./types.js";

type DbJob = Record<string, unknown>; type DbItem = Record<string, unknown>; type DbEvent = Record<string, unknown>;
export type CreateQueueJob = { story: string; input: QueueSubmission; plan: unknown; chapters: Array<{ chapter: number; providers?: string[] }> ; maxAttempts: number };

export class QueueConflictError extends Error {}
export class QueueNotFoundError extends Error {}

export class PostgresQueueRepository {
  constructor(private readonly pool: DatabasePool, private readonly retentionDays = 90) {}

  async createJob(input: CreateQueueJob): Promise<QueueJob> {
    const client = await this.pool.connect(); const id = randomUUID();
    try {
      await client.query("BEGIN");
      const result = await client.query<DbJob>(`INSERT INTO production_jobs
        (id, story_slug, chapter_from, chapter_to, profile, options, plan_summary, status, total_items)
        VALUES ($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,'queued',$8) RETURNING *`,
        [id, input.story, input.input.from, input.input.to, input.input.profile ?? null, JSON.stringify(input.input), JSON.stringify(input.plan), input.chapters.length]);
      for (let index = 0; index < input.chapters.length; index++) { const item = input.chapters[index]!; await client.query(`INSERT INTO production_work_items
        (job_id, chapter, ordinal, status, max_attempts, required_providers) VALUES ($1,$2,$3,'pending',$4,$5)`, [id, item.chapter, index + 1, input.maxAttempts, item.providers ?? []]); }
      await event(client, id, undefined, "job.queued", `Queued Chapters ${input.input.from}–${input.input.to}`, { workItems: input.chapters.length });
      await client.query("COMMIT"); return mapJob(result.rows[0]!);
    } catch (error) { await client.query("ROLLBACK"); if ((error as { code?: string }).code === "23505") throw new QueueConflictError(`Story '${input.story}' already has an active durable production job`); throw error; }
    finally { client.release(); }
  }

  async getJob(id: string): Promise<QueueJob | undefined> { const result = await this.pool.query<DbJob>("SELECT * FROM production_jobs WHERE id=$1", [id]); return result.rows[0] ? mapJob(result.rows[0]) : undefined; }
  async listJobs(input: { page: number; pageSize: number; status?: DurableJobStatus; story?: string }): Promise<QueuePage<QueueJob>> {
    const values: unknown[] = []; const clauses: string[] = [];
    if (input.status) { values.push(input.status); clauses.push(`status=$${values.length}`); }
    if (input.story) { values.push(input.story); clauses.push(`story_slug=$${values.length}`); }
    const where = clauses.length ? `WHERE ${clauses.join(" AND ")}` : ""; const count = await this.pool.query<{ count: string }>(`SELECT count(*)::text count FROM production_jobs ${where}`, values);
    values.push(input.pageSize, (input.page - 1) * input.pageSize); const result = await this.pool.query<DbJob>(`SELECT * FROM production_jobs ${where} ORDER BY created_at DESC,id DESC LIMIT $${values.length - 1} OFFSET $${values.length}`, values);
    return page(result.rows.map(mapJob), Number(count.rows[0]?.count ?? 0), input.page, input.pageSize);
  }
  async summary() { const result = await this.pool.query<{ status: string; count: string }>("SELECT status,count(*)::text count FROM production_jobs GROUP BY status"); const jobs = Object.fromEntries(result.rows.map((row) => [row.status, Number(row.count)])); const work = await this.pool.query<{ status: string; count: string }>("SELECT status,count(*)::text count FROM production_work_items GROUP BY status"); return { jobs, workItems: Object.fromEntries(work.rows.map((row) => [row.status, Number(row.count)])) }; }
  async listWorkItems(jobId: string, input: { page: number; pageSize: number }): Promise<QueuePage<QueueWorkItem>> { const count = await this.pool.query<{ count: string }>("SELECT count(*)::text count FROM production_work_items WHERE job_id=$1", [jobId]); const result = await this.pool.query<DbItem>(`SELECT wi.*,j.story_slug FROM production_work_items wi JOIN production_jobs j ON j.id=wi.job_id WHERE wi.job_id=$1 ORDER BY wi.ordinal LIMIT $2 OFFSET $3`, [jobId,input.pageSize,(input.page-1)*input.pageSize]); return page(result.rows.map(mapItem), Number(count.rows[0]?.count ?? 0), input.page, input.pageSize); }
  async listNeedsReview(input: { page: number; pageSize: number }): Promise<QueuePage<QueueWorkItem>> { const count = await this.pool.query<{ count: string }>("SELECT count(*)::text count FROM production_work_items WHERE status IN ('needs_review','failed')"); const result = await this.pool.query<DbItem>(`SELECT wi.*,j.story_slug FROM production_work_items wi JOIN production_jobs j ON j.id=wi.job_id WHERE wi.status IN ('needs_review','failed') ORDER BY wi.updated_at DESC LIMIT $1 OFFSET $2`, [input.pageSize,(input.page-1)*input.pageSize]); return page(result.rows.map(mapItem), Number(count.rows[0]?.count ?? 0), input.page, input.pageSize); }
  async listEvents(jobId: string, afterId = 0, limit = 100): Promise<QueueEvent[]> { const result = await this.pool.query<DbEvent>("SELECT * FROM production_events WHERE job_id=$1 AND id>$2 ORDER BY id LIMIT $3", [jobId,afterId,limit]); return result.rows.map(mapEvent); }
  async listRecentEvents(jobId:string,limit=100):Promise<QueueEvent[]>{const result=await this.pool.query<DbEvent>("SELECT * FROM production_events WHERE job_id=$1 ORDER BY id DESC LIMIT $2",[jobId,limit]);return result.rows.reverse().map(mapEvent);}

  async recoverExpired(now = new Date()) {
    const client = await this.pool.connect(); try { await client.query("BEGIN"); const expired = await client.query<{ id: string; job_id: string; chapter: number }>(`UPDATE production_work_items SET status='pending',lease_owner=NULL,lease_expires_at=NULL,current_stage=NULL,updated_at=now() WHERE status='running' AND lease_expires_at < $1 RETURNING id::text,job_id::text,chapter`, [now]);
      for (const item of expired.rows) await event(client,item.job_id,item.id,"chapter.recovered",`Recovered Chapter ${item.chapter} after an expired worker lease`,{});
      await client.query(`UPDATE production_jobs j SET status='queued',current_chapter=NULL,current_stage=NULL,updated_at=now() WHERE status='running' AND (finalization_expires_at IS NULL OR finalization_expires_at < $1) AND NOT EXISTS (SELECT 1 FROM production_work_items wi WHERE wi.job_id=j.id AND wi.status='running')`,[now]);
      await client.query("UPDATE production_jobs SET finalization_owner=NULL,finalization_expires_at=NULL,status='queued',current_stage=NULL,updated_at=now() WHERE finalized_at IS NULL AND finalization_expires_at < $1",[now]);
      await client.query("COMMIT"); return expired.rowCount ?? 0;
    } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); }
  }

  async claimFinalization(workerId:string,leaseMs:number,now=new Date()):Promise<QueueJob|undefined>{const client=await this.pool.connect();try{await client.query("BEGIN");const result=await client.query<DbJob>(`SELECT j.* FROM production_jobs j WHERE j.finalized_at IS NULL AND j.status IN ('queued','running') AND NOT j.pause_requested AND NOT j.cancel_requested AND (j.finalization_expires_at IS NULL OR j.finalization_expires_at<$1) AND NOT EXISTS(SELECT 1 FROM production_work_items wi WHERE wi.job_id=j.id AND wi.status NOT IN ('completed','warning','skipped')) ORDER BY j.created_at FOR UPDATE OF j SKIP LOCKED LIMIT 1`,[now]);if(!result.rows[0]){await client.query("COMMIT");return undefined;}const expires=new Date(now.getTime()+leaseMs);const updated=await client.query<DbJob>("UPDATE production_jobs SET status='running',current_chapter=NULL,current_stage='exports',finalization_owner=$2,finalization_expires_at=$3,updated_at=now() WHERE id=$1 RETURNING *",[result.rows[0].id,workerId,expires]);await event(client,String(result.rows[0].id),undefined,"job.finalizing","Building final outputs",{workerId});await client.query("COMMIT");return mapJob(updated.rows[0]!);}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
  async completeFinalization(jobId:string,warning?:string){const result=await this.pool.query<DbJob>(`UPDATE production_jobs SET status=CASE WHEN warning_items>0 OR $2::text IS NOT NULL THEN 'completed_with_warnings' ELSE 'completed' END,error_summary=$2,finalized_at=now(),completed_at=now(),finalization_owner=NULL,finalization_expires_at=NULL,current_stage=NULL,updated_at=now() WHERE id=$1 RETURNING *`,[jobId,warning??null]);if(!result.rows[0])throw new QueueNotFoundError("Queue job was not found");await this.addEvent(jobId,"job.completed",warning?"Job completed with warnings":"Job completed",warning?{warning}:{});return mapJob(result.rows[0]);}
  async failFinalization(jobId:string,failure:ClassifiedFailure){const status=failure.category==="configuration"?"paused":failure.category==="content_qa"?"needs_review":"failed";await this.pool.query(`UPDATE production_jobs SET status=$2,error_summary=$3,finalization_owner=NULL,finalization_expires_at=NULL,current_stage=NULL,updated_at=now(),completed_at=CASE WHEN $2='failed' THEN now() ELSE NULL END WHERE id=$1`,[jobId,status,failure.message]);await this.addEvent(jobId,"job.finalization_failed","Final output assembly failed",{category:failure.category,recommendedAction:failure.recommendedAction});}

  async claimNext(workerId: string, leaseMs: number, now = new Date()): Promise<QueueWorkItem | undefined> {
    const client = await this.pool.connect(); try { await client.query("BEGIN");
      await client.query(`UPDATE production_jobs SET status='paused',updated_at=now(),current_chapter=NULL,current_stage=NULL WHERE pause_requested AND status IN ('queued','running') AND NOT EXISTS (SELECT 1 FROM production_work_items wi WHERE wi.job_id=production_jobs.id AND wi.status='running')`);
      await client.query(`UPDATE production_work_items wi SET status='skipped',completed_at=now(),updated_at=now() FROM production_jobs j WHERE wi.job_id=j.id AND j.cancel_requested AND wi.status IN ('pending','retry_wait')`);
      await client.query(`UPDATE production_jobs SET status='cancelled',completed_at=now(),updated_at=now(),current_chapter=NULL,current_stage=NULL WHERE cancel_requested AND status NOT IN ('cancelled','completed','completed_with_warnings','failed') AND NOT EXISTS (SELECT 1 FROM production_work_items wi WHERE wi.job_id=production_jobs.id AND wi.status='running')`);
      const result = await client.query<DbItem>(`SELECT wi.*,j.story_slug FROM production_work_items wi JOIN production_jobs j ON j.id=wi.job_id
        WHERE j.status IN ('queued','running') AND NOT j.pause_requested AND NOT j.cancel_requested
          AND wi.status IN ('pending','retry_wait') AND (wi.next_retry_at IS NULL OR wi.next_retry_at <= $1)
          AND NOT EXISTS (SELECT 1 FROM production_work_items earlier WHERE earlier.job_id=wi.job_id AND earlier.ordinal<wi.ordinal AND earlier.status NOT IN ('completed','warning','skipped'))
          AND NOT EXISTS (SELECT 1 FROM production_work_items active WHERE active.job_id=wi.job_id AND active.status='running')
          AND NOT EXISTS (SELECT 1 FROM provider_cooldowns pc WHERE pc.provider=ANY(wi.required_providers) AND pc.cooldown_until>$1)
        ORDER BY j.created_at,wi.ordinal FOR UPDATE OF wi SKIP LOCKED LIMIT 1`, [now]);
      if (!result.rows[0]) { await client.query("COMMIT"); return undefined; }
      const id = String(result.rows[0].id); const lease = new Date(now.getTime()+leaseMs); const claimed = await client.query<DbItem>(`UPDATE production_work_items SET status='running',attempt_count=attempt_count+1,last_attempt_at=$2,started_at=COALESCE(started_at,$2),lease_owner=$3,lease_expires_at=$4,updated_at=now() WHERE id=$1 RETURNING *`, [id,now,workerId,lease]);
      const item = { ...claimed.rows[0], story_slug: result.rows[0].story_slug } as DbItem; await client.query(`UPDATE production_jobs SET status='running',started_at=COALESCE(started_at,$2),current_chapter=$3,current_stage='reconciling',updated_at=now() WHERE id=$1`, [item.job_id,now,item.chapter]);
      await event(client,String(item.job_id),id,"chapter.claimed",`Worker claimed Chapter ${item.chapter}`,{workerId,attempt:Number(item.attempt_count)}); await client.query("COMMIT"); return mapItem(item);
    } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); }
  }

  async heartbeat(itemId: string, workerId: string, stage: string, leaseMs: number) { const result = await this.pool.query(`UPDATE production_work_items SET current_stage=$3,lease_expires_at=now()+($4::text || ' milliseconds')::interval,updated_at=now() WHERE id=$1 AND lease_owner=$2 AND status='running' RETURNING job_id`, [itemId,workerId,stage,leaseMs]); if (!result.rowCount) throw new Error("Work item lease was lost"); await this.pool.query("UPDATE production_jobs SET current_stage=$2,updated_at=now() WHERE id=$1", [result.rows[0].job_id,stage]); }
  async heartbeatFinalization(jobId:string,workerId:string,leaseMs:number){const result=await this.pool.query("UPDATE production_jobs SET finalization_expires_at=now()+($3::text || ' milliseconds')::interval,updated_at=now() WHERE id=$1 AND finalization_owner=$2 AND finalized_at IS NULL",[jobId,workerId,leaseMs]);if(!result.rowCount)throw new Error("Finalization lease was lost");}

  async completeItem(item: QueueWorkItem, result: { reused: boolean; qaStatus?: "pass"|"warn"|"fail" }) { const status: WorkItemStatus = result.qaStatus === "warn" ? "warning" : result.qaStatus === "fail" ? "needs_review" : "completed"; await this.finishItem(item,status,{reused:result.reused,qaStatus:result.qaStatus,eventType:status === "needs_review" ? "chapter.needs_review" : "chapter.completed",message:`Chapter ${item.chapter} ${result.reused ? "reused valid artifacts" : status === "warning" ? "completed with warnings" : "completed"}`}); }
  async failItem(item: QueueWorkItem, failure: ClassifiedFailure, now = new Date()) {
    if (failure.retryable && item.attemptCount < item.maxAttempts) { const delay=retryDelayMs(item.attemptCount,failure.retryAfterMs); const next=new Date(now.getTime()+delay); const client=await this.pool.connect(); try { await client.query("BEGIN"); await client.query(`UPDATE production_work_items SET status='retry_wait',last_error=$2,error_category=$3,next_retry_at=$4,lease_owner=NULL,lease_expires_at=NULL,updated_at=now() WHERE id=$1`,[item.id,failure.message,failure.category,next]); if(failure.provider) await client.query(`INSERT INTO provider_cooldowns(provider,cooldown_until,reason) VALUES($1,$2,$3) ON CONFLICT(provider) DO UPDATE SET cooldown_until=GREATEST(provider_cooldowns.cooldown_until,EXCLUDED.cooldown_until),reason=EXCLUDED.reason,updated_at=now()`,[failure.provider,next,failure.message.slice(0,1000)]); await event(client,item.jobId,item.id,"chapter.retry_scheduled",`Chapter ${item.chapter} will retry`,{category:failure.category,nextRetryAt:next.toISOString(),attempt:item.attemptCount}); await client.query("UPDATE production_jobs SET status='queued',current_chapter=NULL,current_stage=NULL,error_summary=$2,updated_at=now() WHERE id=$1",[item.jobId,failure.message]); await client.query("COMMIT"); } catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();} return; }
    const status: WorkItemStatus = failure.category === "content_qa" || failure.category === "configuration" || failure.retryable ? "needs_review" : "failed"; await this.finishItem(item,status,{failure,eventType:status === "needs_review" ? "chapter.needs_review" : "chapter.failed",message:`Chapter ${item.chapter} ${status === "needs_review" ? "needs review" : "failed"}`}); if(failure.category==="configuration")await this.pool.query("UPDATE production_jobs SET status='paused',pause_requested=true,error_summary=$2,updated_at=now() WHERE id=$1",[item.jobId,failure.message]);
  }

  async requestPause(id:string){return this.control(id,"pause");} async resume(id:string){ const result=await this.pool.query(`UPDATE production_jobs SET pause_requested=false,status=CASE WHEN status IN ('paused','needs_review') THEN 'queued' ELSE status END,completed_at=NULL,updated_at=now() WHERE id=$1 AND status NOT IN ('completed','completed_with_warnings','failed','cancelled') RETURNING *`,[id]); if(!result.rows[0]) throw new QueueNotFoundError("Active queue job was not found"); await this.addEvent(id,"job.resumed","Job resumed"); return mapJob(result.rows[0]); }
  async requestCancel(id:string){return this.control(id,"cancel");}
  async retryItem(id:string,stage?:string){ const result=await this.pool.query<DbItem>(`UPDATE production_work_items SET status='pending',current_stage=$2,last_error=NULL,error_category=NULL,next_retry_at=NULL,completed_at=NULL,lease_owner=NULL,lease_expires_at=NULL,updated_at=now() WHERE id=$1 AND status IN ('failed','needs_review','warning') RETURNING *`,[id,stage??null]); if(!result.rows[0]) throw new QueueNotFoundError("Review item was not found or is not retryable"); await this.pool.query("UPDATE production_jobs SET status='queued',pause_requested=false,completed_at=NULL,updated_at=now() WHERE id=$1",[result.rows[0].job_id]); await this.addEvent(String(result.rows[0].job_id),"chapter.retry_requested",`Chapter ${result.rows[0].chapter} queued for retry`,{stage}); return true; }
  async resolveItem(id:string,skip=false){ const row=await this.pool.query<DbItem>(`UPDATE production_work_items SET status=$2,completed_at=CASE WHEN $3::boolean THEN now() ELSE NULL END,last_error=NULL,error_category=NULL,next_retry_at=NULL,updated_at=now() WHERE id=$1 AND status IN ('failed','needs_review','warning') AND (NOT $3::boolean OR current_stage IN ('subtitles','scenePlanning','artwork','video')) RETURNING job_id,chapter`,[id,skip?"skipped":"pending",skip]); if(!row.rows[0]) throw new QueueNotFoundError(skip?"This chapter cannot be skipped safely because it may affect chronological story context":"Review item was not found"); await this.addEvent(String(row.rows[0].job_id),skip?"chapter.skipped":"chapter.resolved",`Chapter ${row.rows[0].chapter} ${skip?"skipped by user":"marked resolved and queued for artifact verification"}`); if(!skip)await this.pool.query("UPDATE production_jobs SET status='queued',pause_requested=false,completed_at=NULL,updated_at=now() WHERE id=$1",[row.rows[0].job_id]); await this.recalculate(String(row.rows[0].job_id)); return true; }
  async addEvent(jobId:string,type:string,message:string,data:Record<string,unknown>={}){await event(this.pool,jobId,undefined,type,message,data);}
  async pruneEvents(){return (await this.pool.query(`DELETE FROM production_events WHERE created_at < now()-($1::text || ' days')::interval`,[this.retentionDays])).rowCount??0;}
  async setCooldown(provider:string,until:Date,reason?:string){await this.pool.query(`INSERT INTO provider_cooldowns(provider,cooldown_until,reason) VALUES($1,$2,$3) ON CONFLICT(provider) DO UPDATE SET cooldown_until=GREATEST(provider_cooldowns.cooldown_until,EXCLUDED.cooldown_until),reason=EXCLUDED.reason,updated_at=now()`,[provider,until,reason??null]);}

  private async control(id:string,kind:"pause"|"cancel"){const column=kind==="pause"?"pause_requested":"cancel_requested";const result=await this.pool.query<DbJob>(`UPDATE production_jobs SET ${column}=true,updated_at=now() WHERE id=$1 AND status NOT IN ('completed','completed_with_warnings','failed','cancelled') RETURNING *`,[id]);if(!result.rows[0])throw new QueueNotFoundError("Active queue job was not found");await this.addEvent(id,`job.${kind}_requested`,`${kind==="pause"?"Pause":"Cancel"} requested`);return mapJob(result.rows[0]);}
  private async finishItem(item:QueueWorkItem,status:WorkItemStatus,options:{reused?:boolean;qaStatus?:string;failure?:ClassifiedFailure;eventType:string;message:string}){const client=await this.pool.connect();try{await client.query("BEGIN");await client.query(`UPDATE production_work_items SET status=$2,reused=$3,qa_status=$4,last_error=$5,error_category=$6,completed_at=now(),next_retry_at=NULL,lease_owner=NULL,lease_expires_at=NULL,updated_at=now() WHERE id=$1`,[item.id,status,options.reused??false,options.qaStatus??null,options.failure?.message??null,options.failure?.category??null]);if(options.failure)await client.query("UPDATE production_jobs SET error_summary=$2,updated_at=now() WHERE id=$1",[item.jobId,options.failure.message]);await event(client,item.jobId,item.id,options.eventType,options.message,options.failure?{category:options.failure.category,recommendedAction:options.failure.recommendedAction}:{});await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}await this.recalculate(item.jobId);}
  private async recalculate(jobId:string){const client=await this.pool.connect();try{await client.query("BEGIN");const counts=await client.query<Record<string,string>>(`SELECT count(*)::text total,count(*) FILTER(WHERE status IN ('completed','skipped'))::text completed,count(*) FILTER(WHERE status='warning')::text warnings,count(*) FILTER(WHERE status='needs_review')::text reviews,count(*) FILTER(WHERE status='failed')::text failures,count(*) FILTER(WHERE status IN ('pending','running','retry_wait'))::text remaining FROM production_work_items WHERE job_id=$1`,[jobId]);const c=counts.rows[0]!;const remaining=Number(c.remaining);const reviews=Number(c.reviews);const failures=Number(c.failures);const status=remaining?"running":reviews?"needs_review":failures?"failed":"queued";await client.query(`UPDATE production_jobs SET total_items=$2,completed_items=$3,warning_items=$4,review_items=$5,failed_items=$6,status=CASE WHEN cancel_requested THEN 'cancelled' WHEN pause_requested THEN 'paused' ELSE $8 END,current_chapter=CASE WHEN $7::int=0 THEN NULL ELSE current_chapter END,current_stage=CASE WHEN $7::int=0 THEN NULL ELSE current_stage END,completed_at=CASE WHEN cancel_requested OR ($7::int=0 AND ($5::int>0 OR $6::int>0)) THEN now() ELSE NULL END,updated_at=now() WHERE id=$1`,[jobId,Number(c.total),Number(c.completed),Number(c.warnings),reviews,failures,remaining,status]);await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
}

async function event(client:{query:(sql:string,values?:unknown[])=>Promise<unknown>},jobId:string,workItemId:string|undefined,type:string,message:string,data:Record<string,unknown>){await client.query("INSERT INTO production_events(job_id,work_item_id,event_type,message,data) VALUES($1,$2,$3,$4,$5::jsonb)",[jobId,workItemId??null,type,message.slice(0,2000),JSON.stringify(data)]);}
function page<T>(items:T[],total:number,pageNumber:number,pageSize:number):QueuePage<T>{return{items,page:pageNumber,pageSize,total,pages:Math.ceil(total/pageSize)}}
function iso(value:unknown){return value instanceof Date?value.toISOString():typeof value==="string"?new Date(value).toISOString():undefined;}
function mapJob(row:DbJob):QueueJob{return{id:String(row.id),story:String(row.story_slug),from:Number(row.chapter_from),to:Number(row.chapter_to),profile:row.profile?String(row.profile):undefined,options:row.options as QueueSubmission,plan:row.plan_summary,status:row.status as DurableJobStatus,pauseRequested:Boolean(row.pause_requested),cancelRequested:Boolean(row.cancel_requested),currentChapter:row.current_chapter?Number(row.current_chapter):undefined,currentStage:row.current_stage?String(row.current_stage):undefined,totalItems:Number(row.total_items),completedItems:Number(row.completed_items),warningItems:Number(row.warning_items),reviewItems:Number(row.review_items),failedItems:Number(row.failed_items),errorSummary:row.error_summary?String(row.error_summary):undefined,createdAt:iso(row.created_at)!,startedAt:iso(row.started_at),updatedAt:iso(row.updated_at)!,completedAt:iso(row.completed_at)}}
function mapItem(row:DbItem):QueueWorkItem{return{id:String(row.id),jobId:String(row.job_id),story:String(row.story_slug??""),chapter:Number(row.chapter),ordinal:Number(row.ordinal),status:row.status as WorkItemStatus,currentStage:row.current_stage?String(row.current_stage):undefined,attemptCount:Number(row.attempt_count),maxAttempts:Number(row.max_attempts),lastError:row.last_error?String(row.last_error):undefined,errorCategory:row.error_category as QueueWorkItem["errorCategory"],nextRetryAt:iso(row.next_retry_at),lastAttemptAt:iso(row.last_attempt_at),startedAt:iso(row.started_at),completedAt:iso(row.completed_at),reused:Boolean(row.reused),qaStatus:row.qa_status as QueueWorkItem["qaStatus"],requiredProviders:Array.isArray(row.required_providers)?row.required_providers.map(String):[],leaseOwner:row.lease_owner?String(row.lease_owner):undefined,leaseExpiresAt:iso(row.lease_expires_at)}}
function mapEvent(row:DbEvent):QueueEvent{return{id:String(row.id),jobId:String(row.job_id),workItemId:row.work_item_id?String(row.work_item_id):undefined,type:String(row.event_type),message:String(row.message),data:(row.data??{}) as Record<string,unknown>,createdAt:iso(row.created_at)!}}
