import { createHash } from "node:crypto";
import { createReadStream } from "node:fs";
import { readFile, rm } from "node:fs/promises";
import { AlignmentArtifact, alignmentArtifactSchema } from "../alignment/types.js";
import { Chapter, StageState, chapterSchema } from "../domain/chapter.js";
import { Story } from "../domain/story.js";
import { SubtitleError } from "../pipeline/errors.js";
import { atomicWrite, atomicWriteJson } from "../storage/atomic-write.js";
import { storyPaths } from "../storage/paths.js";
import { readJsonIfExists } from "../storage/story-files.js";
import { fingerprint } from "../utils/hash.js";
import { generateAlignedSubtitleTiming } from "./aligned-timing.js";
import { toSrt } from "./srt.js";
import { generateSubtitleTiming, SUBTITLE_GENERATOR_VERSION } from "./timing.js";
import { SubtitleCue, SubtitleDocument, subtitleDocumentSchema } from "./types.js";
import { toVtt } from "./vtt.js";

export type SubtitleEvent = { status: "started" | "completed" | "reused"; chapter: number; state: StageState };
export async function generateStoredSubtitles(options: { root: string; story: Story; chapter: number; force?: boolean; forceEstimated?: boolean; onEvent?: (event: SubtitleEvent) => void }) {
  const paths = storyPaths(options.root, options.story.slug, options.chapter); const raw = await readJsonIfExists<Chapter>(paths.chapterMeta); if (!raw) throw new SubtitleError(`Chapter ${options.chapter} has no pipeline metadata`);
  const chapter = chapterSchema.parse(raw); if (chapter.stages.audioMastering.status !== "complete" || !chapter.audio) throw new SubtitleError(`Chapter ${options.chapter} audio is not mastered`);
  const manualRaw = await readJsonIfExists<SubtitleDocument>(paths.subtitlesManual); const manual = manualRaw ? subtitleDocumentSchema.safeParse(manualRaw) : undefined;
  if (manual?.success && await outputsFingerprint(paths.subtitlesSrt, paths.subtitlesVtt, paths.subtitlesDocument)) { chapter.subtitle = { cueCount: manual.data.cues.length, durationSeconds: manual.data.durationSeconds, timingMode: manual.data.timingMode, engine: "manual", manual: true }; if (chapter.stages.subtitles.provider !== "manual") { chapter.stages.subtitles = { ...chapter.stages.subtitles, status: "complete", provider: "manual", model: "studio-editor" }; await persist(paths.chapterMeta, chapter); } options.onEvent?.({ status: "reused", chapter: options.chapter, state: chapter.stages.subtitles }); return { chapter, document: manual.data, reused: true, protected: true }; }
  const narration = await readFile(paths.narration, "utf8").catch(() => { throw new SubtitleError(`Chapter ${options.chapter} narration is missing`); }); const masteredAudioFingerprint = await fileFingerprint(paths.audio).catch(() => { throw new SubtitleError(`Chapter ${options.chapter} mastered audio is missing`); });
  const alignmentRaw = options.forceEstimated ? undefined : await readJsonIfExists<AlignmentArtifact>(paths.alignment); const alignment = alignmentRaw ? alignmentArtifactSchema.safeParse(alignmentRaw) : undefined; const aligned = alignment?.success && alignment.data.mode === "aligned";
  const inputFingerprint = subtitleFingerprint(fingerprint(narration), masteredAudioFingerprint, options.story.subtitles, aligned ? alignment.data.inputFingerprint : "estimated"); const outputFingerprint = await outputsFingerprint(paths.subtitlesSrt, paths.subtitlesVtt, paths.subtitlesDocument);
  if (!options.force && chapter.stages.subtitles.status === "complete" && chapter.stages.subtitles.fingerprint === inputFingerprint && chapter.stages.subtitles.outputFingerprint === outputFingerprint && chapter.subtitle) { const document = subtitleDocumentSchema.parse(await readJsonIfExists(paths.subtitlesDocument)); options.onEvent?.({ status: "reused", chapter: options.chapter, state: chapter.stages.subtitles }); return { chapter, document, reused: true, protected: false }; }
  const started = Date.now(); chapter.subtitle = undefined; chapter.video = undefined; chapter.stages.video = { status: "pending" }; chapter.stages.subtitles = { status: "running", provider: "local", model: aligned ? "aligned-subtitles-v1" : SUBTITLE_GENERATOR_VERSION, fingerprint: inputFingerprint, startedAt: new Date().toISOString() }; await persist(paths.chapterMeta, chapter); options.onEvent?.({ status: "started", chapter: options.chapter, state: chapter.stages.subtitles });
  try {
    const document = aligned ? generateAlignedSubtitleTiming(alignment.data.words, chapter.audio.durationSeconds, options.story.subtitles) : generateSubtitleTiming(narration, chapter.audio.durationSeconds, options.story.subtitles);
    await writeDocuments(paths, document); const produced = await outputsFingerprint(paths.subtitlesSrt, paths.subtitlesVtt, paths.subtitlesDocument); if (!produced) throw new SubtitleError("Subtitle generation produced empty files"); const warning = alignment?.success ? alignment.data.warning : options.forceEstimated ? "Estimated timing was explicitly requested" : "No valid alignment artifact was available";
    chapter.subtitle = { cueCount: document.cues.length, durationSeconds: document.durationSeconds, timingMode: document.timingMode, engine: alignment?.success ? alignment.data.engine : "deterministic", manual: false, warning: aligned ? undefined : warning }; chapter.stages.subtitles = { ...chapter.stages.subtitles, status: "complete", outputFingerprint: produced, completedAt: new Date().toISOString(), durationMs: Date.now() - started }; await persist(paths.chapterMeta, chapter); options.onEvent?.({ status: "completed", chapter: options.chapter, state: chapter.stages.subtitles }); return { chapter, document, reused: false, protected: false };
  } catch (error) { chapter.stages.subtitles = { ...chapter.stages.subtitles, status: "failed", durationMs: Date.now() - started, error: { message: error instanceof Error ? error.message : String(error) } }; await persist(paths.chapterMeta, chapter); throw new SubtitleError(`Chapter ${options.chapter} subtitle generation failed: ${chapter.stages.subtitles.error?.message}`, { cause: error }); }
}

export async function saveManualSubtitles(root: string, story: string, chapterNumber: number, rawCues: unknown) {
  const paths = storyPaths(root, story, chapterNumber); const metadataRaw = await readJsonIfExists<Chapter>(paths.chapterMeta); if (!metadataRaw) throw new SubtitleError(`Chapter ${chapterNumber} has no pipeline metadata`); const chapter = chapterSchema.parse(metadataRaw); if (!chapter.audio) throw new SubtitleError("Mastered audio is required before editing subtitles");
  const cues = subtitleDocumentSchema.shape.cues.parse(rawCues).map((cue, index) => ({ ...cue, index: index + 1 })); validateCueOrder(cues, chapter.audio.durationSeconds); const document: SubtitleDocument = { version: "manual-subtitles-v1", durationSeconds: chapter.audio.durationSeconds, timingMode: chapter.subtitle?.timingMode ?? "estimated", manual: true, cues };
  await atomicWriteJson(paths.subtitlesManual, document); await writeDocuments(paths, document); const outputFingerprint = await outputsFingerprint(paths.subtitlesSrt, paths.subtitlesVtt, paths.subtitlesDocument); chapter.subtitle = { cueCount: cues.length, durationSeconds: chapter.audio.durationSeconds, timingMode: document.timingMode, engine: "manual", manual: true }; chapter.video = undefined; chapter.stages.video = { status: "pending" }; chapter.stages.subtitles = { status: "complete", provider: "manual", model: "studio-editor", fingerprint: `manual:${fingerprint(document)}`, outputFingerprint, completedAt: new Date().toISOString() }; await persist(paths.chapterMeta, chapter); return { chapter, document };
}

export async function discardManualSubtitles(root: string, story: string, chapterNumber: number) { const paths = storyPaths(root, story, chapterNumber); const raw = await readJsonIfExists<Chapter>(paths.chapterMeta); if (!raw) throw new SubtitleError(`Chapter ${chapterNumber} has no pipeline metadata`); const chapter = chapterSchema.parse(raw); await rm(paths.subtitlesManual, { force: true }); chapter.subtitle = undefined; chapter.video = undefined; chapter.stages.subtitles = { status: "pending" }; chapter.stages.video = { status: "pending" }; await persist(paths.chapterMeta, chapter); return chapter; }

export function validateCueOrder(cues: SubtitleCue[], audioDurationSeconds: number) { for (let index = 0; index < cues.length; index++) { const cue = cues[index]!; if (cue.startSeconds < 0 || cue.endSeconds <= cue.startSeconds) throw new SubtitleError(`Cue ${index + 1} must have start < end`); if (cue.endSeconds > audioDurationSeconds + .25) throw new SubtitleError(`Cue ${index + 1} extends beyond the mastered audio`); if (index && cue.startSeconds < cues[index - 1]!.endSeconds) throw new SubtitleError(`Cue ${index + 1} overlaps or precedes the previous cue`); } }
export function subtitleFingerprint(narration: string | undefined, masteredAudio: string | undefined, settings: Story["subtitles"], alignment = "estimated") { return fingerprint({ narration, masteredAudio, settings, alignment, version: SUBTITLE_GENERATOR_VERSION }); }
async function writeDocuments(paths: ReturnType<typeof storyPaths>, document: SubtitleDocument) { await atomicWriteJson(paths.subtitlesDocument, document); await atomicWrite(paths.subtitlesSrt, toSrt(document)); await atomicWrite(paths.subtitlesVtt, toVtt(document)); }
async function outputsFingerprint(...paths: string[]) { try { const data = await Promise.all(paths.map((path) => readFile(path))); return data.every((value) => value.length) ? fingerprint(data.map((value) => value.toString("base64"))) : undefined; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined; throw error; } }
async function fileFingerprint(path: string) { const hash = createHash("sha256"); for await (const chunk of createReadStream(path)) hash.update(chunk as Buffer); return hash.digest("hex"); }
async function persist(path: string, chapter: Chapter) { chapter.updatedAt = new Date().toISOString(); await atomicWriteJson(path, chapterSchema.parse(chapter)); }
