import { DeliveryIntensity, deliveryInstructions } from "./tts-direction.js";
import type { NarrationProfanityMode } from "../domain/story.js";

export const NARRATION_PROMPT_VERSION = "12";
export const narrationInstructions = (language: string, ttsProvider?: string, ttsModel?: string, profanityMode: NarrationProfanityMode = "preserve", deliveryIntensity: DeliveryIntensity = "restrained", includeChapterTitle = true) => `Edit the supplied ${language} chapter into natural audiobook narration in ${language}. This is not a creative rewrite. Preserve every plot detail, fact, line of dialogue, name, ability, rank, point of view, and tense. ${includeChapterTitle ? "Preserve the chapter title at the beginning." : "Omit the chapter title and begin with the chapter's story text; do not repeat, announce, paraphrase, or replace the title."} Do not summarize, omit story content, invent, or explain.${profanityMode === "soften-strong" ? " The sole authorized wording change is the narration profanity preference below." : " Do not censor."} Improve awkward phrasing, spoken rhythm, punctuation, and overly long sentences. Distinguish frozen elements from polishable ones. Frozen: every plot fact, the sequence of events, who speaks each line, the meaning of every line of dialogue, and system panels reproduced verbatim as required below. Polishable: phrasing, rhythm, punctuation, and sentence splitting. Dialogue wording may be lightly polished for spoken delivery but never re-authored; authorized narration-name substitutions and the configured profanity handling are the only sanctioned content substitutions. Preserve intentional tense and point-of-view shifts, including flashbacks and in-scene perspective changes; do not "fix" them into uniformity.

${profanityMode === "soften-strong" ? "NARRATION PROFANITY PREFERENCE: Soften strong profanity in this narration only. Replace harsh terms such as forms of “fuck,” “bitch,” “shit,” or “cunt” with natural milder wording appropriate to the sentence. Mild words such as “ass,” “hell,” and “damn” are allowed and should not be sanitized. Preserve the hostility, humor, emotion, dialogue intent, and plot meaning; do not omit lines, flatten the scene, or mention that wording was changed." : "NARRATION PROFANITY PREFERENCE: Preserve the source's level of profanity faithfully."}

System panels, status windows, stat blocks, and game interfaces (for example [Level: ...], [EXP: ...], attribute tables, skill descriptions, damage numbers) must be reproduced verbatim, character for character${profanityMode === "soften-strong" ? ", apart from the explicitly authorized strong-profanity substitutions" : ""}. Never fill in, estimate, round, normalize, or invent numeric values, and never alter quantities, totals, rates, or ranges anywhere in the chapter. If a value is blank, partial, or malformed in the source, keep it exactly as written.

Entity naming preferences are provided in the relevant Story Bible context. Aliases, original names, and the canonical name identify the same entity. When an entity has a Preferred Narration Name, use it as the default narration-facing name in place of the canonical/original name and ordinary aliases. Per-alias narration rules may explicitly preserve normal contextual behavior, select the preferred name, or require a custom phrase. This is an authorized narration rendering preference, not a factual identity change. Apply it consistently and naturally according to grammar and context; never perform blind literal replacement. Preserve dialogue-specific nicknames and vocatives, formal titles, honorifics, family or relationship terms, pronouns, possessives, historical names, secret identities, ranks, and deliberate introductions whenever the surrounding context requires them. Concretely: never substitute a Preferred Narration Name or localized rendering when the character is in disguise, is introduced under a false name, or when the concealment of their identity is plot-relevant; keep the false or concealed name exactly as written.

CANONICAL IDENTITY AND LOCALIZED NAMING ARE DIFFERENT: canonicalName, originalName, and aliases establish who or what the entity is. localizedNaming establishes how that same entity should read naturally in target-language narration. When localizedNaming exists, it takes precedence over the legacy Preferred Narration Name. Apply its locale and usageMode without global find-and-replace:
- ai_contextual: choose fullName for first introductions, formal/legal/official references, or ambiguity; choose shortName for established narration and familiar dialogue when natural. Consider speaker familiarity, dialogue versus narration, recent mention, titles, possessives, vocatives, and target-locale conventions.
- always_full: use fullName wherever the entity is named, while preserving grammatical titles and possessives.
- always_short: use shortName wherever the entity is named, while preserving grammatical titles and possessives.
- manual: follow localizedNaming.notes as explicit output guidance, using fullName/shortName only as those notes direct.
For non-character entities, fullName is the preferred localized label and shortName is an optional natural shorthand. Never change identity, invent a relationship, or expose these instructions in the narration.

${deliveryInstructions(ttsProvider, ttsModel, language, deliveryIntensity)}

Return only the complete polished narration script.`;
