import { CommandRunner, runCommand } from "../audio/ffmpeg.js";
import { VideoError } from "../pipeline/errors.js";

export const VIDEO_PROCESSOR_VERSION = "ffmpeg-video-v1";
export type VideoProbe = { durationSeconds: number; videoCodec: string; audioCodec: string; width: number; height: number; container: string };
export class FfmpegVideoTools {
  constructor(readonly ffmpegPath = process.env.FFMPEG_PATH || "ffmpeg", readonly ffprobePath = process.env.FFPROBE_PATH || "ffprobe", private readonly runner: CommandRunner = runCommand) {}
  async validateAvailability() { try { await this.runner(this.ffmpegPath, ["-version"]); await this.runner(this.ffprobePath, ["-version"]); } catch (error) { throw new VideoError("FFmpeg and ffprobe are required for video rendering. Install FFmpeg or set FFMPEG_PATH and FFPROBE_PATH.", { cause: error }); } }
  async validateFilters(filters: string[]) { if (!filters.length) return; let result; try { result = await this.runner(this.ffmpegPath, ["-hide_banner", "-filters"]); } catch (error) { throw new VideoError("Unable to inspect FFmpeg video filters", { cause: error }); } const missing = filters.filter((filter) => !new RegExp(`\\s${filter}\\s`).test(result.stdout + result.stderr)); if (missing.length) throw new VideoError(`This FFmpeg build is missing required filter${missing.length > 1 ? "s" : ""}: ${missing.join(", ")}. Install an FFmpeg build with FreeType (drawtext) and libass (subtitles) support, or disable the corresponding intro/subtitle option.`); }
  async ffmpeg(args: string[]) { try { return await this.runner(this.ffmpegPath, ["-hide_banner", "-nostdin", "-y", ...args]); } catch (error) { throw new VideoError(`FFmpeg video render failed: ${error instanceof Error ? error.message : String(error)}`, { cause: error }); } }
  async probe(path: string): Promise<VideoProbe> { let result; try { result = await this.runner(this.ffprobePath, ["-v", "error", "-show_entries", "format=duration,format_name:stream=codec_name,codec_type,width,height", "-of", "json", path]); } catch (error) { throw new VideoError(`ffprobe failed for ${path}`, { cause: error }); }
    try { const value = JSON.parse(result.stdout) as { format?: { duration?: string; format_name?: string }; streams?: Array<{ codec_type?: string; codec_name?: string; width?: number; height?: number }> }; const video = value.streams?.find((stream) => stream.codec_type === "video"); const audio = value.streams?.find((stream) => stream.codec_type === "audio"); const durationSeconds = Number(value.format?.duration); if (!video?.codec_name || !audio?.codec_name || !video.width || !video.height || !Number.isFinite(durationSeconds) || durationSeconds <= 0) throw new Error("missing valid audio/video streams"); return { durationSeconds, videoCodec: video.codec_name, audioCodec: audio.codec_name, width: video.width, height: video.height, container: value.format?.format_name ?? "unknown" }; } catch (error) { throw new VideoError(`Invalid ffprobe video output for ${path}`, { cause: error }); }
  }
}
