import { VideoError } from "../pipeline/errors.js";
import { VideoSettings } from "./config.js";
import { FfmpegVideoTools, VideoProbe, VIDEO_PROCESSOR_VERSION } from "./ffmpeg-video.js";
import { buildSceneMotionFilter, buildVideoPresentationTimeline } from "./presentation.js";
import type { SceneVideoTreatment } from "../scenes/types.js";

export type SceneVideoImage = { path: string; durationSeconds: number; videoTreatment?: SceneVideoTreatment; disabled?: boolean };
export type ChapterVideoInput = { audio: string; subtitles?: string; cover?: string; sceneArtwork?: SceneVideoImage[]; storyTitle: string; chapterLabel: string; chapterTitle?: string; audioDurationSeconds: number };
export interface VideoProcessor { readonly version: string; render(input: ChapterVideoInput, output: string, settings: VideoSettings): Promise<VideoProbe>; }
export class FfmpegVideoProcessor implements VideoProcessor {
  readonly version = VIDEO_PROCESSOR_VERSION; constructor(private readonly tools = new FfmpegVideoTools()) {}
  async render(input: ChapterVideoInput, output: string, settings: VideoSettings) { await this.tools.validateAvailability(); const timeline = buildVideoPresentationTimeline(input.sceneArtwork ?? [], settings); const hasCover = !timeline.scenes.length && Boolean(input.cover); await this.tools.validateFilters([...(settings.introDurationSeconds > 0 ? ["drawtext"] : []), ...((settings.subtitleMode === "burn" || settings.subtitleMode === "both") && input.subtitles ? ["subtitles"] : []), ...(timeline.boundaries.some((boundary) => boundary.effectiveDurationSeconds > 0) ? ["xfade"] : []), ...(timeline.scenes.some((scene) => scene.motion !== "still") || hasCover && settings.motion.mode !== "still" ? ["zoompan"] : [])]); const args = buildVideoArgs(input, output, settings); await this.tools.ffmpeg(args); const probe = await this.tools.probe(output); validateChapterVideo(probe, settings, input.audioDurationSeconds + settings.introDurationSeconds); return probe; }
}
export function buildVideoArgs(input: ChapterVideoInput, output: string, settings: VideoSettings) {
  const args: string[] = []; const duration = input.audioDurationSeconds + settings.introDurationSeconds; const sceneArtwork = input.sceneArtwork?.filter((item) => !item.disabled && item.durationSeconds > 0) ?? []; const timeline = buildVideoPresentationTimeline(sceneArtwork, settings); const hasScenes = sceneArtwork.length > 0; const hasCover = !hasScenes && Boolean(input.cover);
  if (hasScenes) for (let index = 0; index < sceneArtwork.length; index++) args.push("-loop", "1", "-framerate", String(settings.fps), "-t", String(timeline.scenes[index]!.visualDurationSeconds + (index === 0 ? settings.introDurationSeconds : 0) + 1 / settings.fps), "-i", sceneArtwork[index]!.path);
  else if (hasCover) args.push("-loop", "1", "-framerate", String(settings.fps), "-i", input.cover!); else args.push("-f", "lavfi", "-i", `color=c=0x11131a:s=${settings.width}x${settings.height}:r=${settings.fps}:d=${duration}`);
  const audioIndex = hasScenes ? sceneArtwork.length : 1; args.push("-i", input.audio); const soft = (settings.subtitleMode === "soft" || settings.subtitleMode === "both") && input.subtitles; const subtitleIndex = audioIndex + 1; if (soft) args.push("-itsoffset", String(settings.introDurationSeconds), "-i", input.subtitles!);
  const filters: string[] = []; let visual = "[0:v]";
  if (hasScenes) { const labels: string[] = []; for (let index = 0; index < sceneArtwork.length; index++) { const label = `scene${index}`; const scene = timeline.scenes[index]!; const clipDuration = scene.visualDurationSeconds + (index === 0 ? settings.introDurationSeconds : 0); const motion = buildSceneMotionFilter({ mode: scene.motion, width: settings.width, height: settings.height, fps: settings.fps, durationSeconds: clipDuration, intensity: settings.motion.intensity }); filters.push(`[${index}:v]${motion},setsar=1,fps=${settings.fps},trim=duration=${clipDuration},settb=AVTB,setpts=PTS-STARTPTS[${label}]`); labels.push(`[${label}]`); }
    let current = labels[0]!; for (let index = 0; index < timeline.boundaries.length; index++) { const boundary = timeline.boundaries[index]!; const next = labels[index + 1]!; const outputLabel = index === timeline.boundaries.length - 1 ? "[background]" : `[joined${index}]`; if (boundary.mode === "cut") filters.push(`${current}${next}concat=n=2:v=1:a=0${outputLabel}`); else { const effect = boundary.mode === "dissolve" ? "fade" : boundary.mode === "fade_black" ? "fadeblack" : "slideleft"; const offset = settings.introDurationSeconds + boundary.boundaryTimeSeconds - boundary.effectiveDurationSeconds / 2; filters.push(`${current}${next}xfade=transition=${effect}:duration=${boundary.effectiveDurationSeconds}:offset=${offset.toFixed(6)}${outputLabel}`); } current = outputLabel; } if (!timeline.boundaries.length) filters.push(`${current}null[background]`); visual = "[background]"; }
  else if (hasCover) { const mode = settings.motion.mode === "auto_subtle" ? "zoom_in" : settings.motion.mode; filters.push(`[0:v]${buildSceneMotionFilter({ mode, width: settings.width, height: settings.height, fps: settings.fps, durationSeconds: duration, intensity: settings.motion.intensity })},setsar=1,fps=${settings.fps},trim=duration=${duration},setpts=PTS-STARTPTS[background]`); visual = "[background]"; }
  else { filters.push("[0:v]null[background]"); visual = "[background]"; }
  if (settings.introDurationSeconds > 0) { const title = [input.storyTitle, input.chapterLabel, input.chapterTitle].filter((value): value is string => Boolean(value)).map(escapeDrawtext).join("\\n"); const fontSize = Math.round(settings.height * .055); filters.push(`${visual}drawtext=text='${title}':fontcolor=white:fontsize=${fontSize}:line_spacing=${Math.round(fontSize * .35)}:x=(w-text_w)/2:y=(h-text_h)/2:enable='between(t,0,${settings.introDurationSeconds})'[titled]`); visual = "[titled]"; }
  if ((settings.subtitleMode === "burn" || settings.subtitleMode === "both") && input.subtitles) { const style = subtitleStyle(settings); filters.push(`${visual}setpts=PTS-${settings.introDurationSeconds}/TB,subtitles=filename='${escapeFilterPath(input.subtitles)}':force_style='${style}',setpts=PTS+${settings.introDurationSeconds}/TB[captioned]`); visual = "[captioned]"; }
  if (settings.introDurationSeconds > 0) filters.push(`anullsrc=r=44100:cl=stereo:d=${settings.introDurationSeconds}[intro];[intro][${audioIndex}:a]concat=n=2:v=0:a=1[audio]`); else filters.push(`[${audioIndex}:a]anull[audio]`);
  args.push("-filter_complex", filters.join(";"), "-map", visual, "-map", "[audio]"); if (soft) args.push("-map", `${subtitleIndex}:s:0`, "-c:s", "mov_text", "-metadata:s:s:0", "language=eng");
  args.push("-t", String(duration), "-r", String(settings.fps), "-c:v", settings.codec, "-crf", String(settings.quality), "-preset", "medium", "-pix_fmt", "yuv420p", "-c:a", "aac", "-b:a", "192k", "-movflags", "+faststart", output); return args;
}
export function validateChapterVideo(probe: VideoProbe, settings: VideoSettings, expectedDuration: number) { if (probe.videoCodec !== "h264" || probe.audioCodec !== "aac") throw new VideoError(`Expected H.264/AAC video, received ${probe.videoCodec}/${probe.audioCodec}`); if (probe.width !== settings.width || probe.height !== settings.height) throw new VideoError(`Expected ${settings.width}x${settings.height}, received ${probe.width}x${probe.height}`); if (Math.abs(probe.durationSeconds - expectedDuration) > Math.max(0.25, 2 / settings.fps)) throw new VideoError(`Video duration ${probe.durationSeconds.toFixed(2)}s does not match expected ${expectedDuration.toFixed(2)}s`); }
function subtitleStyle(settings: VideoSettings) { const size = settings.subtitleStyle === "large" ? 17 : settings.subtitleStyle === "minimal" ? 10 : 12; return `FontName=Arial,FontSize=${size},PrimaryColour=&H00FFFFFF,OutlineColour=&H80000000,BorderStyle=1,Outline=1,Shadow=0,MarginV=14,Alignment=2`; }
function escapeFilterPath(value: string) { return value.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/:/g, "\\:").replace(/,/g, "\\,").replace(/\[/g, "\\[").replace(/\]/g, "\\]"); }
function escapeDrawtext(value: string) { return value.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/:/g, "\\:").replace(/%/g, "\\%").replace(/\n/g, " "); }
