import { mkdir, readdir, rename, rm } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { z } from "zod";
import { Story } from "../domain/story.js";
import { Chapter, chapterSchema } from "../domain/chapter.js";
import { VideoError } from "../pipeline/errors.js";
import { atomicWrite, atomicWriteJson } from "../storage/atomic-write.js";
import { storyPaths, videoExportPaths } from "../storage/paths.js";
import { exists, readJsonIfExists } from "../storage/story-files.js";
import { fingerprint } from "../utils/hash.js";
import { fileFingerprint } from "../utils/file-fingerprint.js";
import { FfmpegVideoTools, VideoProbe, VIDEO_PROCESSOR_VERSION } from "./ffmpeg-video.js";

export type ExportVideoChapter = { chapter: number; title: string; path: string; durationSeconds: number; fingerprint: string };
export interface VideoExportProcessor { readonly version: string; assemble(chapters: ExportVideoChapter[], output: string, title: string): Promise<VideoProbe>; }
export const videoExportManifestSchema = z.object({ version: z.literal(1), fingerprint: z.string(), outputFingerprint: z.string(), story: z.string(), from: z.number().int().positive(), to: z.number().int().positive(), createdAt: z.string(), output: z.string(), durationSeconds: z.number().positive(), chapters: z.array(z.object({ chapter: z.number().int().positive(), title: z.string(), durationSeconds: z.number().positive(), fingerprint: z.string() })) });
export class FfmpegVideoExportProcessor implements VideoExportProcessor { readonly version = VIDEO_PROCESSOR_VERSION; constructor(private readonly tools = new FfmpegVideoTools()) {} async assemble(chapters: ExportVideoChapter[], output: string, title: string) { await this.tools.validateAvailability(); const metadataPath = `${output}.ffmetadata`; const concatPath = `${output}.ffconcat`; await atomicWrite(metadataPath, buildVideoMetadata(chapters, title)); await atomicWrite(concatPath, buildVideoConcatManifest(chapters)); try { await this.tools.ffmpeg(buildVideoExportArgs(concatPath, output, metadataPath)); return await this.tools.probe(output); } finally { await Promise.all([metadataPath, concatPath].map((path) => rm(path, { force: true }))); } } }

export async function assembleVideoExport(options: { root: string; story: Story; from: number; to: number; processor: VideoExportProcessor; force?: boolean; onProgress?: (event: { type: string; total: number }) => void }) {
  const chapters = await selectVideoChapters(options.root, options.story, options.from, options.to); const paths = videoExportPaths(options.root, options.story.slug, options.from, options.to); const inputFingerprint = fingerprint({ story: options.story.slug, title: options.story.title, processor: options.processor.version, chapters: chapters.map(({ chapter, title, fingerprint }) => ({ chapter, title, fingerprint })) }); const cachedRaw = await readJsonIfExists(paths.manifest); const cached = cachedRaw ? videoExportManifestSchema.safeParse(cachedRaw) : undefined;
  if (!options.force && cached?.success && cached.data.fingerprint === inputFingerprint && await fileFingerprint(paths.output) === cached.data.outputFingerprint) return { manifest: cached.data, reused: true };
  await mkdir(paths.directory, { recursive: true }); const staged = `${paths.output}.stage-${randomUUID()}.mp4`; options.onProgress?.({ type: "videoExport.started", total: chapters.length });
  try { const probe = await options.processor.assemble(chapters, staged, options.story.title); const expected = chapters.reduce((sum, chapter) => sum + chapter.durationSeconds, 0); if (probe.videoCodec !== "h264" || probe.audioCodec !== "aac" || !probe.container.toLowerCase().includes("mp4") || probe.durationSeconds < expected * .9 || probe.durationSeconds > expected * 1.1 + 1) throw new VideoError("Combined video failed H.264/AAC MP4 stream or duration validation"); await rename(staged, paths.output); const outputFingerprint = await fileFingerprint(paths.output); if (!outputFingerprint) throw new VideoError("Combined video output is empty"); const manifest = videoExportManifestSchema.parse({ version: 1, fingerprint: inputFingerprint, outputFingerprint, story: options.story.slug, from: options.from, to: options.to, createdAt: new Date().toISOString(), output: paths.output, durationSeconds: probe.durationSeconds, chapters }); await atomicWriteJson(paths.manifest, manifest); options.onProgress?.({ type: "videoExport.completed", total: chapters.length }); return { manifest, reused: false }; } catch (error) { await rm(staged, { force: true }); throw new VideoError(`Combined video export failed: ${error instanceof Error ? error.message : String(error)}`, { cause: error }); }
}
export async function selectVideoChapters(root: string, story: Story, from: number, to: number) { if (!Number.isInteger(from) || !Number.isInteger(to) || from < 1 || to < from) throw new VideoError("Video export range must satisfy from <= to"); const chaptersRoot = `${storyPaths(root, story.slug, 1).story}/chapters`; let numbers: number[] = []; try { numbers = (await readdir(chaptersRoot, { withFileTypes: true })).filter((entry) => entry.isDirectory() && /^\d+$/.test(entry.name)).map((entry) => Number(entry.name)).filter((chapter) => chapter >= from && chapter <= to).sort((a, b) => a - b); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; } if (!numbers.length) throw new VideoError(`No chapters found in range ${from}-${to}`); const result: ExportVideoChapter[] = []; for (const chapter of numbers) { const paths = storyPaths(root, story.slug, chapter); const raw = await readJsonIfExists<Chapter>(paths.chapterMeta); const metadata = raw ? chapterSchema.parse(raw) : undefined; const actualFingerprint = await fileFingerprint(paths.video); if (!metadata || metadata.stages.video.status !== "complete" || !metadata.stages.video.outputFingerprint || actualFingerprint !== metadata.stages.video.outputFingerprint || !metadata.video) throw new VideoError(`Chapter ${chapter} video is not rendered or changed since rendering`); result.push({ chapter, title: metadata.translatedTitle ?? metadata.originalTitle ?? `Chapter ${chapter}`, path: paths.video, durationSeconds: metadata.video.durationSeconds, fingerprint: actualFingerprint }); } return result; }
export function buildVideoExportArgs(concatPath: string, output: string, metadata: string) { return ["-f", "concat", "-safe", "0", "-i", concatPath, "-f", "ffmetadata", "-i", metadata, "-map", "0:v", "-map", "0:a", "-map_metadata", "1", "-map_chapters", "1", "-c:v", "libx264", "-crf", "20", "-pix_fmt", "yuv420p", "-c:a", "aac", "-b:a", "192k", "-movflags", "+faststart", output]; }
export function buildVideoConcatManifest(chapters: ExportVideoChapter[]) { if (!chapters.length) throw new VideoError("Video export requires at least one chapter"); return `ffconcat version 1.0\n${chapters.map((chapter) => `file '${chapter.path.replaceAll("'", "'\\''")}'`).join("\n")}\n`; }
function buildVideoMetadata(chapters: ExportVideoChapter[], title: string) { let cursor = 0; const lines = [";FFMETADATA1", `title=${escapeMeta(title)}`]; for (const chapter of chapters) { const start = Math.round(cursor * 1000); cursor += chapter.durationSeconds; lines.push("[CHAPTER]", "TIMEBASE=1/1000", `START=${start}`, `END=${Math.round(cursor * 1000)}`, `title=${escapeMeta(chapter.title)}`); } return `${lines.join("\n")}\n`; }
function escapeMeta(value: string) { return value.replace(/([\\;#=])/g, "\\$1").replace(/\n/g, "\\n"); }
