#!/usr/bin/env node
import { alignStoredChapter } from "../../src/alignment/chapter-alignment.js";
import { alignmentConfig, createAlignmentEngine } from "../../src/alignment/config.js";
import { selectChapterRange } from "../../src/batch/range.js";
import { loadEnvironment, resolveStudioRoot } from "../../src/config/env.js";
import { loadStory } from "../../src/config/load-config.js";
import { loadImportedChapters } from "../../src/source/importer.js";
import { storyPaths } from "../../src/storage/paths.js";
import { withStoryLock } from "../../src/storage/story-lock.js";

async function main() { const args = parse(process.argv.slice(2)); const env = loadEnvironment(); const root = resolveStudioRoot(env); const config = alignmentConfig(env, root); const engine = createAlignmentEngine(config); await withStoryLock(root, args.story, "audio alignment", async () => { const story = await loadStory(storyPaths(root, args.story, 1).storyConfig); const selected = selectChapterRange((await loadImportedChapters(root, args.story)).chapters, args.from, args.to); for (let index = 0; index < selected.length; index++) { const chapter = selected[index]!.chapter; const result = await alignStoredChapter({ root, storySlug: story.slug, chapter, language: story.outputLanguage, config, engine, force: args.force, forceEstimated: args.estimated, requireAligned: args.requireAligned }); process.stdout.write(`[${index + 1}/${selected.length}] Chapter ${chapter}: ${result.reused ? "reused" : result.artifact.mode}${result.artifact.warning ? ` — ${result.artifact.warning}` : ""}\n`); } }); }
function parse(values: string[]) { let story = ""; let from: number | undefined; let to: number | undefined; let force = false; let estimated = false; let requireAligned = false; for (let index = 0; index < values.length; index++) { const key = values[index]!; if (key === "--force") { force = true; continue; } if (key === "--estimated") { estimated = true; continue; } if (key === "--require-aligned") { requireAligned = true; continue; } const value = values[++index]; if (!value || value.startsWith("--")) usage(`Missing value for ${key}`); if (key === "--story") story = value; else if (key === "--chapter") from = to = positive(value, key); else if (key === "--from") from = positive(value, key); else if (key === "--to") to = positive(value, key); else usage(`Unknown argument: ${key}`); } if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(story)) usage("--story must be a lowercase kebab-case slug"); if (estimated && requireAligned) usage("--estimated and --require-aligned cannot be combined"); return { story, from, to, force, estimated, requireAligned }; }
function positive(value: string, key: string) { const number = Number(value); if (!Number.isSafeInteger(number) || number < 1) usage(`${key} must be a positive integer`); return number; }
function usage(message: string): never { throw new Error(`${message}\nUsage: npm run story:align -- --story <slug> [--chapter N | --from N --to N] [--force] [--estimated] [--require-aligned]`); }
main().catch((error) => { process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`); process.exitCode = 1; });
