#!/usr/bin/env node
import { selectChapterRange } from "../../src/batch/range.js";
import { generateStoredArtwork } from "../../src/artwork/generator.js";
import { OpenAIImageProvider } from "../../src/artwork/openai-image.provider.js";
import { loadEnvironment } from "../../src/config/env.js";
import { loadStory } from "../../src/config/load-config.js";
import { loadImportedChapters } from "../../src/source/importer.js";
import { storyPaths } from "../../src/storage/paths.js";
import { withStoryLock } from "../../src/storage/story-lock.js";

async function main() { const args = parse(process.argv.slice(2)); const env = loadEnvironment(); await withStoryLock(process.cwd(), args.story, "artwork generation", async () => { const story = await loadStory(storyPaths(process.cwd(), args.story, 1).storyConfig); const provider = new OpenAIImageProvider(env.OPENAI_API_KEY, env.PROVIDER_TIMEOUT_MS); const selected = selectChapterRange((await loadImportedChapters(process.cwd(), args.story)).chapters, args.from, args.to); let estimated = 0; for (let index = 0; index < selected.length; index++) { const chapter = selected[index]!.chapter; const result = await generateStoredArtwork({ root: process.cwd(), story, chapter, provider, sceneId: args.scene, force: args.force, dryRun: args.dryRun }); estimated += result.imagesToGenerate; process.stdout.write(`[${index + 1}/${selected.length}] Chapter ${chapter}: ${args.dryRun ? `${result.imagesToGenerate} image(s) would be generated` : `${result.generated} generated, ${result.reused} reused`}\n`); } if (args.dryRun) process.stdout.write(`Dry run total: ${estimated} paid image request(s). No images generated.\n`); }); }
function parse(values: string[]) { let story = ""; let from: number | undefined; let to: number | undefined; let chapter: number | undefined; let scene: string | undefined; let force = false; let dryRun = false; for (let index = 0; index < values.length; index++) { const key = values[index]!; if (key === "--force") { force = true; continue; } if (key === "--dry-run") { dryRun = true; continue; } const value = values[++index]; if (!value || value.startsWith("--")) usage(`Missing value for ${key}`); if (key === "--story") story = value; else if (key === "--chapter") chapter = integer(value, key); else if (key === "--from") from = integer(value, key); else if (key === "--to") to = integer(value, key); else if (key === "--scene" && /^scene-\d{3}$/.test(value)) scene = value; else usage(`Unknown or invalid argument: ${key}`); } if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(story)) usage("--story must be a lowercase kebab-case slug"); if (chapter !== undefined) { if (from !== undefined || to !== undefined) usage("Use --chapter or --from/--to, not both"); from = chapter; to = chapter; } if (from === undefined || to === undefined) usage("Choose an explicit --chapter or --from and --to range"); if (to < from) usage("--to must be greater than or equal to --from"); if (scene && from !== to) usage("--scene requires a single chapter"); return { story, from, to, scene, force, dryRun }; }
function integer(value: string, key: string) { const parsed = Number(value); if (!Number.isInteger(parsed) || parsed < 1) usage(`${key} must be a positive integer`); return parsed; }
function usage(message: string): never { throw new Error(`${message}\nUsage: npm run story:artwork -- --story <slug> (--chapter N | --from N --to N) [--scene scene-NNN] [--force] [--dry-run]`); }
main().catch((error) => { process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`); process.exitCode = 1; });
