#!/usr/bin/env node
import { pathToFileURL } from "node:url";
import { getCanonicalEntitiesPage, getCanonicalEntityDetail, getStoryBible } from "../server/catalog.js";
import { StudioOperations } from "../server/operations.js";
import { loadEnvironment, resolveStudioRoot } from "../../src/config/env.js";
import { loadImportedChapters } from "../../src/source/importer.js";
import { rebuildStoryBibleBeforeChapter } from "../../src/story-bible/rebuild.js";
import { withStoryLock } from "../../src/storage/story-lock.js";

type Command = { action: "list"; story: string; type?: string; query?: string } | { action: "show"; story: string; id: string } | { action: "edit"; story: string; id: string; patch: Record<string, unknown> } | { action: "merge"; story: string; target: string; sources: string[]; reason: string } | { action: "undo"; story: string; mergeId: string } | { action: "rebuild"; story: string; through?: number };
const slug = (value: string) => { if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(value)) throw new Error("Story must be a valid slug"); return value; };
const json = (value: string) => { try { const parsed = JSON.parse(value); if (!parsed || Array.isArray(parsed) || typeof parsed !== "object") throw new Error(); return parsed as Record<string, unknown>; } catch { throw new Error("--json must be a JSON object"); } };
export function parseBibleArgs(v: string[]): Command { const [action, storyRaw, id, ...rest] = v; const story = storyRaw && slug(storyRaw); if (!action || !story) throw new Error("Usage: story:bible <list|show|edit|merge|undo|rebuild> <story> ..."); if (action === "list") return { action, story, ...options(id ? [id, ...rest] : []) }; if (action === "show") { if (!id || rest.length) throw new Error("Show requires an entity ID"); return { action, story, id }; } if (action === "edit") { if (!id || rest[0] !== "--json" || !rest[1] || rest.length !== 2) throw new Error("Edit requires <entity-id> --json '{...}'"); return { action, story, id, patch: json(rest[1]) }; } if (action === "merge") { const o = options(rest); if (!id || !o.target || !o.sources || !o.reason) throw new Error("Merge requires --target <entity-id> --sources id,id --reason text"); return { action, story, target: o.target, sources: o.sources.split(",").filter(Boolean), reason: o.reason }; } if (action === "undo") { if (!id || rest.length) throw new Error("Undo requires a merge ID"); return { action, story, mergeId: id }; } if (action === "rebuild") { const o = options(id ? [id, ...rest] : []); return { action, story, through: o.through ? integer(o.through, "--through") : undefined }; } throw new Error(`Unknown Story Bible action: ${action}`); }
function options(v: string[]) { const out: Record<string, string> = {}; for (let i=0;i<v.length;i+=2) { const key=v[i], value=v[i+1]; if (!key?.startsWith("--") || !value || value.startsWith("--")) throw new Error(`Missing value for ${key ?? "option"}`); out[key.slice(2)] = value; } return out; }
function integer(value:string,label:string) { const n=Number(value); if (!Number.isSafeInteger(n)||n<1) throw new Error(`${label} must be a positive integer`); return n; }
async function main() { const command=parseBibleArgs(process.argv.slice(2)); const env=loadEnvironment(), root=resolveStudioRoot(env), operations=new StudioOperations(root,env); try { await runBibleCommand(command,{root,operations,stdout:t=>process.stdout.write(t)}); } finally { await operations.close(); } }
export async function runBibleCommand(command: Command, d: {root:string;operations:Pick<StudioOperations,"updateCanonicalEntity"|"mergeCanonicalEntities"|"undoCanonicalMerge">;stdout:(text:string)=>unknown}) { if(command.action==="list") { const page=await getCanonicalEntitiesPage(d.root,command.story,{page:1,pageSize:100,type:command.type,query:command.query}); d.stdout(page.items.length?page.items.map(x=>`${x.id}\t${x.type}\t${x.canonicalName}`).join("\n")+"\n":"No canonical entities found.\n"); return; } if(command.action==="show") return void d.stdout(JSON.stringify(await getCanonicalEntityDetail(d.root,command.story,command.id),null,2)+"\n"); if(command.action==="edit") return void d.stdout(JSON.stringify(await d.operations.updateCanonicalEntity(command.story,command.id,command.patch),null,2)+"\n"); if(command.action==="merge") return void d.stdout(JSON.stringify(await d.operations.mergeCanonicalEntities(command.story,{targetEntityId:command.target,sourceEntityIds:command.sources,reason:command.reason}),null,2)+"\n"); if(command.action==="undo") return void d.stdout(JSON.stringify(await d.operations.undoCanonicalMerge(command.story,command.mergeId),null,2)+"\n"); await withStoryLock(d.root,command.story,"Story Bible rebuild",async()=>{const chapters=(await loadImportedChapters(d.root,command.story)).chapters.map(x=>x.chapter);const last=command.through??Math.max(...chapters);if(!last)throw new Error("Story has no imported chapters");const bible=await rebuildStoryBibleBeforeChapter(d.root,command.story,last+1);d.stdout(JSON.stringify({rebuiltThroughChapter:last,entities:bible.canonicalEntities.length},null,2)+"\n");}); }
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href) main().catch(e=>{process.stderr.write(`${e instanceof Error?e.message:String(e)}\n`);process.exitCode=1;});
