#!/usr/bin/env node
import { loadEnvironment, resolveStudioRoot } from "../../src/config/env.js";
import { PostgresUsageRepository } from "../../src/cost/repository.js";
import { createDatabasePool } from "../../src/queue/database.js";

async function main(){const args=parse(process.argv.slice(2));const env=loadEnvironment();if(!env.DATABASE_URL)throw new Error("DATABASE_URL is required for cost analytics");const pool=createDatabasePool(env.DATABASE_URL,{max:1});try{const repository=new PostgresUsageRepository(pool,resolveStudioRoot(env));const filters={story:args.story,chapterFrom:args.from,chapterTo:args.to,provider:args.provider,stage:args.stage,model:args.model,fromDate:args.fromDate,toDate:args.toDate};if(args.format==="json"){process.stdout.write(`${JSON.stringify({analytics:await repository.summary(filters),records:await repository.list({...filters,pageSize:200})},null,2)}\n`);return;}if(args.format==="csv"){const records=(await repository.list({...filters,pageSize:200})).items;process.stdout.write(["timestamp,story,chapter,stage,provider,model,operation,success,input_tokens,cached_tokens,output_tokens,utf8_bytes,images,cost_usd,cost_status,request_id",...records.map(r=>[r.attemptedAt,r.story,r.chapter??"",r.stage,r.provider,r.model,r.operation,r.success,r.inputTokens??"",r.cachedInputTokens??"",r.outputTokens??"",r.inputUtf8Bytes??"",r.imageCount??"",r.costUsd??"",r.costStatus,r.requestId??""].map(csv).join(","))].join("\n")+"\n");return;}const data=await repository.summary(filters);const s=data.summary;process.stdout.write([`Provider costs · ${args.story}`,`Recorded spend: $${Number(s.totalCostUsd).toFixed(6)}`,`Requests: ${s.requests} (${s.failed} failed, ${s.retries} retries)`,`Tokens: ${s.inputTokens} input · ${s.cachedInputTokens} cached · ${s.outputTokens} output`,`TTS input: ${s.inputUtf8Bytes} UTF-8 bytes`,`Images: ${s.images}`,s.unpricedRequests?`Pricing unavailable: ${s.unpricedRequests} request(s)` : "All recorded requests are priced","",...data.dimensions.map((d:any)=>`${d.stage.padEnd(16)} ${d.provider}/${d.model}  ${d.requests} req  $${Number(d.costUsd).toFixed(6)}`)].join("\n")+"\n");}finally{await pool.end();}}
type Args={story:string;from?:number;to?:number;provider?:string;stage?:string;model?:string;fromDate?:string;toDate?:string;format:"text"|"json"|"csv"};
function parse(values:string[]):Args{const result:Args={story:"",format:"text"};for(let i=0;i<values.length;i++){const key=values[i]!,value=values[++i];if(!value)throw new Error(`Missing value for ${key}`);if(key==="--story")result.story=value;else if(key==="--from")result.from=positive(value);else if(key==="--to")result.to=positive(value);else if(key==="--provider")result.provider=value;else if(key==="--stage")result.stage=value;else if(key==="--model")result.model=value;else if(key==="--from-date")result.fromDate=new Date(value).toISOString();else if(key==="--to-date")result.toDate=new Date(value).toISOString();else if(key==="--format"&&(value==="text"||value==="json"||value==="csv"))result.format=value;else throw new Error(`Unknown argument: ${key}`);}if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(result.story))throw new Error("Usage: npm run story:cost -- --story <slug> [--from N --to N] [--provider name] [--stage name] [--format text|json|csv]");return result;}
function positive(value:string){const n=Number(value);if(!Number.isSafeInteger(n)||n<1)throw new Error("Chapter filters must be positive integers");return n;}
function csv(value:unknown){const text=String(value);return /[",\n]/.test(text)?`"${text.replaceAll('"','""')}"`:text;}
main().catch(error=>{process.stderr.write(`${error instanceof Error?error.message:String(error)}\n`);process.exitCode=1;});
