#!/usr/bin/env node
import { loadEnvironment, resolveStudioRoot } from "../../src/config/env.js";
import { loadStory } from "../../src/config/load-config.js";
import { createPipelineRuntime } from "../../src/pipeline/create-pipeline.js";
import { ProductionForce, ProductionOutput, productionForceSchema, productionOutputSchema } from "../../src/production/types.js";
import { runProduction } from "../../src/production/orchestrator.js";
import { refreshProductionRange } from "../../src/production/refresh.js";
import { loadImportedChapters } from "../../src/source/importer.js";
import { SourceProviderRegistry } from "../../src/source/registry.js";
import { createWebHttpClient } from "../../src/source/web/create-client.js";
import { storyPaths } from "../../src/storage/paths.js";
import { withStoryLock } from "../../src/storage/story-lock.js";
import { ShutdownController } from "../../src/batch/shutdown.js";
import { FfmpegAudiobookProcessor } from "../../src/audio/audiobook.js";
import { FfmpegVideoProcessor } from "../../src/video/renderer.js";
import { FfmpegVideoExportProcessor } from "../../src/video/video-export.js";
import { alignmentConfig, createAlignmentEngine } from "../../src/alignment/config.js";
import { createDatabasePool } from "../../src/queue/database.js";
import { PostgresUsageRepository } from "../../src/cost/repository.js";
import { CostEstimate, estimatePlanCost } from "../../src/cost/estimate.js";

async function main() { const args = parse(process.argv.slice(2)); const env = loadEnvironment(); const root = resolveStudioRoot(env); const pool=env.DATABASE_URL?createDatabasePool(env.DATABASE_URL,{max:1}):undefined;const usage=pool?new PostgresUsageRepository(pool,root):undefined;try{await withStoryLock(root, args.story, "end-to-end production", async () => {
  const story = await loadStory(storyPaths(root, args.story, 1).storyConfig); const runtime = createPipelineRuntime(env,usage); const registry = new SourceProviderRegistry(undefined, createWebHttpClient(root, env)); const alignConfig = alignmentConfig(env, root); const shutdown = new ShutdownController(); const stop = () => { shutdown.request(); process.stderr.write("\nPause requested; stopping after the current chapter.\n"); }; process.once("SIGINT", stop); process.once("SIGTERM", stop);
  try { const result = await runProduction({ root, story, from: args.from, to: args.to, profile: args.profile, outputs: args.outputs, artwork: args.artwork, repairQa: args.repairQa, alignment: args.alignment, refresh: args.refresh, dryRun: args.dryRun, force: args.force, audiobookFormat: args.format, pause: shutdown, onProgress: printProgress }, { pipeline: runtime.pipeline, loadChapters: async () => (await loadImportedChapters(root, story.slug)).chapters, refresh: (from, to) => refreshProductionRange({ root, story, from, to, registry }), scenePlanner: runtime.router.forStage(story.pipeline.scenePlanner), image: runtime.images.forName(story.artwork.provider), video: new FfmpegVideoProcessor(), videoExport: new FfmpegVideoExportProcessor(), audiobook: new FfmpegAudiobookProcessor(), alignmentConfig: alignConfig, alignmentEngine: createAlignmentEngine(alignConfig) });
    const costEstimate=args.dryRun&&usage?estimatePlanCost(result.plan,await usage.summary({story:story.slug})):undefined;process.stdout.write(args.dryRun ? formatPlan(result.plan,costEstimate) : formatSummary(result.manifest)); if (["completed_with_errors", "failed"].includes(result.manifest.status)) process.exitCode = 1; if (result.manifest.status === "paused") process.exitCode = 130;
  } finally { process.removeListener("SIGINT", stop); process.removeListener("SIGTERM", stop); }
});}finally{await pool?.end();} }

type Args = { story: string; from: number; to: number; profile?: string; outputs?: ProductionOutput[]; artwork?: boolean; repairQa?: boolean; alignment?: boolean; refresh: boolean; dryRun: boolean; force?: ProductionForce; format?: "mp3" | "m4b" };
function parse(values: string[]): Args { const result: Args = { story: "", from: 0, to: 0, refresh: false, dryRun: false }; const outputs: ProductionOutput[] = [];
  for (let index = 0; index < values.length; index++) { const key = values[index]!; if (["--artwork", "--no-artwork", "--repair-qa", "--no-repair-qa", "--alignment", "--no-alignment", "--refresh", "--dry-run"].includes(key)) { if (key === "--artwork") result.artwork = true; if (key === "--no-artwork") result.artwork = false; if (key === "--repair-qa") result.repairQa = true; if (key === "--no-repair-qa") result.repairQa = false; if (key === "--alignment") result.alignment = true; if (key === "--no-alignment") result.alignment = false; if (key === "--refresh") result.refresh = true; if (key === "--dry-run") result.dryRun = true; continue; } const value = values[++index]; if (!value || value.startsWith("--")) usage(`Missing value for ${key}`); if (key === "--story") result.story = value; else if (key === "--from") result.from = positive(value, key); else if (key === "--to") result.to = positive(value, key); else if (key === "--profile") result.profile = value; else if (key === "--output") { if (value === "all") outputs.push("audio", "audiobook", "video"); else outputs.push(productionOutputSchema.parse(value)); } else if (key === "--force") result.force = productionForceSchema.parse(value); else if (key === "--format" && (value === "mp3" || value === "m4b")) result.format = value; else usage(`Unknown argument: ${key}`); }
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(result.story) || !result.from || !result.to || result.to < result.from) usage("Required: --story <slug> --from N --to N with from <= to"); if (outputs.length) result.outputs = [...new Set(outputs)]; return result; }
function positive(value: string, key: string) { const parsed = Number(value); if (!Number.isSafeInteger(parsed) || parsed < 1) usage(`${key} must be a positive integer`); return parsed; }
function usage(message: string): never { throw new Error(`${message}\nUsage: npm run story:produce -- --story <slug> --from N --to N [--profile audiobook|story-video|everything] [--output audio|audiobook|video|all] [--artwork|--no-artwork] [--repair-qa|--no-repair-qa] [--alignment|--no-alignment] [--refresh] [--dry-run] [--force stage]`); }
function printProgress(event: Record<string, unknown>) { if (event.type === "production.chapter.started") process.stdout.write(`[${event.index}/${event.total}] Chapter ${event.chapter}\n`); else if (event.type === "production.stage") process.stdout.write(`  ${event.status === "reused" ? "↺" : event.status === "completed" ? "✓" : "→"} ${event.stage}${event.status === "reused" ? " (reused)" : ""}\n`); else if (event.type === "production.qa.repair") process.stdout.write(`  ↻ QA repair ${event.attempt}/${event.maximum} from ${event.stage}\n`); else if (event.type === "production.chapter.failed") process.stdout.write(`  ! ${event.error}\n`); }
function formatPlan(plan: Awaited<ReturnType<typeof runProduction>>["plan"],estimate?:CostEstimate) { const cost=estimate?.estimatedUsd!==undefined?`Historical provider estimate: $${estimate.estimatedUsd.toFixed(4)} (likely $${estimate.lowUsd?.toFixed(4)}–$${estimate.highUsd?.toFixed(4)}, ${estimate.confidence} confidence)`:"Cost estimate: unavailable—insufficient priced provider history. No provider call was made.";return [`Production dry run`, `Story: ${plan.story}`, `Chapters: ${plan.from}-${plan.to} (${plan.chapters.length})`, ...plan.stages.map((stage) => `${stage}: ${plan.counts[stage]?.reusable ?? 0} reusable, ${plan.counts[stage]?.required ?? 0} required`), `Estimated paid operations: LLM ${plan.estimates.llmOperations}, TTS ${plan.estimates.ttsOperations}, images ${plan.estimates.imageOperations}${plan.estimates.imagesPendingPlanning ? ` (+ ${plan.estimates.imagesPendingPlanning} chapter(s) awaiting scene plans)` : ""}`, `Final output: ${plan.finalOutputs.join(", ") || "chapter files"}`, cost].join("\n") + "\n"; }
function formatSummary(manifest: Awaited<ReturnType<typeof runProduction>>["manifest"]) { return [`Production ${manifest.status}`, `Chapters: ${manifest.selection.from}-${manifest.selection.to}`, `Completed: ${manifest.summary.completed}`, `Needs Review: ${manifest.summary.needsReview}`, `Failed: ${manifest.summary.failed}`, `Reused stages: ${manifest.summary.reusedStages}`, `New stages: ${manifest.summary.newStages}`, `QA warnings: ${manifest.summary.qaWarnings}`, `QA failures: ${manifest.summary.qaFailures}`, ...Object.entries(manifest.summary.exports).map(([type, path]) => `${type}: ${path}`), `Elapsed: ${(manifest.summary.elapsedMs / 1000).toFixed(1)}s`, `Manifest: stories/${manifest.story}/production-runs/${manifest.id}.json`].join("\n") + "\n"; }
main().catch((error) => { process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`); process.exitCode = 1; });
