#!/usr/bin/env node
import { pathToFileURL } from "node:url";
import { join, resolve } from "node:path";
import { listStories, getStoryOverview } from "../server/catalog.js";
import { StudioOperations } from "../server/operations.js";
import { loadEnvironment, resolveStudioRoot } from "../../src/config/env.js";

const slug=(v:string)=>{if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(v))throw new Error("Story must be a valid slug");return v;};
function options(values:string[]){const out:Record<string,string|boolean>={};for(let i=0;i<values.length;i++){const key=values[i]!;if(!key.startsWith("--"))throw new Error(`Unexpected argument: ${key}`);if(key==="--include-media"){out.includeMedia=true;continue;}const value=values[++i];if(!value||value.startsWith("--"))throw new Error(`Missing value for ${key}`);out[key.slice(2)]=value;}return out;}
export async function runProject(values:string[],d:{root:string;operations:Pick<StudioOperations,"createStory"|"updateMetadata"|"duplicateProject"|"createBackup"|"restoreBackup"|"cleanup"|"deleteProject">;stdout:(t:string)=>unknown}) {const [action,arg,...rest]=values;if(action==="restore"){if(!arg||rest.length)throw new Error("Restore requires a backup ZIP path");d.stdout(JSON.stringify(await d.operations.restoreBackup(resolve(arg)),null,2)+"\n");return;}const o=options(rest);if(action==="list"){d.stdout((await listStories(d.root)).map(item=>`${item.slug}\t${item.title}`).join("\n")+"\n");return;}if(action==="create"){const result=await d.operations.createStory({slug:slug(String(o.slug??arg??"")),title:String(o.title??""),author:o.author,description:o.description??"",tags:o.tags?String(o.tags).split(","):[],notes:o.notes??"",sourceLanguage:o["source-language"],outputLanguage:o["output-language"]});d.stdout(JSON.stringify(result,null,2)+"\n");return;}if(!arg)throw new Error(`${action} requires a story slug`);const story=slug(arg);if(action==="show"){d.stdout(JSON.stringify(await getStoryOverview(d.root,story),null,2)+"\n");return;}if(action==="update"){const current=(await getStoryOverview(d.root,story)).story;const result=await d.operations.updateMetadata(story,{title:o.title??current.title,author:o.author??current.author,description:o.description??current.description,tags:o.tags?String(o.tags).split(","):current.tags,notes:o.notes??current.notes,sourceLanguage:o["source-language"]??current.sourceLanguage,outputLanguage:o["output-language"]??current.outputLanguage});d.stdout(JSON.stringify(result,null,2)+"\n");return;}if(action==="duplicate"){if(!o.slug)throw new Error("Duplicate requires --slug");d.stdout(JSON.stringify(await d.operations.duplicateProject(story,{slug:slug(String(o.slug)),mode:o.mode==="full"?"full":"settings"}),null,2)+"\n");return;}if(action==="backup"){const result=await d.operations.createBackup(story,{includeMedia:Boolean(o.includeMedia)});d.stdout(JSON.stringify({...result,path:join(d.root,".ai-story-studio","backups",`${result.id}.zip`)},null,2)+"\n");return;}if(action==="cleanup"){if(!o.kind)throw new Error("Cleanup requires --kind");d.stdout(JSON.stringify(await d.operations.cleanup(story,{kind:o.kind}),null,2)+"\n");return;}if(action==="delete"){if(!o.confirm)throw new Error("Delete requires --confirm with the exact story title");d.stdout(JSON.stringify(await d.operations.deleteProject(story,{confirmation:o.confirm}),null,2)+"\n");return;}throw new Error(`Unknown project action: ${action}`);}
async function main(){const env=loadEnvironment(),root=resolveStudioRoot(env),operations=new StudioOperations(root,env);try{await runProject(process.argv.slice(2),{root,operations,stdout:t=>process.stdout.write(t)});}finally{await operations.close();}}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href)main().catch(e=>{process.stderr.write(`${e instanceof Error?e.message:String(e)}\n`);process.exitCode=1;});
