#!/usr/bin/env node
import { pathToFileURL } from "node:url";
import { loadEnvironment, resolveStudioRoot } from "../../src/config/env.js";
import { assertQueueSchema, createDatabasePool } from "../../src/queue/database.js";
import { ProductionQueueService } from "../../src/queue/production-service.js";
import { PostgresQueueRepository } from "../../src/queue/repository.js";
const option=(v:string[],name:string)=>{const i=v.indexOf(name);return i<0?undefined:v[i+1];};const positive=(v:string|undefined,name:string)=>{const n=Number(v);if(!Number.isSafeInteger(n)||n<1)throw new Error(`${name} must be a positive integer`);return n;};const required=(v:string|undefined,a:string)=>{if(!v)throw new Error(`${a} requires an ID`);return v;};
async function main(){let values=process.argv.slice(2);if(values[0]?.startsWith("--"))values=["submit",...values];const[action,id,...rest]=values;const env=loadEnvironment(),root=resolveStudioRoot(env);if(!env.DATABASE_URL)throw new Error("DATABASE_URL is required for durable queue commands. Start Postgres and run npm run db:migrate.");const pool=createDatabasePool(env.DATABASE_URL);try{await assertQueueSchema(pool);const repository=new PostgresQueueRepository(pool,env.QUEUE_EVENT_RETENTION_DAYS),service=new ProductionQueueService(root,env,repository);let result:unknown;if(action==="submit"){const story=option(rest,"--story");if(!story)throw new Error("Submit requires --story");result=await service.submit(story,{from:positive(option(rest,"--from"),"--from"),to:positive(option(rest,"--to"),"--to"),profile:option(rest,"--profile"),outputs:option(rest,"--output")==="all"?["audiobook","video"]:option(rest,"--output")?[option(rest,"--output")]:undefined,alignment:rest.includes("--alignment")?true:rest.includes("--no-alignment")?false:undefined});}else if(action==="list")result=await repository.listJobs({page:Number(option(rest,"--page")??1),pageSize:Number(option(rest,"--page-size")??50),status:option(rest,"--status") as any,story:option(rest,"--story")});else if(action==="show"){const job=await repository.getJob(required(id,action));if(!job)throw new Error("Queue job was not found");result={job,items:await repository.listWorkItems(job.id,{page:1,pageSize:100}),events:await repository.listRecentEvents(job.id,50)};}else if(action==="pause")result=await repository.requestPause(required(id,action));else if(action==="resume")result=await repository.resume(required(id,action));else if(action==="cancel")result=await repository.requestCancel(required(id,action));else if(action==="review")result=await repository.listNeedsReview({page:Number(option(rest,"--page")??1),pageSize:Number(option(rest,"--page-size")??50)});else if(action==="retry")result=await repository.retryItem(required(id,action),option(rest,"--stage"));else if(action==="resolve")result=await repository.resolveItem(required(id,action));else if(action==="skip")result=await repository.resolveItem(required(id,action),true);else throw new Error("Usage: story:queue <submit|list|show|pause|resume|cancel|review|retry|resolve|skip> ...");process.stdout.write(JSON.stringify(result,null,2)+"\n");}finally{await pool.end();}}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href)main().catch(e=>{process.stderr.write(`${e instanceof Error?e.message:String(e)}\n`);process.exitCode=1;});
