#!/usr/bin/env node
import { pathToFileURL } from "node:url";
import { getStoryOverview, updateStorySettings } from "../server/catalog.js";
import { loadEnvironment, resolveStudioRoot } from "../../src/config/env.js";

const validSlug=(v:string)=>{if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(v))throw new Error("Story must be a valid slug");return v;};
function parseJson(value:string){try{const parsed=JSON.parse(value);if(!parsed||Array.isArray(parsed)||typeof parsed!=="object")throw new Error();return parsed as Record<string,unknown>;}catch{throw new Error("--json must be a JSON object");}}
function merge(base:any,patch:any):any { if(!patch||typeof patch!=="object"||Array.isArray(patch))return patch;const out={...base};for(const [key,value] of Object.entries(patch))out[key]=value&&typeof value==="object"&&!Array.isArray(value)?merge(base?.[key]??{},value):value;return out; }
export async function runSettings(values:string[],root:string,stdout:(text:string)=>unknown){const [action,storyRaw,...rest]=values;const story=storyRaw&&validSlug(storyRaw);if(!story||!["show","set"].includes(action??""))throw new Error("Usage: story:settings <show|set> <story> [--json '{...}']");const current=(await getStoryOverview(root,story)).story;if(action==="show"){if(rest.length)throw new Error("Show does not accept additional options");stdout(JSON.stringify(current,null,2)+"\n");return;}if(rest[0]!=="--json"||!rest[1]||rest.length!==2)throw new Error("Set requires --json with a settings patch");const patch=parseJson(rest[1]);const input=merge({title:current.title,author:current.author??"",description:current.description,tags:current.tags,notes:current.notes,sourceLanguage:current.sourceLanguage,outputLanguage:current.outputLanguage,recentChapterSummaries:current.context.recentChapterSummaries,narrationSettings:current.narrationSettings,translation:current.pipeline.translation,narration:current.pipeline.narration,qa:current.pipeline.qa,scenePlanner:current.pipeline.scenePlanner,tts:current.pipeline.tts,audio:current.audio,subtitles:current.subtitles,video:current.video,scenes:current.scenes,artwork:current.artwork},patch);stdout(JSON.stringify(await updateStorySettings(root,story,input),null,2)+"\n");}
async function main(){const env=loadEnvironment();await runSettings(process.argv.slice(2),resolveStudioRoot(env),t=>process.stdout.write(t));}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href)main().catch(e=>{process.stderr.write(`${e instanceof Error?e.message:String(e)}\n`);process.exitCode=1;});
