import { z } from "zod";
import { StoryBible } from "../domain/story-bible.js";
import { atomicWriteJson } from "../storage/atomic-write.js";
import { storyPaths } from "../storage/paths.js";
import { readJsonIfExists } from "../storage/story-files.js";
import { fingerprint } from "../utils/hash.js";
import { normalizeEntityName } from "./updater.js";

export const continuityTypeSchema = z.enum(["possible_contradiction", "timeline_conflict", "relationship_conflict", "identity_alias_ambiguity", "status_conflict", "location_conflict", "ability_item_conflict"]);
export const continuityFindingSchema = z.object({ id: z.string().regex(/^ctf_[a-f0-9]{24}$/), type: continuityTypeSchema, severity: z.enum(["info", "warning", "critical"]), entityIds: z.array(z.string()).min(1), chapters: z.array(z.number().int().positive()).min(1), explanation: z.string(), supportingFacts: z.array(z.object({ entityId: z.string().optional(), chapter: z.number().int().positive(), summary: z.string(), provenanceKind: z.string() })).min(1), evidenceFingerprint: z.string(), status: z.enum(["open", "accepted_new", "kept_existing", "intentional", "corrected", "merged", "dismissed"]).default("open"), resolutionNote: z.string().optional(), resolvedAt: z.string().optional() });
export const continuityReviewSchema = z.object({ version: z.literal(1), analyzedThroughChapter: z.number().int().nonnegative(), inputFingerprint: z.string(), updatedAt: z.string(), findings: z.array(continuityFindingSchema).default([]) });
export type ContinuityFinding = z.infer<typeof continuityFindingSchema>;
export type ContinuityResolution = ContinuityFinding["status"];

export function detectContinuityFindings(bible: StoryBible): ContinuityFinding[] {
  const findings: ContinuityFinding[] = []; const byId = new Map(bible.canonicalEntities.map((item) => [item.id, item])); const add = (value: Omit<ContinuityFinding, "id" | "evidenceFingerprint" | "status">) => { const evidenceFingerprint = fingerprint(value); const id = `ctf_${evidenceFingerprint.slice(0, 24)}`; if (!findings.some((item) => item.id === id)) findings.push({ ...value, id, evidenceFingerprint, status: "open" }); };
  for (const entity of bible.canonicalEntities) {
    const events = bible.entityTimeline.filter((item) => item.entityId === entity.id).sort((a, b) => a.chapter - b.chapter); let death: typeof events[number] | undefined; let resurrectionChapter: number | undefined;
    for (const event of events) { if (event.type === "death" || normalizeEntityName(event.status ?? "") === "dead") { death = event; resurrectionChapter = undefined; continue; } if (event.type === "resurrection") { resurrectionChapter = event.chapter; death = undefined; continue; } if (death && event.type === "appearance" && event.chapter > death.chapter && (!resurrectionChapter || event.chapter < resurrectionChapter)) add({ type: "status_conflict", severity: "critical", entityIds: [entity.id], chapters: [death.chapter, event.chapter], explanation: `${entity.canonicalName} appears after being recorded dead without an intervening resurrection.`, supportingFacts: [{ entityId: entity.id, chapter: death.chapter, summary: death.summary, provenanceKind: death.provenance.kind }, { entityId: entity.id, chapter: event.chapter, summary: event.summary, provenanceKind: event.provenance.kind }] }); }
    const locations = events.filter((item) => item.type === "location"); for (let index = 1; index < locations.length; index++) { const prior = locations[index - 1]!, current = locations[index]!; if (prior.chapter === current.chapter && normalizeEntityName(prior.summary) !== normalizeEntityName(current.summary)) add({ type: "location_conflict", severity: "warning", entityIds: [entity.id], chapters: [current.chapter], explanation: `${entity.canonicalName} has incompatible location events in the same chapter.`, supportingFacts: [prior, current].map((item) => ({ entityId: entity.id, chapter: item.chapter, summary: item.summary, provenanceKind: item.provenance.kind })) }); }
    for (const event of events.filter((item) => /never (?:met|knew|known)|first (?:meets|met)/i.test(item.summary))) { const prior = bible.canonicalRelationships.find((item) => (item.sourceEntityId === entity.id || item.targetEntityId === entity.id) && item.startChapter < event.chapter && /meet|know|friend|ally|rival|enemy|teacher|student/i.test(item.type)); if (prior) add({ type: "relationship_conflict", severity: "critical", entityIds: [prior.sourceEntityId, prior.targetEntityId], chapters: [prior.startChapter, event.chapter], explanation: `${entity.canonicalName}'s Chapter ${event.chapter} claim conflicts with an earlier recorded relationship.`, supportingFacts: [{ entityId: prior.sourceEntityId, chapter: prior.startChapter, summary: `${byId.get(prior.sourceEntityId)?.canonicalName ?? "Entity"} ${prior.type} ${byId.get(prior.targetEntityId)?.canonicalName ?? "entity"}`, provenanceKind: "relationship" }, { entityId: entity.id, chapter: event.chapter, summary: event.summary, provenanceKind: event.provenance.kind }] }); }
  }
  const aliasOwners = new Map<string, string[]>(); for (const entity of bible.canonicalEntities) for (const name of [entity.canonicalName, entity.originalName, ...entity.aliases]) { const key = normalizeEntityName(name); if (key) aliasOwners.set(key, [...(aliasOwners.get(key) ?? []), entity.id]); } for (const [alias, ids] of aliasOwners) { const unique = [...new Set(ids)]; if (unique.length > 1) add({ type: "identity_alias_ambiguity", severity: "warning", entityIds: unique, chapters: unique.map((id) => byId.get(id)!.firstAppearance), explanation: `The normalized name or alias '${alias}' resolves to multiple entities.`, supportingFacts: unique.map((id) => ({ entityId: id, chapter: byId.get(id)!.firstAppearance, summary: byId.get(id)!.canonicalName, provenanceKind: "extraction" })) }); }
  const ownership = bible.canonicalRelationships.filter((item) => item.state === "current" && /owns|possesses|has/i.test(item.type)); for (let i = 0; i < ownership.length; i++) for (let j = i + 1; j < ownership.length; j++) { const a = ownership[i]!, b = ownership[j]!; if (a.targetEntityId === b.targetEntityId && a.sourceEntityId !== b.sourceEntityId) add({ type: "ability_item_conflict", severity: "warning", entityIds: [a.sourceEntityId, b.sourceEntityId, a.targetEntityId], chapters: [a.startChapter, b.startChapter], explanation: `${byId.get(a.targetEntityId)?.canonicalName ?? "An entity"} has multiple current owners.`, supportingFacts: [a, b].map((item) => ({ entityId: item.sourceEntityId, chapter: item.startChapter, summary: `${byId.get(item.sourceEntityId)?.canonicalName ?? "Entity"} ${item.type} ${byId.get(item.targetEntityId)?.canonicalName ?? "entity"}`, provenanceKind: "relationship" })) }); }
  return findings.sort((a, b) => Math.max(...b.chapters) - Math.max(...a.chapters));
}

export async function analyzeAndPersistContinuity(root: string, slug: string, bible: StoryBible, chapter: number) { const paths = storyPaths(root, slug, chapter); const inputFingerprint = fingerprint({ version: 1, entities: bible.canonicalEntities, timeline: bible.entityTimeline, relationships: bible.canonicalRelationships }); const priorRaw = await readJsonIfExists(paths.continuityReview); const prior = priorRaw ? continuityReviewSchema.safeParse(priorRaw) : undefined; const priorFindings = prior?.success ? prior.data.findings : []; const resolutions = new Map(priorFindings.filter((item) => item.status !== "open").map((item) => [item.id, item])); const detected = detectContinuityFindings(bible).map((item) => resolutions.get(item.id) ? { ...item, status: resolutions.get(item.id)!.status, resolutionNote: resolutions.get(item.id)!.resolutionNote, resolvedAt: resolutions.get(item.id)!.resolvedAt } : item); const currentIds = new Set(detected.map((item) => item.id)); const retained = priorFindings.filter((item) => !currentIds.has(item.id) && (item.status !== "open" || Math.max(...item.chapters) > chapter)); const findings = [...detected, ...retained].sort((a, b) => Math.max(...b.chapters) - Math.max(...a.chapters)); const document = continuityReviewSchema.parse({ version: 1, analyzedThroughChapter: Math.max(chapter, prior?.success ? prior.data.analyzedThroughChapter : 0), inputFingerprint, updatedAt: new Date().toISOString(), findings }); await atomicWriteJson(paths.continuityReview, document); const chapterFindings = findings.filter((item) => item.chapters.includes(chapter)); const artifact = { version: 1, chapter, inputFingerprint, analyzedAt: document.updatedAt, findingIds: chapterFindings.map((item) => item.id), openFindings: chapterFindings.filter((item) => item.status === "open").length }; await atomicWriteJson(paths.continuityAnalysis, artifact); return { document, artifact, reused: prior?.success && prior.data.inputFingerprint === inputFingerprint };
}
export async function resolveContinuityFinding(root: string, slug: string, id: string, resolution: ContinuityResolution, note?: string) { if (resolution === "open") throw new Error("Choose a resolution action"); const paths = storyPaths(root, slug, 1); const raw = await readJsonIfExists(paths.continuityReview); const document = continuityReviewSchema.parse(raw); const finding = document.findings.find((item) => item.id === id); if (!finding) throw new Error("Continuity finding was not found"); finding.status = resolution; finding.resolutionNote = note; finding.resolvedAt = new Date().toISOString(); document.updatedAt = finding.resolvedAt; await atomicWriteJson(paths.continuityReview, document); return finding; }
