import { StoryBible, storyBibleSchema } from "../domain/story-bible.js";
import { contextBeforeChapter, normalizeEntityName } from "./updater.js";

export type StoryContextOptions = { recentSummaryCount?: number; maxEntities?: number; maxRelationships?: number; maxTimelineEvents?: number; maxCharacters?: number };
export function retrieveRelevantContext(bible: StoryBible, chapterText: string, chapter: number, options: StoryContextOptions = {}) {
  const prior = contextBeforeChapter(bible, chapter, options.recentSummaryCount ?? 5); const normalizedText = normalizeEntityName(chapterText); const maxEntities = options.maxEntities ?? 60;
  const scored = prior.canonicalEntities.map((entity) => { const names = [entity.canonicalName, entity.originalName, ...entity.aliases].filter(Boolean); const mentioned = names.some((name) => { const key = normalizeEntityName(name); return key.length >= 2 && normalizedText.includes(key); }); const recent = entity.lastKnownAppearance >= chapter - 10; return { entity, score: mentioned ? 1000 : entity.canonicalNameLocked ? 500 : recent ? 100 : 0 }; }).filter((item) => item.score > 0).sort((a, b) => b.score - a.score || b.entity.lastKnownAppearance - a.entity.lastKnownAppearance).slice(0, maxEntities);
  if (!scored.length) scored.push(...prior.canonicalEntities.slice().sort((a, b) => b.lastKnownAppearance - a.lastKnownAppearance).slice(0, Math.min(12, maxEntities)).map((entity) => ({ entity, score: 1 })));
  const entities = scored.map((item) => item.entity); const ids = new Set(entities.map((item) => item.id)); const relations = prior.canonicalRelationships.filter((item) => ids.has(item.sourceEntityId) || ids.has(item.targetEntityId)).sort((a, b) => b.startChapter - a.startChapter).slice(0, options.maxRelationships ?? 100); for (const relation of relations) { ids.add(relation.sourceEntityId); ids.add(relation.targetEntityId); }
  const selectedEntities = prior.canonicalEntities.filter((item) => ids.has(item.id)).slice(0, maxEntities); const names = new Set(selectedEntities.flatMap((item) => [item.canonicalName, item.originalName, ...item.aliases].map(normalizeEntityName)));
  const result = structuredClone(prior); result.merges = []; result.canonicalEntities = selectedEntities.map((item) => ({ ...item, provenance: item.provenance.slice(-20) })); result.canonicalRelationships = relations.map((item) => ({ ...item, provenance: item.provenance.slice(-20) })); result.entityTimeline = prior.entityTimeline.filter((item) => ids.has(item.entityId)).sort((a, b) => b.chapter - a.chapter).slice(0, options.maxTimelineEvents ?? 120).sort((a, b) => a.chapter - b.chapter);
  for (const key of ["characters", "locations", "factions", "abilities", "classes", "ranks", "items", "creatures", "systemTerms"] as const) result[key] = result[key].filter((item) => names.has(normalizeEntityName(item.canonicalEnglishName)) || names.has(normalizeEntityName(item.originalName))) as never;
  result.relationships = result.relationships.filter((item) => names.has(normalizeEntityName(item.subject)) || names.has(normalizeEntityName(item.object))).slice(0, options.maxRelationships ?? 100);
  result.translationTerms = result.translationTerms.filter((item) => item.locked || normalizedText.includes(normalizeEntityName(item.original)) || normalizedText.includes(normalizeEntityName(item.canonicalEnglish))).slice(0, 120);
  const maxCharacters = options.maxCharacters ?? 32_000; while (JSON.stringify(result).length > maxCharacters && result.entityTimeline.length) result.entityTimeline.shift(); while (JSON.stringify(result).length > maxCharacters && result.canonicalRelationships.length) result.canonicalRelationships.pop(); while (JSON.stringify(result).length > maxCharacters && result.translationTerms.length) result.translationTerms.pop(); while (JSON.stringify(result).length > maxCharacters && Object.keys(result.chapterSummaries).length) delete result.chapterSummaries[Object.keys(result.chapterSummaries)[0]!]; while (JSON.stringify(result).length > maxCharacters && result.canonicalEntities.length > 1) { const removed = result.canonicalEntities.pop()!; const keep = new Set(result.canonicalEntities.map((item) => item.id)); result.canonicalRelationships = result.canonicalRelationships.filter((item) => keep.has(item.sourceEntityId) || keep.has(item.targetEntityId)); result.entityTimeline = result.entityTimeline.filter((item) => item.entityId !== removed.id); } while (JSON.stringify(result).length > maxCharacters && result.canonicalEntities.some((item) => item.provenance.length > 1)) for (const entity of result.canonicalEntities) entity.provenance = entity.provenance.slice(-Math.max(1, Math.floor(entity.provenance.length / 2))); if (JSON.stringify(result).length > maxCharacters) for (const entity of result.canonicalEntities) { entity.description = entity.description.slice(0, 500); entity.notes = entity.notes.slice(0, 500); } if (JSON.stringify(result).length > maxCharacters) { for (const key of ["characters", "locations", "factions", "abilities", "classes", "ranks", "items", "creatures", "systemTerms"] as const) result[key] = [] as never; result.relationships = []; } if (JSON.stringify(result).length > maxCharacters) { result.chapterSummaries = {}; for (const entity of result.canonicalEntities) { entity.provenance = entity.provenance.slice(-1); entity.description = entity.description.slice(0, 120); entity.notes = entity.notes.slice(0, 120); entity.aliases = entity.aliases.slice(0, 12); } }
  return storyBibleSchema.parse(result);
}
